ash-project/ash

lib/ash/actions/read.ex
test/type/type_test.exs

Skips failing test to clarify supported state of trunk

test(type_test): skips failing type test

---

.github/workflows/elixir.yml

This is a POC to see if we can validate sub-projects in CI when making changes to the ash project. It runs `mix compile --warnings-as-errors` and `mix test` on each of the subprojects using the current branch of `ash`. This will give advanced notice if a change in ash will require a fix in a subproject.

chore: Add validation of sub-projects

---

lib/ash/type/atom.ex
test/type/type_test.exs

This is something I came across that I wanted during some experimentation with Ash, and I decided to take a crack at drafting a quick PR for it! 
Basically when defining an `:atom` attribute I wanted to ensure that the input value is restricted to a pre-defined list of atoms.
Quick example in context:
```elixir
attribute :type, :atom, allow_nil?: false, constraints: [
one_of: [:text_post, :video_post, :image_post]
]
```
Feedback encouraged! I love what I see of the Ash framework so far 😄

feat: Add `:one_of` constraint to the Atom type

---

lib/ash/actions/create.ex
test/actions/create_test.exs

fix: do not require private attributes in create api

---

lib/ash/resource/validation/builtins.ex
lib/ash/resource/validation/string_length.ex
test/resource/validation/string_length_test.exs

Here's a first crack at a string length validator. It can be used with `:min`, `:max`, `:exact` and a combination of `:min` and `:max`. The contents of the default error message is dependent on the other params provided, and the error message can be overridden.
```elixir
validate string_length(:body, min: 3, message: "must be min %{min} characters")
```

improvement: Implement string length validation

---

lib/ash/dsl/extension.ex

**I found just one example where this fix is needed, maybe it needs to be the other way around**
Example: https://hexdocs.pm/ash/1.36.3/Ash.Resource.Dsl.html#content
The generated `code_interface` TOC link is `#module-code-interface` while the correct link would be `#module-code_interface`.

Fix documentation TOC

---

lib/ash/resource/dsl.ex
lib/ash/resource/transformers/replace_timestamps.ex

```elixir
attributes do
timestamps()
create_timestamp :inserted_at
update_timestamp :updated_at
end
```
I couldn't find a more elegant way to implement this, if there is one I'd be happy to change it :)

improvement: Add timestamps() attribute

---

documentation/topics/pagination.md
lib/ash/api/api.ex

i.e. warnings that appear when you run `mix docs`
Although this PR doesn't fix the majority of them, since the majority are errors from referring to `@moduledoc false` modules in docs and typespecs.

docs: Fix some documentation warnings

---

lib/ash/type/float.ex
lib/ash/type/type.ex

Also update `Ash.Type` documentation to use the float module as an example of a custom type.
Fixes #203

improvement: Add float type

---

lib/ash/type/type.ex

Allow using type aliases when using `cast_stored` and `dump_to_native` callbacks

Resolve type aliases

---

documentation/introduction/getting_started.md

The `Api.get` example in the docs uses the email instead of the ID to
get the newly created resource. Trying this locally while running
through the getting started tutorial returns a `nil` resource using the
email, but the correct resource when using the ID.
This fix updates the docs to use the ID in the get call.

Docs: Fix Api.get example

---

lib/ash/resource/calculation/calculation.ex

I would like a way to specify that a calculation value can't return nil to use in generating the graphql type. Let me know if there is any validation I need to add and where I should add it.

allow specifying that calculation can't be nil

---

lib/ash/type/decimal.ex

Ash.Type.Decimal wasn't working on embedded resources. It was serialised as a string. I've added `Ash.Type.Decimal.cast_input/2` and `Ash.Type.Decimal.cast_stored/2` implementations for string-encoded values.

fix: Decimal casting issues on ash_postgres

---

lib/ash/api/interface.ex
lib/ash/error/invalid/no_such_resource.ex
test/actions/read_test.exs

Also rename `id` parameter to `id_or_filter` for `get!/3` for clarity

improvement: Add detailed parameter checking for Api read functions

---

documentation/introduction/getting_started.md

Adds the default value of the `private?` field to the description of `create_timestamp`

docs: Update create_timestamp description

---

lib/ash/actions/create.ex
lib/ash/actions/update.ex

As discussed on Discord.
This rectifies the edge-case of updating a Resource that doesn't have multitenancy enabled, while modifying one of it's related resources which does. i.e: Tenant belongs_to Address, while Address has a tenant_id key on it for multi-tenancy.

fix: set tenant even on non-tenant resources where relevant

---

test/actions/belongs_to_test.exs

Failing test for issue #257 
Updating a related field in a change on a one way (`belongs_to`) relationship works in 1.47.6, but now failing in master.
Wasn't sure where to put the test, i couldn't find any examples using a one way belongs_to relationship

chore: Failing test for updating a relation in a change

---

lib/ash/sort/sort.ex

fix: update type spec for Ash.Sort to include single atom instead of only list.

---

lib/ash/changeset/changeset.ex

`Map.get/2` returns a value or `nil`.

Fix the typespec for the `Ash.Changeset.get_data/2` function

---

config/config.exs

No longer have to see `warning: use Mix.Config is deprecated. Use the Config module instead
config/config.exs:1` after running mix commands.

chore: update to import config

---

lib/ash/data_layer/simple/simple.ex
lib/ash/error/simple_data_layer/no_data_provided.ex
lib/ash/query/query.ex
test/resource/resource_test.exs

Issue: https://github.com/ash-project/ash/issues/266
I don't know if `class: invalid` fits with the new `no data provided` error. I just thought of it as happening when there is an invalid read from a resource.

improve: Provide api read error message on no data set

---

lib/ash/error/invalid/multiple_results.ex

Fixes #293
Indicate that MultipleResult error is probably failing due to a missing filter.
The docs for filters live here: https://hexdocs.pm/ash/expressions.html#filters

improvement: Improve usability of finding by primary key (ID)

---

lib/ash/api/api.ex
lib/ash/api/dsl.ex
lib/ash/engine/engine.ex
lib/ash/engine/request.ex
lib/ash/resource/actions/shared_options.ex

Some minor formatting/spelling error fixes and adding an example for `:upsert_identity`

Spelling fixes, add :upsert_identity example

---

lib/ash/resource/change/builtins.ex
lib/ash/resource/change/relate_actor.ex
test/resource/changes/relate_actor_test.exs

The built-in change function called `relate_actor/1` for automatically associating a resource with an actor now takes a Keyword list. It also adds an option called `:allow_nil?` following previous conventions of Ash and it defaults to false, the current behaviour. When set to true, it will not add an error to the changeset if the actor is `nil`.

improvement: added options to the built-in function `relate_actor/1`

---

lib/ash/filter/filter.ex

Moves the end of a code block example to actually end at the end of the code block, whereas currently it looks like this:

docs: Fix code block that wrapped non-code text

---

lib/ash/changeset/changeset.ex
test/changeset/changeset_test.exs

I have defined an argument for an action:
argument :some_boolean, :boolean, allow_nil?: false, default: false
When I retrieve that argument in a changeset, the value is `nil`.
If the default is `true`, it correctly comes in as `true`.
This pr contains a failing test for this scenario

fix: False default value for argument is nil in changeset

---

documentation/tutorials/get-started.md

Updated getting started tutorial to use `Helpdesk.Support` instead of `Helpdesk.Tickets` to avoid confusion.

docs: Update tutorial to use Helpdesk.Support

---

lib/ash/resource/dsl.ex
lib/ash/resource/transformers/default_accept.ex
lib/ash/resource/transformers/validate_accept.ex
test/resource/validate_accept_test.exs

This PR aims to resolve #366 by raising an error if an attribute name specified in an `accept` or `reject` field of an action is either private or not an attribute at all.
I'm not sure if there is anything else that needs to be done here (looking at the contributor checklist).
I'm also not sure if my change in `default_accept` is me not understanding something or me finding a bug.

improvement: validate accepted and rejected attributes in actions

---

lib/ash/api/diagram/diagram.ex
test/api/diagram_test.exs

This PR resolves #392 by printing arguments and attributes for resource actions in class diagrams, with an upper limit of 4 (the rest hidden with ellipsis)

feat: list arguments for resource actions in class diagrams

---

documentation/tutorials/get-started.md

Getting Started guide exemplifies `create!/1` as returning  an `{:ok, #Resource<>}` tuple, when it should be `#Resource<>`
- [ X] Documentation changes

docs: Correct create!/1 return typo in Getting Started Guide

---

lib/ash/changeset/changeset.ex
test/changeset/changeset_test.exs

As described in #411, this fixes an issue where applying a custom validation message for a validation that returns a list of errors, would cause weirdnesses to happen.
Because the `present` validation takes a list of fields to validate, it returns a list of errors, possibly including one for each field. 
This worked when no message was provided - the list of `Ash.Error.Changes.InvalidAttribute` errors was passed to `Ash.Changeset.add_error/3` and all was fine - but when a message was provided, the list of errors was converted to a single string (the message) and that was stored on the changeset instead.
Now each element of the list gets the same treatment as a single error, and it seems to work well in my testing! Closes #411

fix: allow overriding validation message on a list of errors

---

.github/workflows/elixir.yml

These were disabled due to a dialyzer error in Erlang, which has since been fixed in a newer Erlang version.
I installed these versions locally and checked that everything still works as expected; and dialyzer no longer errors.
Closes #382

CI: re-enable latest versions of Elixir/Erlang

---

lib/mix/mermaid.ex
lib/mix/tasks/generate_flow_charts.ex
lib/mix/tasks/generate_resource_diagrams.ex

Support a variety of different formats for all mermaid diagrams and flowcharts.
Closes #422

improvement: SVG, PDF, PNG, Markdown and plain mermaid formats

---

lib/ash/data_layer/data_layer.ex

This is causing the [`ash_gen_server` build to fail](https://github.com/team-alembic/ash_gen_server/actions/runs/3324500691/jobs/5496160933)

fix(DataLayer): incorrect typespec for `run_query/2` callback.

---

test/resource/upsert_and_load_children_test.exs

Add test demonstrating minimal example of strange upsert behaviour with lazy load children.
In particular, lazy loading the children of the parent resource in a global change block seems to affect the behaviour when upserting children through the parent.

test: Add test demonstrating minimal example of strange upsert behaviour

---

lib/ash/actions/managed_relationships.ex
test/resource/relationships/belongs_to_test.exs

fix: don't add required belongs_to error if changeset is invalid

---

documentation/topics/monitoring.md
lib/ash/query/query.ex

Includes removing a duplicate reference to `[:ash, :after_action]` in the docs.
I couldn't work out how to write a test for it (the existing Tracer test didn't seem to invoke it) but I did load this branch into my app and verified that recording telemetry via `summary("ash.query.stop.duration", unit: {:native, :millisecond}, tags: [:resource_short_name])` works as expected.

fix: Add missing `[:ash, :query]` telemetry

---

documentation/topics/code-interface.md

- Updated the Code Interface documentation to align with the naming in the tutorial app.
- Fixed a reference to `interface_options` that was not showing correctly.

docs: Update Code Interface Doc

---

lib/ash/actions/load.ex
test/policy/rbac_test.exs
test/support/policy_rbac/resources/file.ex
test/support/policy_rbac/resources/organization.ex

When using ash_graphql it would be nice to only get the selects inside the authorizer which were actually selected. This was the change I had to make to get it to work.  
The related query also contains other fields, I saw `limit: 1` during my debugging, is this something that should also be passed here.

fix: respect selects in related_query

---

documentation/topics/policies.md

This PR changes `Ash.Policy.Forbidden.Error.report/2` to `Ash.Error.Forbidden.Policy.report/2` in `Policies` docs. 
The `Ash.Policy.Forbidden.Error` module does not exist

docs: Fix wrong policy explanation module in docs.

---

documentation/tutorials/get-started.md

docs: Fix broken link on Getting Started Tutorial

---

documentation/topics/multitenancy.md
lib/ash/actions/read.ex
lib/ash/error/invalid/tenant_required.ex
test/actions/multitenancy_test.exs

I'm currently poking with the stick into [ash_example](https://github.com/ash_project/ash_example). Without tenant specified (there is no way to pass tenant in a request for a moment), I receive an ugly looking error:
```json
{
"data": {
"listTickets": {
"edges": [
{
"cursor": "g2wAAAABbQAAACRlOGE1YzY0NC1lMWM3LTQyOGEtYjk2YS0wMDk4NTM1NTBjMDhq",
"node": {
"description": null,
"id": "e8a5c644-e1c7-428a-b96a-009853550c08",
"reporter": null,
"representative": null,
"response": null,
"status": "new",
"subject": "sdabc"
}
}
],
"pageInfo": {
"hasNextPage": false,
"hasPreviousPage": false
}
}
},
"errors": [
{
"locations": [
{
"column": 9,
"line": 11
}
],
"message": "Raised error: 02762ef1-a47d-4ed1-96ad-ce5b4f5d70b3\n\n** (ErlangError) Erlang error: {%Ash.Error.Unknown{errors: …
```

improvement: Add Ash.Error.Invalid.TenantRequired error

---

lib/ash/changeset/changeset.ex
test/changeset/changeset_test.exs

Because `action` was reassigned, the complete action was passed along instead of just the name.

fix: only pass action name in Ash.Changeset.for_action

---

documentation/topics/monitoring.md
lib/ash/api/info.ex

Because it currently looks like a HTML tag, it's not being rendered visibly - 
This tweaks the short name to render in parens instead, and adds a note about what the short name actually is. (And the typespec was incorrect)
(I can't really figure out how a short name would actually be defined in an API module, so I guess it's just the default which is an atom!)

docs: Render `api_short_name` visibly in the Monitoring guide

---

documentation/topics/glossary.md

An initial pass at setting up a glossary of terms and concepts within Ash, with brief definitions and links to other documentation.
As you can see I'm still fleshing out the definitions, but if there is any feedback on what's written already (or terms that should be added), let me know!

docs: Add Glossary guide 

---

lib/ash/notifier/pub_sub/pub_sub.ex

After conversion to HTML, the placeholders in the code sample are treated as HTML elements and not rendered correctly.
(kinda like #500, denote the placeholders with parentheses instead of angle brackets)

docs: Update pubsub docs to be readable on AshHQ

---

lib/ash/flow/flow.ex

Pretty self-explanatory :). Looked up the missing word from the Flow guide.

Fix typo in Ash.Flow moduledoc

---

documentation/topics/development-utilities.md

I was frustrated by the existing code snippet for the configuration of the spark formatter.
Basically the ellipsis means I can't copy paste it to my own config, so I added a complete code snipped from the Ash-HQ config.
I kept the "If you use a different module than Ash.Resource" part in a separate subsection.

docs: add drop-in configuration code snippet for the Spark formatter plugin

---

lib/ash/changeset/changeset.ex
lib/ash/error/error.ex
lib/ash/error/stacktrace.ex
lib/ash/resource/change/after_action.ex
lib/ash/resource/change/after_transaction.ex
lib/ash/resource/change/before_action.ex
lib/ash/resource/change/before_transaction.ex
lib/ash/resource/change/builtins.ex
test/resource/changes/lifecycle_hooks_test.exs
test/resource/changes/load_test.exs

This allows very-slightly-more-succinct access to lifecycle hooks, eg:
change before_action(&IO.inspect/1)
rather than:
change fn changeset -> Ash.Changeset.before_action(changeset, &IO.inspect/1) end
It's pretty basic, but I think lifecycle hooks are very likely the most common reason that custom changes get written so this should reduce the cognitive burden of writing hooks.
* Add (better) typespecs for `Ash.Changeset`, `Ash.Error` and `Ash.Error.Stacktrace`.
* Remove redundant `change_dependencies` field from `Ash.Changeset`.
* Add new `phase` field to `Ash.Changeset` which can be used to introspect whether a changeset is currently running lifecycle hooks.

improvement: Add builtin changes for lifecycle hooks.

---

lib/ash/actions/read.ex
lib/ash/changeset/changeset.ex
lib/ash/query/query.ex
lib/ash/resource/change/builtins.ex
lib/ash/resource/preparation/after_action.ex
lib/ash/resource/preparation/before_action.ex
lib/ash/resource/preparation/builtins.ex
test/resource/preparations/lifecycle_hooks_test.exs

This allows folks to add lifecycle hooks right in their read actions, eg:
```elixir
prepare before_action(&IO.inspect(&1))
```
rather than:
```elixir
prepare fn query, _context -> Ash.Query.before_action(query, &IO.inspect/1) end
```
* Add (better) typespecs for `Ash.Query`.
* Remove redundant guards as detected by dialyzer.
* Add new `phase` field to `Ash.Query` which can be used to introspec whether a query is currently running lifecycle hooks.

improvement: Add `before_action/1` and `after_action/1` to `Ash.Resource.Preparations.Builtins`.

---

lib/ash/resource/change/builtins.ex

This will allow them to render correctly on Hexdocs and AshHQ
Currently they're a bit broken because they're only using two spaces for indentation, not 4 like the rest of the examples.

docs: format code blocks appropriately

---

lib/ash/error/forbidden/policy.ex

Checks that result in {:ok, :unknown} no longer cause an exception to be raised when describing them for output to the log file.

fix: prevent exception when describing some checks

---

lib/ash/actions/flows/read.ex
lib/ash/actions/flows/read/fake_result.ex
lib/ash/actions/read.ex
lib/ash/error/framework/flag_assertion_failed.ex
lib/ash/flags.ex

Returns an empty result, but at least it returns a result so now we have failing tests with this feature flag, rather than a compile error.

improvement(read_uses_flow?): Build stub for `Ash.Actions.Flows.Read`.

---

lib/ash/actions/create.ex

Currently when running upserts with `upsert_identity` option set to some identity, on resource with attribute multitenancy, it sets the `on_conflict` fields to only identity fields and ignores the multitenancy attribute. This PR aims to fix that by adding this attribute if needed.

Fix: Add tenant attribute to identity attributes on upserts

---

lib/ash/flow/executor/ash_engine.ex
lib/ash/flow/step/create.ex

Currently there's no way to specify upsert options for create actions in the Flows. 
This PR adds support for that by adding this to Spark schema and passes it in AshEngine to `Ash.Actions.Create.as_requests` function.

Improvement: Add upserts options to flow's create step

---

lib/ash/changeset/changeset.ex

Adds missing documentation for `Ash.Changeset.add_error/3`:

Improve documentation for Ash.Changeset.add_error/3

---

lib/ash/api/api.ex

docs: `bulk_create` does not support automatic `upsert_fields`

---

lib/ash/type/module.ex
lib/ash/type/type.ex
test/type/module_test.exs

I needed this in an app the other day and I thought it would be worth contributing it back upstream.

improvement(Ash.Type.Module): Add `:module` type.

---

lib/ash/action_input.ex
lib/ash/changeset/changeset.ex

`Exception.exception?` [is deprecated](https://hexdocs.pm/elixir/1.12/Exception.html#exception?/1) and [will be removed in elixir 1.15](https://github.com/elixir-lang/elixir/blob/a64d42f5d3cb6c32752af9d3312897e8cd5bb7ec/lib/elixir/lib/exception.ex#L49)
`Kernel.is_exception` has been available [since elixir 1.11](https://hexdocs.pm/elixir/1.14/Kernel.html#is_exception/1), and [since ash requires elixir ~> 1.11](https://github.com/ash-project/ash/blob/main/mix.exs#L16) we are safe to depend on it.

fix: swap `Exception.exception?` for `Kernel.is_exception`

---

lib/ash/error/error.ex
lib/ash/error/forbidden.ex
lib/ash/error/forbidden/policy.ex

Some small things about forbidden errors:
Type `error_class` contained `:authorization` instead of `:forbidden`.
`ErrorKind.code()` for `Error.Forbidden` and `Error.Forbidden.Policy` was capitalized "Forbidden" when all other error codes are in lowercase.
(Moved `defp header(:invalid)` bellow `defp header(:forbidden)` to be consistent with order in other places inside the file.)

fix: add `:forbidden` to `error_class`, lowercase code for `Forbidden`

---

lib/ash/generator/generator.ex
test/actions/stream_test.exs
test/generator/generator_test.exs

This would eliminate this error ` ** (RuntimeError) generator/1 unimplemented for Ash.Type.Map` if the Resource has an attribute of type map that is not nullable and a generator is passed for that attribute.

Only create values for attributes that did not get a generator

---

lib/ash/error/engine_error.ex
lib/ash/error/invalid/limit_required.ex
lib/ash/error/invalid/pagination_required.ex
lib/ash/error/load/invalid_query.ex
lib/ash/error/load/no_such_relationship.ex
lib/ash/error/query/aggregates_not_supported.ex
lib/ash/error/query/calculations_not_supported copy.ex
lib/ash/error/query/invalid_filter_reference.ex
lib/ash/error/query/invalid_filter_value.ex
lib/ash/error/query/lock_not_supported.ex
lib/ash/error/query/no_complex_sorts_with_keyset_pagination.ex
lib/ash/error/query/no_such_attribute_or_relationship.ex
lib/ash/error/query/no_such_filter_predicate.ex
lib/ash/error/query/not_found.ex
lib/ash/error/query/read_action_required.ex
lib/ash/error/query/unsupported_predicate.ex

Still looking into errors and noticed that some implementations of `ErrorKind` have `class` and `stacktrace` while `ErrorKind` protocol does not have those methods. I assume that those are outdated placeholder things and can be removed, right?

fix: remove `class` and `stacktrace` from `ErrorKind` implementations

---

lib/ash/code_interface.ex

Looking at the code of code_interface saw some inconsistencies when it comes to `Keyword.drop` calls in api calls.
`action` was dropping `:changeset` when it should have dropped `:input`.
`action!` did the same plus `tenant` was missing in drops.
`read` and `read!` were missing `tracer` drop.
`create!` was missing `tenant` drop.
Reordered drop keys to be consistently - `[...specific_keys, :actor, :tenant, :authorize?, :tracer]`. 
And in two places replaced simple `||` with `> Kernel.||`, just because majority of relevant places used later form.

fix: drop proper opts keys when calling api in code interface

---

lib/ash/code_interface.ex
test/code_interface_test.exs

Adds three new auto generated helper methods for actions in code interface.
`$input_to_$act` - `input_to_execute`, `query_to_find_by_id`, `changeset_to_create` and so on. Creates and returns corresponding input based on action type. Generic actions produce `Ash.ActionInput`, reads produce `Ash.Query` and create/update/destroy - `Ash.Changeset`.
`can_$act`/`can_$act?` - passes produced input right into `api.can`/`api.can?`. (Is not generated for generic actions as `api.can` works only with queries/changesets at the moment.) First required argument is an actor after that the same arguments as in rest of generated methods.

improvement: generate some action helpers with code interface

---

lib/ash/changeset/changeset.ex
test/changeset/changeset_test.exs

This doesn't unit tests since I couldn't find unit tests for `around_action`, `before_transaction` or `after_transaction` to use as reference.

feat: Adds Ash.Changeset around_transaction

---

lib/ash/resource/validation/present.ex
test/resource/changes/relate_actor_test.exs

Fix a typo in the at_most validation message.

fix: typo in at_most validation message

---

lib/ash/resource/validation.ex
lib/ash/resource/validation/action_is.ex
lib/ash/resource/validation/attribute_does_not_equal.ex
lib/ash/resource/validation/attribute_equals.ex
lib/ash/resource/validation/attribute_in.ex
lib/ash/resource/validation/builtins.ex
lib/ash/resource/validation/changing.ex
lib/ash/resource/validation/compare.ex
lib/ash/resource/validation/confirm.ex
lib/ash/resource/validation/function.ex
lib/ash/resource/validation/match.ex
lib/ash/resource/validation/negate.ex
lib/ash/resource/validation/one_of.ex
lib/ash/resource/validation/present.ex
lib/ash/resource/validation/string_length.ex
test/policy/field_policy_test.exs
test/resource/validation/negate_test.exs

Continue of work done in https://github.com/ash-project/ash/pull/587
> This PR adds negate validation that negates other validations. This allows to do things like negate(one_of(:attr, [:val1, :val2]).
> 
> Originally I wanted to name it not but when adding a builtin I've found that it might conflict with Kernel.not so I've renamed it to negate

Add `Negate` validation

---

lib/ash/type/uuid.ex
test/type/uuid_test.exs

This fixes `Ash.Type.cast_input/2` returning an error on certain UUIDs coming out of raw queries represented in binary/bitstrings. `String.trim/1` removes the last byte if it's less than 14, causing the cast to fail.
```elixir
Ecto.Type.cast(Ecto.UUID, <<167, 206, 201, 186, 21, 222, 76, 86, 153, 228, 194, 171, 201, 26, 34, 14>>)
#=> {:ok, "a7cec9ba-15de-4c56-99e4-c2abc91a220e"}
Ash.Type.cast_input(Ash.Type.UUID, <<167, 206, 201, 186, 21, 222, 76, 86, 153, 228, 194, 171, 201, 26, 34, 14>>)
#=> {:ok, "a7cec9ba-15de-4c56-99e4-c2abc91a220e"}
Ecto.Type.cast(Ecto.UUID, <<167, 206, 201, 186, 21, 222, 76, 86, 153, 228, 194, 171, 201, 26, 34, 13>>)
#=> {:ok, "a7cec9ba-15de-4c56-99e4-c2abc91a220d"}
Ash.Type.cast_input(Ash.Type.UUID, <<167, 206, 201, 186, 21, 222, 76, 86, 153, 228, 194, 171, 201, …
```

fix: incorrect error for casting some binary UUIDs

---

lib/ash/resource/validation/argument_equals.ex

We had an almost-identical `ArgumentEquals` validation in our codebase, and when I removed it in favour of the new built-in one, some of our tests started failing. 
Upon comparing them, I noticed this issue - it wasn't reading the actual argument, instead looking for an attribute with the same name!

fix: read argument value in `ArgumentEquals` validation

---

lib/ash/resource/calculation/argument.ex
lib/ash/resource/calculation/calculation.ex

`AshGraphql.all_attributes_and_arguments/4` was crashing for me when trying to iterate calculation arguments that default to `nil` (I was building the calculation entity dynamically).  I fixed my codebase locally, but I figured we should fix it here too.
I also fixed up the `Ash.Resource.Calculation.t` and `Ash.Resource.Calculation.Argument.t` typespecs.
The only question I have is the typespec for `Ash.Resource.Calculation`'s `calculation` field which I _think_ has been wrong for a long time.

improvement(Ash.Resource.Calculation): set struct defaults.

---

lib/ash/api/api.ex

This PR adds the api used during an action run inside the ActionInput struct.
This change was discussed in this topic in Discord: https://discord.com/channels/711271361523351632/1119369920807960726

improvement: Set api field for ActionInput when running action

---

lib/ash/actions/read.ex
lib/ash/filter/filter.ex
lib/ash/query/query.ex
test/policy/complex_test.exs

We now only apply related policies to filter statements based on references that are explicitly annotated as inputs.  This is the same logic that backs protecting access in filters for field policies.

fix(Ash.Filter): Don't overly constrain related references.

---

.formatter.exs
lib/ash/actions/update.ex
lib/ash/api/api.ex
lib/ash/changeset/changeset.ex
lib/ash/data_layer/data_layer.ex
lib/ash/data_layer/ets/ets.ex
lib/ash/error/changes/stale_record.ex
lib/ash/error/invalid/atomics_not_supported.ex
lib/ash/filter/filter.ex
lib/ash/filter/runtime.ex
lib/ash/resource/actions/update.ex
lib/ash/resource/change/atomic.ex
lib/ash/resource/change/change.ex
lib/ash/resource/dsl.ex
lib/ash/resource/validation.ex
lib/ash/type/type.ex
test/actions/update_test.exs

there is still a lot of potential work that needs to be on this front.
1. allowing changes to have an atomic and a non-atomic implementation
2. supporting atomics on create actions.
3. supporting atomics in upserts (this one may actually be much easier than the first one, for postgres specifically, due to ecto implementation details)
4. discovering places atomics can be more nicely integrated into existing changes, validations, policies

improvement: implement atomics, expression-based changes

---

.formatter.exs
lib/ash/data_layer/ets/ets.ex
lib/ash/resource/dsl.ex
lib/ash/resource/transformers/cache_primary_key.ex
lib/ash/resource/transformers/validate_action_types_supported.ex
test/resource/no_pk_test.exs

This is experimental and will likely cause breakages. It's to support time series tables.

improvement: Allow resources to opt out of the primary key requirement.

---

documentation/dsls/DSL:-Ash.Resource.cheatmd
lib/ash/resource/dsl.ex

Changes the example for `update_timestamp` to 
`update_timestamp :updated_at`
Before screenshot of the documentation:

Improve example update_timestamp docu

---

documentation/dsls/DSL:-Ash.Resource.cheatmd
lib/ash/resource/actions/read.ex
lib/ash/resource/interface.ex

In typespec of `Ash.Resource.Actions.Read` `get_by` type is `nil | [atom]` but should include a single atom too as dsl schema describes it as [`{:or, [:atom, {:list, :atom}]}`](https://github.com/vonagam/ash/blob/e3c086e87150e172a359a17e69e52b7d63378ecd/lib/ash/resource/actions/read.ex#L70).
In schema for `Ash.Resource.Interface` `get_by` is `{:list, :atom}` but should be `{:or, [:atom, {:list, :atom}]}` (like in the action) - there is a [`List.wrap`](https://github.com/ash-project/ash/blob/c8e796fbcbb100e5c6a65161fbb5d35b1881659e/lib/ash/code_interface.ex#L387) call to support that.

fix: `get_by` option can accept a single atom

---

documentation/dsls/DSL:-Ash.Flow.cheatmd
documentation/dsls/DSL:-Ash.Resource.cheatmd
lib/ash/flow/step/transaction.ex
lib/ash/flow/step/validate.ex
lib/ash/resource/validation.ex

Saw three places where `:wrap_list` can be used. 
So instead of:
```elixir
{:or, [Ash.OptionsHelpers.ash_resource(), {:list, Ash.OptionsHelpers.ash_resource()}]}
{:or, [@validation_type, {:list, @validation_type}]}
{:list, {:or, [:atom, {:list, :atom}]}}
```
It will be:
```elixir
{:wrap_list, Ash.OptionsHelpers.ash_resource()}
{:wrap_list, @validation_type}
{:list, {:wrap_list, :atom}}
```

fix: use `:wrap_list` type where appropriate

---

lib/ash/resource/transformers/belongs_to_attribute.ex

In dsl default value for belongs to `attribute_type` was changed from `:uuid` to [`Application.compile_env(:ash, :default_belongs_to_type, :uuid)`](https://github.com/ash-project/ash/blob/05b9ac1f866d2470efacdc41fd957a3e7278ccd2/lib/ash/resource/relationships/belongs_to.ex#L91). But in `Ash.Resource.Transformers.BelongsToAttribute` it is still `relationship.attribute_type || :uuid`. Replaced `|| :uuid` with `:default_belongs_to_type` env fallback.

fix: add missing usage of `:default_belongs_to_type`

---

documentation/dsls/DSL:-Ash.Notifier.PubSub.cheatmd
documentation/dsls/DSL:-Ash.Resource.cheatmd
lib/ash/notifier/pub_sub/publication.ex
lib/ash/resource/aggregate/aggregate.ex
lib/ash/resource/change/change.ex
lib/ash/resource/identity.ex
lib/ash/resource/validation.ex
lib/ash/resource/validation/present.ex

Saw that type for `keys` in `identity` was document as `any`. Thought why wouldn't it show `atom | list(atom)`? Found out that there are custom type validations that just do what `:wrap_list` handles. Replaced them.
In one case of `Ash.Notifier.PubSub.Publication.topic` there was even a small bug - it would allow a single string or a list of string/atoms, but not a single atom.
Note: `{:wrap_list, x}` produces type documentation `list(x) | x`. Personally I would find it more conventional for it to be `x | list(x)` instead - from simpler to more complex.

fix: more usages of `:wrap_list` type

---

documentation/dsls/DSL:-Ash.Notifier.PubSub.cheatmd
lib/ash/notifier/pub_sub/publication.ex
lib/ash/resource/validation.ex

Revert one of the changes in #700. I've missed that the custom function supports recursion.
Also in that PR I've made remark that with custom function `topic` supports `"string"` or `["string"]` or `[:atom]` but not `:atom`. I've kept it like it was before, I assume this is because atoms represent changing parts and it is not advisable for topic to consist only of an attribute value. Though there is a potential `prefix`, so maybe single atom is ok.
Also on topic of `:wrap_list` removed `List.wrap` call `Ash.Resource.Validation` that is not needed anymore because `:wrap_list` does that now.

fix: revert `:wrap_list` usage for `topic` in PubSub, needs recursion

---

lib/ash/resource/transformers/get_by_read_actions.ex

`get_by` transform should happen after `belongs_to` attributes are generated.
Closes #637.

fix: usage of `get_by` with `belongs_to` attribute

---

lib/ash/type/type.ex
lib/ash/type/union.ex

After the change you made to fix the permissions when loading through unions, I got another error.
This might not be the right place to fix this issue, but it got rid of the error.
What happened was that I tried to execute an update on a resource, and the resource I put in had a %Ash.ForbiddenField{} struct in place for the union. Ash then tried to go through the load function and failed
because the Enum function couldn't handle the %Ash.ForbiddenField{} value. 
This is not actually fixing this, but because I didn't need to load anything from the union in this action, the load was empty, and I could circumvent the problem like this.

fix: return unions as is if load is empty

---

lib/ash/type/float.ex

Seems like `Type.Float` was copied from `Type.Decimal` but the types were left as is from decimal. Unless I am missing something it should not work as there is no `decimal` method in `Type.Float`.

fix: fix types for `min`/`max` constraints in `Type.Float`

---

documentation/dsls/DSL:-Ash.Resource.cheatmd
lib/ash/resource/dsl.ex
lib/ash/resource/relationships/many_to_many.ex
lib/ash/resource/transformers/many_to_many_destination_attribute_on_join_resource.ex
lib/ash/resource/transformers/many_to_many_source_attribute_on_join_resource.ex
test/resource/relationships/many_to_many_test.exs

Many to many relationship `source_attribute_on_join_resource` and `destination_attribute_on_join_resource` are now guessed by there module name if not explicitly set in the relationship.
Solve issue #245.

improvement: set default many to many options

---

lib/ash.ex
lib/ash/api/api.ex
lib/ash/api/functions.ex
lib/ash/api/global_interface.ex
lib/ash/resource.ex
lib/ash/resource/dsl.ex
lib/ash/resource/info.ex
lib/ash/resource/transformers/set_define_for.ex
lib/ash/resource/verifiers/verify_accepted_by_api.ex
test/api/api_test.exs

improvement: add functions to `Ash` for resources w/ configured apis
improvement: default code_interface.define_for to resource's ash api
So what does this give us?
```elixir
defmodule Resource do
use Ash.Resource,
api: YourApi
end
```
Given that resource, you can then use the functions defined in `Ash` that mirror the functions defined in the api module,
```elixir
Resource
|> Ash.Changeset.for_create()
|> Ash.create!()
```
Additionally, options like `code_interface.define_for` default to the value of that api, allowing you to omit them.

improvement: support an `api` option to `use Ash.Resource`

---

lib/ash/resource/change/builtins.ex

I just noticed that the indentation for the code examples were not properly set.

Format code examples in `Ash.Resource.Change.Builtins.set_attribute/3`

---

lib/ash/code_interface.ex
test/code_interface_test.exs

Issue was that there was an unclear error message when passing a list (or other type) to a code interface action function (e.g. update).
This is to close out https://github.com/ash-project/ash/issues/679
I first added a unit test to verify the fix worked (retroactively modifying the caught error message in the unit test once I determined what it was). For the unit test I added an `update` action to the User resource in `code_interface_test` and passed in an empty list to the `User.update` code interface action.
The fix was relatively simple: removing the pattern matching in the code_interface switch action block resulted in a clearer error message.

2023 ww41 srcrr 679 code gen interfaces check type first argument

---

lib/mix/tasks/generate_livebook.ex

Solves #739
The documentation of the mix task mentioned the `--only` command line option, but this options doesn't seem to exist so I've removed it from the documentation for now.

improvement: add "filename" parameter to the livebook generator.

---

lib/ash/api/info/livebook.ex
test/api/livebook_test.exs

Solves #740 
I've added a root H1 to the generated livebook and moved all section headings by one level.

fix: Change heading levels in generated livebook to have only one H1

---

config/config.exs
lib/ash/action_input.ex
lib/ash/flags.ex
test/actions/generic_actions_test.exs
test/test_helper.exs

Solves #725 
When encountering unknown arguments, unknown keys are added to the `invalid_keys` set and an `Ash.Error.Action.InvalidArgument` with a custom message is added to the ActionInput.
Running the action will then return an `Ash.Error.Invalid` error.

feat: Add unknown argument error when passing an unknown key to an action.

---

.gitpod.yml
lib/ash/type/union.ex
test/type/union_test.exs

This fixes an issue that I ran into while writing edge case tests for ash_paper_trail's full diff feature.  Updating a union value to a native type (:string) error will error when calling `prepare_change` and `handle_change`.
```
** (UndefinedFunctionError) function :string.prepare_change/3 is undefined or private
code: ctx.resource.update!(res, %{
stacktrace:
(stdlib 5.1.1) :string.prepare_change(nil, "https://www.just-a-link.com", [])
(ash 2.15.8) lib/ash/type/union.ex:589: Ash.Type.Union.do_prepare_change/4
(ash 2.15.8) lib/ash/changeset/changeset.ex:3433: Ash.Changeset.change_attribute/3
(stdlib 5.1.1) maps.erl:416: :maps.fold_1/4
(ash 2.15.8) lib/ash/changeset/changeset.ex:913: Ash.Changeset.prepare_changeset_for_action/4
(ash 2.15.8) lib/ash/changeset/changeset.ex:875: …
```

fix: native union changes

---

lib/ash/type/union.ex
test/type/union_test.exs

In my previous PR, I missed a few instances of calling `type.handle_change`.   After implementing fixes, I followed the pattern of `do_prepare_change` and DRY'd up the various scenarios.

fix more handle change use cases

---

lib/ash/resource/preparation/preparation.ex

It mentioned changeset and change instead of query and preparation

docs: fix Ash.Resource.Preparation moduledoc

---

documentation/dsls/DSL:-Ash.Resource.cheatmd
lib/ash/api/api.ex
lib/ash/changeset/changeset.ex
lib/ash/data_layer/data_layer.ex
lib/ash/data_layer/ets/ets.ex
lib/ash/resource/actions/create.ex
test/actions/bulk/bulk_create_test.exs
test/resource/upsert_test.exs

With this change, upsert_fields accepts the following options:
* `nil`: upsert fields not set;
* `:replace_all`: all fields from resource will be updated;
* `{:replace_all_except, [fields]}`: all fields from resource except fields inside `fields` will be updated;
* `{:replace, [fields]}`: only fields inside `fields` will be updated.
- [] Features include unit/acceptance tests

feat: Expand upsert_fields option

---

lib/ash/actions/managed_relationships.ex
test/actions/has_many_test.exs

It was mentioned on Discord that the returned record still contained the destroyed related resource. This should ensure the resource is removed from the related data if the resource is destroyed or unrelated. 
https://discordapp.com/channels/711271361523351632/711271361523351636/1171422824129380403

fix: remove destroyed or unrelated data from the relationship

---

lib/ash/policy/check/relates_to_actor_via.ex
test/policy/relates_to_actor_via_test.exs

This is necessary so that the name can be used for the error message, should the relationship resolve to nil.

fix: separated the relationship's name from its resolution 

---

lib/ash/actions/create/bulk.ex
lib/ash/changeset/changeset.ex
lib/ash/data_layer/ets/ets.ex

This should fix the issue I mentiond in https://github.com/ash-project/ash_postgres/pull/179
I reverted the change in set_on_upsert introduced in https://github.com/ash-project/ash/pull/761, which is used inside the ets data_layer but wasn't used in ash_postgres. I extracted the expansion of the options into its own function and ran the options/action settings through it before it was passed to the data layers.
There are already tests that check the behaviour, but they all used the ets data_layer that handled the upsert logic using the before-mentioned function. The tests still work but now they should also work if a different data_layer is used.

fix: convert upsert fields before passing to data layer

---

lib/ash/type/enum.ex

I was struggling for a bit with using Enums for a reason that now seems trivial, so I wanted to clarify the documentation in case anyone else would find this non-intuitive. This PR just changes the documentation to include an example of Enum usage:
```elixir
attribute :status, MyApp.TicketStatus
```
(I was originally trying to just run `attribute :status, :atom, constraints: [one_of: MyApp.TicketStatus]` instead.)

Clarify how to use Enums in attributes

---

documentation/how_to/auto-format-code.md
documentation/tutorials/get-started.md

After getting tripped up on this several times, I figured it was worthy of its own guide! (I always forget to add the formatter config)
I figure other Ash library documentation can be updated to point to this guide, to be the source of truth for how to auto-format stuff.

docs: Remove formatting note from Getting Started guide in favour of giving it its own guide

---

documentation/topics/relationships.md

With the current documentation, it's unclear how to set up a cross-API `many_to_many` relationship if the join resource is in the source API but the destination resource is in a different API (the current example only works for when both of them are in the destination API). I added an example connecting Organizations and Users with guidance on how to set up the additional `has_many` association. The current error message was helpful in helping me realize how to do it, but it still took me a little while to nail everything.
In addition, I added a `postgres` and `actions` block to the example of a join resource, as currently the documentation doesn't list them but shows the full module code, which to me implied they weren't necessary. The error I faced because I left them out wasn't quite …

Add a cross-API many-to-many example to the documentation

---

test/resource/validation/embedded_resource_test.exs

I'm not sure this is an ideal testing strategy but it reproduces the issue.  
In short, I'm using embedded resources as arguments and attributes on resources. When the validations and changes run for the embedded resources, I need to be able to access the tenant, actor and authorize? values to query the data layer.

Embedded resource changesets should have access to the tenant, actor, and authorize? values

---

lib/mix/tasks/generate_policy_chart.ex

This is the one-liner that is shown when running `mix help` to list tasks
Currently it looks like:

docs: Fill out shortdoc for `generate_policy_charts` mix task

---

lib/ash/error/exception.ex
lib/ash/type/keyword.ex
lib/ash/type/map.ex
test/calculations/calculation_test.exs
test/type/keyword_test.exs
test/type/map_test.exs

This PR resolves #820 – I think I found and fixed this in all places it was occurring.
During the course of this work, I [discovered](https://github.com/ash-project/ash/compare/main...ahey:error-vars?expand=1#diff-32cc05145e05358ce83d202848ab062c4748ca83784a0f6a7e1854f5aac02594R151) and fixed another issue ([here](https://github.com/ash-project/ash/compare/main...ahey:error-vars?expand=1#diff-5c6d681025e312c3caa3d2600b733fa250caa0878be36aa94a6f49b5aeeaa078R157) and [here](https://github.com/ash-project/ash/compare/main...ahey:error-vars?expand=1#diff-9b75dd399fae543dfa8cd09e97e8e6c11a969c91aa1f7d83b85631ff0cc52670R178)) where `vars` was missing a keyword to be interpolated into the error string.
A few tests were incorrectly expecting the superflouous keywords to be included in vars. These …

fix: only put keywords to be interpolated in message in error vars

---

documentation/dsls/DSL:-Ash.Resource.md
lib/ash/resource/dsl.ex

The `Ash.Resource.Info.put_metadata` => `Ash.Resource.put_metadata`, and noting that you'll most likely want to set metadata in a change `after_action` hook when the result is present.

Misc metadata doc improvement

---

documentation/topics/pagination.md
lib/ash/api/api.ex
test/actions/pagination_test.exs

This will re-run the same query that was used to fetch the given page, updating the data in it
I was hoping there would be some tests for the existing options that I could copy and modify, but there were not :( I manually tested it with both offset and keyset pagination, and they both behaved as expected.
When viewing a page of data in a web browser, and then deleting a record on it, reloading the page (data page, not web page) will correctly shift the data up/down to fill the gap.

feat: Allow `:self` as an option when requesting a relative page from a given page

---

lib/ash/actions/read/read.ex

Add the pagination info to the context again, like in the old implementation:
* https://github.com/ash-project/ash/blob/ff1a590f46e750422920b4dc200fc6d3329b420c/lib/ash/actions/read.ex#L386
*  https://github.com/ash-project/ash/blob/ff1a590f46e750422920b4dc200fc6d3329b420c/lib/ash/actions/read.ex#L498
I don't know if this is right in the new implementation, especially the call to add_page and passing the values there.
I do not understand the code completely at the moment, to be honest ;)  I'm a bit confused about the context values only being used for add_page and not the pagination itself, but that was already the case in the old implementation.
I need to familiarise myself with the code a bit more in the future.

fix: add page opts to context again

---

lib/ash/policy/authorizer/authorizer.ex

I had a test in my project error out because the pagination added the `id` as a filter `id > last_entry_from_last_page_id` and primary keys do not have field policies if I'm not mistaken.

fix: do not check primary key fields in filter

---

lib/ash/actions/read/calculations.ex
lib/ash/query/query.ex

This gets rid of the exeption in my test. The behaviour is still a bit different as the calculation is now returning back `nil` instead of `[]` as before

fix: load fails because of empty list instead of query

---

lib/ash/resource/change/relate_actor.ex
test/resource/changes/relate_actor_test.exs

Fixes:
- `opts[:field]` was used where `opts[:relationship]` is supposed to.
- actor was not get by `opts[:field]`, added `actor_or_field` call to use field if specified.
Note: I see that there is a check for case of actor being nil. But this check does not cover a case where `opts[:field]` is specified. In that case an `actor` can be an empty map, so actual actor is still nil and it slips past the check.

fix: use correct option for relationship in atomic `relate_actor`

---

lib/ash/type/float.ex

Update Ash.Type.Float to accommodate `constraints/0` instead of `constraints/1`

Update Ash.Type.Float to accommodate constraints/0

---

documentation/topics/validations.md

Save others a few minutes of confusion when they copy the example and it eventually bombs out when used by a custom action

Add 'use Ash.Resource.Validation' to Custom Validation example

---

lib/ash/actions/managed_relationships.ex
lib/ash/changeset/changeset.ex
lib/ash/changeset/managed_relationship_helpers.ex

Idea is to allow this for many to many:
```elixir
[
on_match: :update,
on_lookup: :relate,
on_no_match: :create,
join_keys: [:some, :key],
]
```
With the same meaning as this:
```elixir
[
on_match: {:update, :update, :update, [:some, :key]},
on_lookup: {:relate, :create, :read, [:some, :key]},
on_no_match: {:create, :create, :create, [:some, :key]},
]
```
Additional things:
- Cleaned up `ManagedRelationshipHelpers.sanitize_opts` - made variable names and white space usage consistent. Added a missing case for `on_no_match: {:create, create, join_create}` and removed one redundant case in `on_lookup`. In  `:on_lookup` `primary_action_name` method was used to get an action name unlike other ones which were using `Ash.Resource.Info.primary_action!`. The difference is that the latter is …

improvement: add `join_keys` option to `manage_relationship`

---

lib/ash/actions/managed_relationships.ex

Right now when managed create for many to many relationship is happening the name in `accessing_from` is for a through relationship. 
Example: 
Resources `Post`, `Tag` and `PostTag`. In `Tag` we add such policy:
```elixir
policies do
policy action_type(:create) do
authorize_if accessing_from(Post, :tags)
end
end
```
This will not work because actual name in `accessing_from` context will be `tags_join_assoc` (if the through name is generated automatically).

fix: set right `accessing_from` name in many to many managed create

---

lib/ash/registry/extensions/resource_validations/verifiers/validate_related_resource_inclusion.ex

Continues  #870.
Saw the PR - looked if `join_relationship_name` is mentioned anywhere else and the exact same thing was in another place.

chore: continue update validate_related_resource_inclusion.ex

---

lib/ash/actions/managed_relationships.ex
lib/ash/changeset/changeset.ex
lib/ash/changeset/managed_relationship_helpers.ex
test/changeset/changeset_test.exs

Support for updating only join resource in `manage_relationship` without updating destination one in many to many.
Can be specified as `:update_join`, `{:update_join, :action_name}` or `{:update_join, :action_name, [:join, :param]}`.
Under the hood it just gets transformed into `{:update, nil, :action_name, [:join, :param]}`. So the PR adds such alias and checks if an update action for destination is nil or not before doing it.
I will need to add it to documentation and ideally a test. But first want to confirm that such implementation is acceptable. Because it adds support for `{:update, nil}` (for many to many only, as an alternative way to do the same thing) but that's the least disrupting way to add the feature. The code is simple.
Note: saw [a wrong …

improvement: add `on_match: :update_join` to `manage_relationship`

---

documentation/dsls/DSL:-Ash.Resource.md
lib/ash/resource/dsl.ex

In my testing, arguments to a manual action are part of the `arguments` in the input to the `run` function - which is the action struct itself.

docs: Correct example used for manual actions

---

lib/ash/filter/filter.ex

Nothing important. At that point in code `args` is guaranteed to be a tuple. And only one tuple format is valid for calculation in a filter: `{args, statement}`.

fix: remove unneeded code for calculations in a filter

---

lib/ash/filter/filter.ex

Saw a warning about incompatible types about changes in my previous PR - #891:
```
warning: incompatible types:
tuple() !~ {var1, var2}
in expression:
{args, nested_statement} = args
hint: use pattern matching or "is_tuple(args) and tuple_size(args) == 2" to guard a sized tuple.
```
Added a guard to address the warning.

fix: handle warning about incompatible types

---

lib/ash/actions/read/read.ex
lib/ash/api/api.ex
lib/ash/changeset/changeset.ex
lib/ash/data_layer/ets/ets.ex
lib/ash/embeddable_type.ex
lib/ash/engine/request.ex
lib/ash/filter/filter.ex
lib/ash/filter/runtime.ex
lib/ash/query/boolean_expression.ex
lib/ash/query/query.ex
lib/ash/type/type.ex

Seems formatter does not enforce a single style in that case and allows to write both:
```elixir
with a <- b do
end
```
and:
```elixir
with a <-
b do
end
```
Saw a second variant where first one makes more sense (especially if it does not match neighbors). But I assume that some of changed lines might be a deliberate stylistic choice though.

chore: format some `with` clauses to be on a single line

---

test/flow/tenant_test.exs

When run
```
mix test test/flow/tenant_test.exs
```
From `GetPost.run/3`
```
opts = context |> Ash.context_to_opts() |> IO.inspect()
```
outputs
```
[authorize?: false, actor: nil]
```
and there's no tenant.

Reproduce flow custom step has no tenant in context

---

test/flow/run_flow_test.exs

To reproduce, run
```
mix test test/flow/run_flow_test.exs
```
ValidateNoEmptySteps raises "Must have at least one step." when map or branch has only run_flow during compile.
```elixir
steps do
map :create_two_posts, range(1, 2) do
run_flow :create_post, CreatePost do
input %{}
end
end
end
```

Reproduce run_flow is not counted as a step inside map, branch

---

lib/ash/actions/destroy/bulk.ex
lib/ash/actions/destroy/destroy.ex
lib/ash/actions/update/bulk.ex
lib/ash/actions/update/update.ex
lib/ash/query/query.ex

`for_read` opts were provided as a third argument, meaning they were treated as an input arguments instead and ignored (unless somebody had arguments with same names).
In non-bulk destroy there was a propagation of context from a changeset to a query through `Ash.Query.set_context(changeset.context)` but in other three places there wasn't. Meaning that important context like table for polymorphic relationships was missing.
Reordered some lines to be in the same order.

fix: correct `for_read` calls in update and destroy actions

---

lib/ash/resource/dsl.ex

Just a one line correction. `integer_primary_key` does set `generated?: true` but `uuid_primary_key` does not.

docs: `uuid_primary_key` does not have `generated?: true` by default

---

lib/ash/resource/transformers/set_define_for.ex

There is no need to do `Spark.Dsl.Transformer.persist(dsl, :api, api)` since `api` comes from `Spark.Dsl.Transformer.get_persisted(dsl, :api)`.

chore: remove unneeded `persist` call

---

lib/ash/resource/change/change.ex

Fixes documentation a little and changes `list` to `wrap_list` for `where` (`validation` already uses `wrap_list` for `where`).

improvement: use `wrap_list` for `where` in `changes.change`

---

lib/ash/resource/transformers/create_join_relationship.ex

If existing `join_relationship` is provided for `many_to_many` then `source_attribute` should be copied from the join relationship into many-to-many. Just like join `destination_attribute` gets transferred as `source_attribute_on_join_resource`.

fix: set `source_attribute` from `join_relationship` in `many_to_many`

---

lib/ash/plug_helpers.ex

`Ash.PlugHelpers` context function specs were mistakenly using `Ash.Resource.record()` types instead of `map()`

fix: update set/get/update_context function specs to use maps

---

lib/ash/type/vector.ex
lib/ash/vector.ex
test/type/vector_test.exs

I'm trying to store embeddings as `pgvector` data in Postgres as follows (simplified):
```elixir
defmodule MyApp.Context.Chunk do
use Ash.Resource,
data_layer: AshPostgres.DataLayer
@embedding_size 384
attributes do
uuid_primary_key :id
attribute :embedding, :vector
end
postgres do
table "chunks"
repo MyApp.Repo
migration_types embedding: {:vector, @embedding_size}
end
end
```
I have the following test:
```elixir
defmodule MyApp.Context.ChunkTest do
use MyApp.DataCase, async: true
test "can store embedding as vector" do
embedding = 1..384 |> Enum.to_list()
assert {:ok, chunk} = MyApp.Context.Chunk.create!(%{embedding: embedding})
end
end
```
Which fails with the following error:
```
** (Postgrex.Error) ERROR 22000 (data_exception) expected 384 dimensions, not 1540
```
I suspect somehow …

fix: don't double-encode vector data

---

lib/ash/policy/check.ex
lib/ash/policy/check/built_in_checks.ex
lib/ash/policy/check/matches.ex
lib/ash/policy/filter_check_with_context.ex
lib/ash/policy/simple_check.ex
test/policy/simple_test.exs
test/support/policy_simple/resources/tweet.ex

Adds `matches` built-in check for making simple checks using functions without need to define a separate module for that.
Example from the test (where `bar` is required argument):
```elixir
policy action(:create_bar) do
authorize_if matches("bar is even", fn _actor, context ->
rem(context.changeset.arguments.bar, 2) == 0
end)
end
```
Also included some typespec corrections - unless I'm mistaken `actor` is not required to be a struct (even though it is most likely is) and also can be nil.

improvement: add `matches` built-in policy check

---

lib/ash/actions/update/bulk.ex
test/actions/bulk/bulk_update_test.exs

I'm trying to use bulk updates to generate text embeddings for an Ash resource in batches using an `Nx.Serving`:
```elixir
@impl Ash.Resource.Change
def batch_change(changesets, _opts, _context) do
Logger.info("Generating embeddings for #{length(changesets)} chunks ...")
texts = Enum.map(changesets, &Changeset.get_attribute(&1, :text))
embeddings = generate_embeddings(texts)
changesets
|> Enum.zip(embeddings)
|> Enum.map(&change_embedding/1)
end
```
When running this code I noticed the following issues:
- `batch_change/3` was never called, because Ash checks for `batch_change/4` (callback is defined as `batch_change/3`): https://github.com/ash-project/ash/blob/c04b638136f464b659a0c1d4dfe5bce91f25e561/lib/ash/actions/update/bulk.ex#L2035
- The `:batch_size` option is ignored (unless using …

Fix bulk updates

---

lib/ash/type/enum.ex
test/type/enum_test.exs

As discussed in https://github.com/ash-project/ash_graphql/issues/116, this allows extensions to use the description to use the provided descriptions.
The documentation assumes that if a user provides a description, it does so for all values (since this seems to be a reasonable assumption and allows the nicer keyword list syntax). However tests also cover an enum with some missing descriptions.

feat: allow providing descriptions to Ash.Type.Enum values

---

lib/ash/policy/check.ex

Type that `strict_check` is [allowed to return](https://github.com/ash-project/ash/blob/0afb9ade26ba540e61fa9db27f4f5bb77bce1071/lib/ash/policy/policy.ex#L190) `{:error, error}` tuple.

fix: show that `Policy.Check.strict_check` can return an error tuple

---

lib/ash/api/api.ex
lib/ash/api/functions.ex
lib/ash/api/global_interface.ex
lib/ash/api/interface.ex

- `reload!` was not exposed on `Ash`, only `reload` was.
- `reload` was marked as not having `opts` while it does.

fix: corrections for `reload`/`reload!`

---

lib/ash/actions/create/create.ex
lib/ash/actions/destroy/destroy.ex
lib/ash/actions/helpers.ex
lib/ash/actions/read/read.ex
lib/ash/actions/update/bulk.ex
lib/ash/actions/update/update.ex
lib/ash/api/api.ex

`load` option was supported in read and bulk actions. Now it is applicable to usual create/update/destroy actions too.
Noting that create/update/soft-destroy and non-soft destroy handle loads different.
Small changes besides that - consistent usage of `Helpers` alias, remove double call to `add_process_context` in destroy action, remove empty `@create_update_opts_schema`.

improvement: support `load` option for create/update/destroy

---

lib/ash/actions/create/bulk.ex
lib/ash/actions/destroy/bulk.ex
lib/ash/actions/update/bulk.ex

There were two identical contexts on the same level in nesting. Both were missing tenants. Then in some PR definition for one of contexts was moved up and added tenant. So by removing second context a tenant also gets passed properly there.

fix: fix missing tenant in some bulk contexts

---

lib/ash/actions/aggregate.ex
lib/ash/actions/read/read.ex
test/actions/multitenancy_test.exs

The multitenancy attribute was already considered as a filter in aggregates, but the presence of the tenant was not enforced

fix: enforce multitenancy on aggregates

---

lib/ash/api/interface.ex
test/actions/aggregate_test.exs

split_aggregate_opts/1 was called too early so it didn't handle the translation of :read_action to :action, leading to a NimbleOptions error during validation

fix: make bang variant of field aggregates work correctly

---

lib/ash/policy/simple_check.ex

Allows simple check to return `{:error, error}` or explicit `{:ok, boolean}` in addition to simply returning a boolean.
Had to silence dialyzer because it is used in macro, so when it is used it knows what `match?` specifically returns in a module and complains about never matching pattern.
This is PR to main. Ash 2 lives on a separate branch now. If this is merged in, what do I need to do to add it to second version too (the code and change is the same in this case)?

improvement: allow simple check to return error tuple

---

documentation/tutorials/get-started.md

----
Hi,
I wanted to try Ash Framework and I have followed the "Get Started" guide with Ash `3.0.0-rc.3`.
I got some errors and warnings, but with the changes from the PR, it should work with no errors and fewer warnings.
There is still 1 warning left in this PR, but I don't know how to remove it:
```
warning: the Inspect protocol has already been consolidated, an implementation for Helpdesk.Support.Representative has no effect. If you want to implement protocols after compilation or during tests, check the "Consolidation" section in the Protocol module documentation
│
1 │ defmodule Helpdesk.Support.Representative do
│ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
│
└─ lib/helpdesk/support/representative.ex:1: Helpdesk.Support.Representative (module)
```

docs: Adjust guide to suppress errors and warnings for v3.0

---

lib/ash/actions/read/calculations.ex
lib/ash/actions/read/read.ex
lib/ash/query/query.ex
test/calculations/calculation_test.exs

Small breaking change: aligns position of `type` in `Ash.Query.calculate` with position in `calculation` dsl entity and with `Ash.Query.aggregate`. Also should help with formatting when `module_and_opts` supports anonymous functions.

improvement: change `type` argument position in `Ash.Query.calculate`

---

lib/ash/query/aggregate.ex
lib/ash/query/calculation.ex

In `Ash.Query.Aggregate` and `Ash.Query.Calculation` options included `sensitive?` but it was not used (also one had wrong default value, other had no default value). Now it is handled.
Also in calculation there was `sortable?: opts[:filterable?]`.

fix: handle `sensitive?` option in query aggregate/calculation

---

documentation/how_to/upgrade.md

Mention the fact that resources do not implement `Ash.Type` anymore

docs: add a section to the 3.0 Upgrade guide

---

documentation/how_to/upgrade.md

Closes #970 
Moves announcement of `API -> Domain` change to the top of the changes list. This way all other domain changes will not be confusing/surprising. The rest of the doc is unchanged

move API -> Domain change to the top of upgrade doc

---

documentation/dsls/DSL:-Ash.Reactor.md
lib/ash/reactor/dsl/action.ex
lib/ash/reactor/dsl/actor.ex
lib/ash/reactor/dsl/create.ex
lib/ash/reactor/dsl/destroy.ex
lib/ash/reactor/dsl/inputs.ex
lib/ash/reactor/dsl/tenant.ex
lib/ash/reactor/dsl/transaction.ex
lib/ash/reactor/dsl/update.ex

fix: multi-line DSL doc options in `Ash.Reactor`.

---

lib/ash/actions/aggregate.ex
test/actions/aggregate_test.exs

Avoid making callers like Ash.aggregate crash with a WithClause error since they expect an :ok/:error tuple

fix: return {:error, query} for invalid query in Aggregate.run/4

---

lib/ash/changeset/changeset.ex
lib/ash/resource/validation/match.ex
test/resource/validation/match.ex

improvement: make Ash.Resource.Validation.Match partially atomic

---

lib/ash/resource/change/builtins.ex
lib/ash/resource/preparation/builtins.ex
lib/ash/resource/validation/builtins.ex

All examples should be indented by four spaces. (Also added a missing close quote)
Before: https://hexdocs.pm/ash/Ash.Resource.Preparation.Builtins.html#after_action/1
After:

docs: Fix formatting of examples for `Ash.Resource.Preparation.Builtins`

---

lib/ash/code_interface.ex
test/code_interface_test.exs

In Ash 3 code interface started to automatically add an argument for primary key to methods with `get?: true`. 
Seems like it was unintended consequence of refactoring `if` to `case` statement.
This PR undoes this change. To get things by id one can use `get_by: :id`.

fix: undo adding primary key argument for methods with `get?`

---

documentation/dsls/DSL:-Ash.Resource.md
documentation/topics/advanced/reactor.md
lib/ash/actions/action.ex
lib/ash/resource/actions/action/action.ex
lib/ash/resource/dsl.ex
lib/ash/resource/verifiers/verify_generic_action_reactor_inputs.ex
test/actions/generic_actions_test.exs

- Extends the generic action runner to detect when the `run` module is a Reactor and automatically executes it in the correct way.
- Adds a verifier that detects said actions and ensures that action arguments are present for all expected inputs.

improvement: Allow Reactor modules to be run directly from generic actions

---

lib/ash/resource/info.ex
test/resource/info_test.exs

The function was missing a base case causing it to always return nil when trying to get relationships by path.

Fix Ash.Resource.Info.public_relationship/2

---

lib/ash/reactor/builders/transaction.ex
lib/ash/reactor/builders/utils.ex
lib/ash/reactor/notifications.ex
test/reactor/notifications_test.exs
test/reactor/reactor_test.exs
test/reactor/transaction_test.exs

Thanks to @carlgleisner for the [detailed reproduction](https://github.com/carlgleisner/reactor_notification_worker_issue).
The problem was caused by an attempt to not have nested reactors indepdently publish their notifications separate to the parents but contained a logic flaw which caused the agent to not start, but only the first time you try and use a given reactor.
The fix involves _always_ starting a notification agent for each reactor, but nesting them.  When a reactor completes it either publishes it's notifications to the parent reactor or to ash if there are no parent reactors.

fix(Ash.Reactor): crash when calling an ash reactor for the first time.

---

lib/ash/api/api.ex
lib/ash/api/interface.ex
test/policy/rbac_test.exs
test/support/policy_rbac/resources/file.ex

Was refactoring app to leverage the policies `can?` fn like:
```elixir
Hello.World.can?({thing, :update}, actor)
```
Code worked fine, but Dialyzer yelled at me with
```
The function call will not succeed.
Hello.World.can?(
{%Hello.World.Thing{_ => _},
:update},
_actor :: any()
)
will never return since the 1st arguments differ
from the success typing arguments:
(
{atom(), atom()}
| %{
:__struct__ => Ash.Changeset | Ash.Query,
:__validated_for_action__ => atom(),
:action =>
nil
| %{
:__struct__ =>
Ash.Resource.Actions.Action
| Ash.Resource.Actions.Create
| Ash.Resource.Actions.Destroy
| Ash.Resource.Actions.Read
| Ash.Resource.Actions.Update,
:arguments => [map()],
:description => nil | binary(),
:name => atom(),
:primary? => boolean(),
:touches_resources => [atom()],
:transaction? => _, …
```

fix(types): Missing types on spec for can/can? functions

---

lib/ash/changeset/changeset.ex
lib/ash/data_layer/data_layer.ex
lib/ash/to_tenant.ex

This is technically a breaking change, but without this the protocol would never work as intended since the funtion gets dispatched based on the type of the first parameter and the resource parameter will always be an atom (precisely, an alias) so the implementation for Atom will always be called
I'll add regression tests in another PR where I call the protocol in actions, I've wanted to leave this separate to highlight the need for a breaking change

fix: swap the parameters in Ash.ToTenant.to_tenant/2

---

lib/ash/resource/validation/compare.ex
test/resource/validation/compare_test.exs

The previous `reduce` loop did not break on the first failure and return the error, it returned the last iteration of the loop
❗ ❗ Some more work may need to be done on the atomic side of the validation, I'm not familiar with how they work!
Without the code change, the new test fails:
```
1) test validate against a range of values (Ash.Test.Resource.Validation.CompareTest)
test/resource/validation/compare_test.exs:139
match (=) failed
code:  assert {:error, %{message: message, vars: vars}} = Compare.validate(changeset, opts, %{})
left:  {:error, %{message: message, vars: vars}}
right: :ok
stacktrace:
test/resource/validation/compare_test.exs:157: Ash.Test.Resource.Validation.CompareTest.assert_error/3
test/resource/validation/compare_test.exs:145: (test)
```
Because -1 passes the last …

fix: Validate all conditions in a `numericality` validation instead of only the last

---

documentation/topics/reference/glossary.md

The `<>` around the link generated a URL like `https://hexdocs.pm/ash/3.0.0-rc.18/%3Chttps://en.wikipedia.org/wiki/Domain_(software_engineering)%3E` (oops)

docs: Reorder Glossary sections alphabetically and fix link to domain wiki page

---

lib/ash/changeset/changeset.ex
test/actions/bulk/bulk_destroy_test.exs

In trying to implement bulk actions, we encountered an issue where the `action_type` on a `bulk_delete` was being set as `:update`. We have an after action that depends on the `action_type` being correct. This MR attempts to ensure that the `action_type` is set correctly.

Properly set action_type when preparing changesets

---

lib/ash.ex
lib/ash/changeset/changeset.ex
lib/ash/code_interface.ex
test/code_interface_test.exs

- Actions generated by for the code interface did not accept the `@context` option and returned an error/exception.
- We seem to have spotted a bug in `bulk create` (see change `lib/ash/code_interface.ex#702`)
- Ready for review for Ash 3.0 code base
- Ash 2.0 https://github.com/ash-project/ash/pull/1017
- Many thanks to @barnabasJ for supporting me while digging into this 🤝

fix: `code_interface` actions accept `@context`

---

lib/ash/type/enum.ex
test/type/enum_test.exs

Allow handling additional inputs to map them to one of the enum values

feat: make `match/1` overridable in Ash.Type.Enum

---

lib/ash/actions/create/bulk.ex
lib/ash/actions/create/create.ex
lib/ash/actions/read/read.ex
lib/ash/actions/update/update.ex

Improvement over 9f2b4ab8baf now that we cache to to_tenant value in changesets and queries

improvement: use cached to_tenant when setting tenant attribute

---

lib/ash/code_interface.ex
lib/ash/resource/interface.ex

For some reason opts in code interface `define_calculation` methods were limited to only `actor`.
This allows using `authorize?`, `tenant` and `tracer` too.
(Note: `Ash.calculate` validates opts.)

fix: support all calculate opts in code interface methods

---

lib/ash/resource/change/builtins.ex
lib/ash/resource/change/relate_actor.ex
lib/ash/resource/change/set_attribute.ex
lib/ash/resource/validation/builtins.ex
lib/ash/resource/validation/compare.ex
lib/ash/resource/validation/present.ex
lib/ash/resource/validation/string_length.ex

This allows the validation and change modules to be read and grokked standalone, without needing to flick back and forward with the relevant `Builtins` module to get the options schema.
Added bonus: fixed the docs for `relate_actor` change accidentally being assigned to the `relate_actor_opts` function here https://hexdocs.pm/ash/Ash.Resource.Change.Builtins.html#relate_actor_opts/0
Note that a chunk of the change/validation modules don't have their opt schemas defined like this - possible future work!

refactor: Move opt schema definitions for built-in changes and validations to their specific modules

---

documentation/topics/reference/expressions.md

I think these changes would be needed to make the examples make sense!
Current: https://hexdocs.pm/ash/3.0.0-rc.27/expressions.html#filter-semantics-joins
Now:

docs: Fix filter semantics examples in Expressions guide

---

lib/ash/actions/managed_relationships.ex

Since managed relationship resource can be a tenant resource, the tenant must be set directly in for_create/update and so on.

Set tenant for managed relationship changeset (for 2.0)

---

lib/ash/actions/managed_relationships.ex

Since managed relationship resource can be a tenant resource, the tenant must be set directly in for_create/update and so on.

Set tenant for managed relationship changeset (for 3.0)

---

lib/ash/type/enum.ex

values are only a flat list of values, and map_join would need a function as the third argument if you specify a `joiner`

fix: do not use Enum.map_join in Ash.Type.Enum.cast_atomic

---

lib/ash/code_interface.ex

This bit me today because I had code  like this and it worked in 2.0
```elixir
Resource
|> filter_board_codes(board_codes)
|> filter_min_price(min_price)
|> filter_max_price(max_price)
|> filter_refundable_only(refundable_only)
```
and all the `filter_*` functions looked like this
```elixir
def filter_something(query, nil), do: query
def filter_something(query, something) do
query
|> Ash.Query.filter(....)
end
```

fix: handle resource being passed as query code_interface.ex

---

lib/ash/changeset/changeset.ex
lib/ash/resource/validation/attributes_present.ex
lib/ash/resource/validation/builtins.ex
lib/ash/resource/validation/present.ex
test/actions/validation_test.exs

I require this backport since I'm currently still using version 2.0.

Add attributes_present, attributes_absent for 2.0

---

lib/ash/changeset/changeset.ex

Fix is_belongs_to_rel_being_managed? to match list with more than 2 elements.

Fix is_belongs_to_rel_being_managed? to match list with more than 2.

---

lib/ash/reactor/dsl/change.ex
lib/ash/resource/change/change.ex
lib/ash/resource/validation.ex
lib/ash/resource/validation/function.ex

Breaking change for Ash 3 that aligns anonymous validate functions with those of changes, preparations and `before_action`/`after_action` built-ins helpers. Now anonymous validate functions should expect two arguments - a changeset and a context.

improvement: pass context to anonymous validate functions

---

documentation/dsls/DSL:-Ash.Resource.md
lib/ash/resource/actions/read.ex

This PR adds documentation on ways one can disable pagination in `required?` section of pagination API.

Add documentation on disabling pagination

---

lib/ash/type/union.ex
test/type/union_test.exs

Seems like a few regressions have occurred when handling union arrays if the current value is nil as well as handling resetting an allow_nil? union array back to nil

fix: union array argument/attribute handling when current attribute is nil (Backport for 2.0)

---

lib/ash/type/union.ex
test/type/union_test.exs

Seems like a few regressions have occurred when handling union arrays if the current value is nil as well as handling resetting an allow_nil? union array back to nil

fix: union array argument/attribute handling when current attribute is nil

---

lib/ash/actions/update/bulk.ex

Rollback just accepts the error term, without an error tuple. This broke error handling downstream.

fix: don't pass an error tuple to rollback in bulk update

---

lib/ash.ex
lib/ash/helpers.ex
test/ash_test.exs

`See` #1051 and #1055.
First argument of Ash.create (with a resource) and Ash.update (with a record) no longer are in a tuple with its arguments.
Arguments are now the second argument if it's not a keyword list.

improvement: better create/update first argument

---

lib/ash/actions/read/stream.ex
test/actions/stream_test.exs

If there were 0 results, it just kept reading and reading forever

fix: streaming with limit/offset and no pagination

---

lib/ash/resource/validation/attribute_in.ex
lib/ash/resource/validation/changing.ex
lib/ash/resource/validation/present.ex

`attribute_in` and `changing` were using non-inverted condition in atomic implementation.
`present` was ignoring arguments for `at_most`/`at_least` options.

fix: fixes to some atomic validations

---

documentation/topics/resources/identities.md

I never remember the ExDoc incantation for linking to a specific place in docs. This seems to work!

docs: Add some examples to the Identities guide, with a link to the DSL docs

---

lib/ash/policy/check/changing_attributes.ex

Should return false (as documented and implemented before transition to filter) if any of attributes do not change.

fix: fix `changing_attributes` for multiple attributes

---

lib/ash/policy/check/action.ex
lib/ash/policy/check/action_type.ex
lib/ash/policy/check/built_in_checks.ex
lib/ash/policy/check/resource.ex

1) Adds `List.wrap` call to `changing_attributes`. So one can write `changing_attributes(:my_field)`. 
2) Same for `changing_relationships`. So `changing_relationship` becomes just an alias for `changing_relationships`.
3) Move some wrap calls from runtime `match?` to options creation site.
If you prefer having separate methods I can undo 1 and 2 change and add `changing_attribute` instead. But I think one method is more consistent since you don't have `action` and `actions` for example.
3 is a small breaking change in case somebody was using those check modules directly without normalizing options.

improvement: normalise `List.wrap` usage for policy checks

---

test/actions/bulk/bulk_update_test.exs

It was making also other tests fail

fix: ensure only the intended failing test fails

---

lib/ash/data_layer/ets/ets.ex
test/actions/load_test.exs

One of the two branches was using the non-bang version of a function, which returned `{:ok, filter}`. That value was then directly put in the Query struct, resulting in an invalid filter that was never applied.

fix: make lateral join filtering in ETS data layer work

---

lib/ash/type/type.ex
test/type/array_test.exs

Following [my discussion with Zach on the Elixir Forum](https://elixirforum.com/t/array-type-empty-values-cannot-remove-all-empty-values/63330/3), this PR makes sure to run the item constraints before checking for `nil` values in an array type.
The main goal is to address empty strings being converted to `nil` *after* we checked for `nil` values in the array, effectively resulting in `nil` values in the data layer.
- Moving the `nil` check has the side-effect of not running it anymore when `type.custom_apply_constraints_array?()` is true. In the Ash codebase that only impacts `Ash.EmbeddableType`. I don't know what the implications of that change are, so it's worth making sure it's not breaking any existing behavior for anyone.
- I've added a `test/type/array_test.exs` test file, which …

fix: run array type nil check after item constraints

---

lib/ash/type/type.ex
test/type/array_test.exs

A follow-up to https://github.com/ash-project/ash/pull/1115, which was also [discussed in the Elixir Forum thread](https://elixirforum.com/t/array-type-empty-values-cannot-remove-all-empty-values/63330/2).
This adds a `remove_nil_items?` constraint to the array type, which as its name implies removes `nil` values instead of marking them as errors.

feat: add new remove_nil_items? array type constraint

---

lib/ash/filter/filter.ex

I found no mention in the documentation about the connection between `Ash.Filter` and the `Ash.Filter.Functions.*` modules. Seemed like an important connection to make.

Add documentation for Ash.Filter, linking to Expressions guide

---

test/calculations/calculation_with_auth_test.exs

Side Note, it only happens if the attribute is both selected and part of a calc dependency

add test for calc deps that are forbidden

---

lib/ash/actions/read/read.ex
test/actions/multitenancy_test.exs

Make the tenant available to calculations so they can call `load!` in their code without the need of passing an explicit tenant

improvement: add tenant to data earlier in read

---

lib/ash/resource/change/get_and_lock.ex
lib/ash/resource/change/get_and_lock_for_update.ex

context is now a struct and does not implement access behaviour

fix: access to change context in get_and_lock(_for_update) changes

---

lib/ash/code_interface.ex

Compilation was failing on update code interfaces with require_reference? false and no filters

fix: check require_reference? when generating update code interface

---

documentation/topics/actions/actions.md

`read` actions have to be inside an `actions` block

docs: Clarify resource code in Actions guide

---

lib/ash.ex

Hi,
Found this small error in the documentation for `Ash.create`, it causes the LSP to think the following will not succeed for example:
But it does in fact work

docs: Fix incorrect documentation for Ash.create

---

lib/ash/type/union.ex

This also led to embeddable types not being authorized correctly while casting

fix: add __source__ to union inner_constraints

---

documentation/tutorials/get-started.md

Just a small change to the docs to mirror a change made in the `ash_authentication_phoenix` repo.

docs: change wording to discourage use of `simple_sat` unless needed

---

lib/ash/actions/read/read.ex

Another of my tests failed because nil was returned from `Map.get` above

fix: handle nil case

---

lib/ash/actions/update/bulk.ex
test/actions/multitenancy_test.exs

Fix the usage of the `:use_atomic_update_data?` option so that the `__metadata__` map from the data source is correctly considered when running atomic updates.
For instance, `Ash.update!/3` now correctly keeps the `tenant` metadata on the resource.

Fix: keep data's metadata in atomic update

---

documentation/topics/reference/expressions.md
lib/ash/changeset/changeset.ex

This fixes the argument order in a call to ref in the expressions guide. I also fixed what looks like the same issue in `changeset.ex`, however there is no test coverage – please double check it.

^ref argument order fixes

---

test/actions/bulk/bulk_destroy_test.exs

I'm doing some testing around the new `cascade_destroy` behaviour, and I'll open issues/PRs with failing tests as I come across issues :)

bug: Add failing test for verifying bulk destroy actions

---

lib/ash/type/type.ex

Feels like there might be a cleaner way to do this, but it fixes the problem.

fix: only return valid non nil values items from generator

---

test/actions/bulk/bulk_destroy_test.exs
test/resource/changes/cascade_destroy_test.exs

A couple more issues around using `cascade_destroy` functionality.
Issues occur when there is no data to cascade destroy, or notifications are requested but none are returned

bug: Add more failing tests around cascade_destroy functionality

---

lib/ash.ex
test/actions/bulk/bulk_destroy_test.exs
test/actions/bulk/bulk_update_test.exs

It can't be extracted from an empty list, but it's not actually needed

fix: don't require domain for empty stream bulk update and destroy

---

lib/ash/resource/validation/changing.ex
test/resource/validation/changing_test.exs

- Use the correct option key to select the field
- Fail without hitting the data layer if the attribute is not changing
- Allow checking relationships like the non-atomic counterpart

fix: make Ash.Resource.Validation.Changing work correctly in atomics

---

lib/ash/helpers.ex
test/policy/rbac_test.exs

Since Ash.can? accepts {resource, action, input}, get_domain should also accept it.

Fix get_domain

---

lib/ash/filter/filter.ex

fix: use correct boolean operation names in Filter.find/4

---

lib/ash/actions/read/read.ex
test/actions/create_test.exs
test/actions/destroy_test.exs
test/actions/update_test.exs

Read actions support specifying pagination options on `load` statements for relationships.
These options are correctly respected, and the `count: true` option results in Ash counting the total number of related resources and returning the count in the page returned as the loaded relationship.
However, actions such as `Ash.update!/3` do not properly respect the `load` option since the resulting `count` field is left as `nil`. 
The PR adds a sample failing test.

Pagination: support pagination's `count` on actions besides reads

---

lib/ash/type/union.ex

only passing the item constraints led to an forbidden error for a destroy on an embeddable type because the context with the actor was missing.

do not lose constraints context

---

lib/ash.ex
lib/ash/actions/create/bulk.ex
lib/ash/actions/destroy/bulk.ex
lib/ash/actions/update/bulk.ex
lib/ash/data_layer/ets/ets.ex
test/actions/bulk/bulk_create_test.exs
test/actions/bulk/bulk_update_test.exs
test/actions/create_test.exs
test/actions/update_test.exs

The PR tests loading relationships on multitenant resources after a create or update action.
The introduced tests are currently failing and require troubleshooting.

Test loading relationships on multitenant resources after create or update

---

lib/ash.ex
lib/ash/actions/read/relationships.ex
lib/ash/changeset/changeset.ex
test/actions/bulk/bulk_create_test.exs
test/actions/bulk/bulk_update_test.exs
test/actions/create_test.exs
test/actions/update_test.exs

Ash is already able to load paginated relationships on multitenant resources, see also #1249.
However this change specifically test the case of a many to many relationship where the tenant is included in the primary key of the joined resources.

Test loading paginated relationship when tenant is in primary key

---

lib/ash/actions/destroy/bulk.ex
test/actions/bulk/bulk_destroy_test.exs
test/actions/bulk/bulk_update_test.exs

Asserts that notifications are sent for bulk updates and destroys using the `:stream` strategy with a data layer that supports transactions.
Asserts and fixes #1262

test: assert that notifications are sent for specific cases

---

lib/ash/actions/read/relationships.ex
test/actions/has_many_test.exs

manual relationships don't seem to work when using primary key types that don't have '==' equality i.e: uuid_v7 or AshUUID. not many tests in this manual relationship stuff so not sure if I've broken other cardinality manual relationships by doing this...

fix manual relationships when using 'complex' types

---

lib/ash/actions/update/bulk.ex

the passed action seems to only be the name (atom) of the action and not the action definition

fix: use action from changeset

---

lib/ash/actions/read/read.ex
test/actions/load_test.exs

Currently the logic for `lazy?`-loading calculations and aggregates is wrong, which results in already loaded fields to be loaded again and unloaded fields not to be loaded at all.
The following example will only load the calculation or aggregate if it was already loaded:
```elixir
Ash.load(resource, [:some_agg, :another_calc], lazy?: true)
```

fix: invert logic for lazy-loading calculations/aggregates

---

documentation/topics/resources/validations.md

For the `where` option of the `validate` function in the `Ash.Resource` DSL, the current documentation puts little emphasis on the fact that one can pass a list of validations to construct complex conditionals.
1. Change the text to put more emphasis on the functionality of multiple `where` validations.
2. Add more usage examples.

docs: extend documentation for `validate` `where` option

---

lib/ash/actions/read/calculations.ex

`add_calculation_dependency` expects a MapSet

fix: generate a MapSet, not a list, when creating calculation deps

---

lib/ash/changeset/changeset.ex

The type for the `Changeset.around_transaction_fun` is missing the callback function argument, which results in the following Dialyzer warning in our app:
```
The call 'Elixir.Ash.Changeset':around_transaction
(_changeset@1 :: any(),
fun((_, _) -> any())) breaks the contract 
(t(), around_transaction_fun()) -> t()
``` 
I fixed the spec and refactored the types according the `around_action_fun` spec.

fix: add callback arg to Changeset.around_transaction/2 spec

---

lib/ash.ex
lib/ash/query/query.ex
test/actions/load_test.exs

Enables more optimised data-fetching by only fetching the specified attributes of loaded/nested relationships.

Add strict?-option to Ash.Query.load

---

lib/ash/reactor/steps/action_step.ex
lib/ash/reactor/steps/bulk_create_step.ex
lib/ash/reactor/steps/bulk_update_step.ex
lib/ash/reactor/steps/create_step.ex
lib/ash/reactor/steps/destroy_step.ex
lib/ash/reactor/steps/read_one_step.ex
lib/ash/reactor/steps/read_step.ex
lib/ash/reactor/steps/update_step.ex

This fix uses the passed action context when running a Reactor from a generic resource action, which is currently ignored.
I'm not sure if there are good and valid reasons for having the opportunity to specify actor/tenant/authorize? as step attributes (`Ash.Reactor.ReadStep` for example), or if those values could just be placed in the context as well when invoking `Reactor.run` directly? At least that would simplify the logic a tiny bit, if possible 😅 
Anyway, this is not a breaking change, and fixes running a reactor that requires access to values from the generated action-context, which will currently break if any of the steps require access to the actor/tenant etc from the action's opts.

Make action ctx-values from reactor-ctx take precedence if set.

---

lib/ash/reactor/builders/ash_step.ex
lib/ash/reactor/dsl/ash_step.ex
lib/ash/reactor/reactor.ex
lib/ash/reactor/steps/ash_step.ex

Adds a wrapper that handles enqueueing of any returned ash-notifications when running a regular step-module or an anonymous run-function.

Add ash_step wrapper.

---

lib/ash/type/new_type.ex
test/type/new_type_test.exs

fix: Fix cast_input/2 of Ash.Type.NewType returning :ok

---

lib/ash/resource/actions/create.ex
lib/ash/resource/actions/destroy.ex
lib/ash/resource/actions/update.ex

This was causing a CI failure for AshAuthentication.
https://github.com/team-alembic/ash_authentication/actions/runs/9994845281/job/27626214114?pr=747

chore: fix typespecs for `accepts` key in action entity structs.

---

lib/ash/expr/expr.ex
lib/ash/query/function/parent.ex

Struct is a map, so no need for same but separate overloads for struct and map.
Also fixed doc for `Ash.Query.Parent`.

fix: remove redundant overload of `Ash.Expr.get_path`

---

lib/ash/type/ci_string.ex
lib/ash/type/string.ex

This closes https://github.com/ash-project/ash/issues/1333.
This ensures the min_length is respected whenever using the default generator for string/ci_string types.

Update string/ci_string generators to ensure min_length

---

documentation/dsls/DSL:-Ash.Resource.md
lib/ash/resource/dsl.ex

I noticed that the defaults weren't being formatted as code, eg. here https://hexdocs.pm/ash/dsl-ash-resource.html#attributes-uuid_v7_primary_key
Now they are!
(repeated for all special attributes in this DSL that formatted things like this)

docs: Format default options for special attributes as code, in Ash.Resource DSL

---

lib/ash/type/enum.ex
test/type/enum_test.exs

Implement the `@type t()` for `Ash.Type.Enum` implementations.
This allows users to write simpler typespecs in their applications.
Example:
```elixir
iex> t Ash.Type.DurationName
@type t() ::
:microsecond
| :millisecond
| :second
| :minute
| :hour
| :day
| :week
| :month
| :year
```
The `quote` was switched to use `bind_quoted` instead of unquoting the values. This is because  the `unquote` in the `@type` was wrongly unquoting into the macro scope and not into the module scope as usual.

Expose type t() on Ash.Type.Enum implementations

---

lib/ash/query/query.ex
test/actions/manual_read_test.exs

The function is meant to be used to act on data that is in-memory, so it makes sense to not read data again. Moreover this caused an infinite loop if using this at the end of a manual read.
Add a regression test for the manual read case.

fix: pass reuse_values? true when loading in Ash.Query.apply_to/2

---

lib/ash/type/new_type.ex
test/type/new_type_test.exs

The previous implementation was behaving differently when dealing with single values and arrays.

fix: apply constraints to NewType even when casting an array

---

lib/ash/type/file.ex
lib/ash/type/file/implementation.ex
lib/ash/type/file/io.ex
lib/ash/type/file/path.ex
lib/ash/type/file/plug_upload.ex
lib/ash/type/file/source.ex
lib/ash/type/type.ex
test/type/file_test.exs

Implementation of ash-project/ash_phoenix#226
The file type should allow access to the underlying file with a standardized interface.
I propose that we'll have two functions:
* `path/1` (optional) - Get path of the file if it is on disk. Allows maximum freedom but might not be supported by all implementations.
* `open/2` (required) - Allows access to the file content via the `IO` module. Custom implementations for the [I/O Protocol](https://www.erlang.org/doc/apps/stdlib/io_protocol.html) should allow access to any implementation and is already standardized.
I intended this type mainly for action arguments. Those will never be stored.
* File type is usable for direct code action access
* `Plug.Upload` works through phoenix controllers
* `Plug.Upload` works through `ash_graphql` if …

Add Ash.Type.File

---

lib/ash/error/framework/can_not_be_atomic.ex
lib/ash/policy/info.ex
test/actions/bulk/bulk_create_test.exs
test/actions/bulk/bulk_destroy_test.exs
test/actions/bulk/bulk_update_test.exs
test/actions/create_test.exs
test/actions/destroy_test.exs
test/actions/update_test.exs

Right now it's not always checked if a validation only has an atomic implementation and it throws an error. 
According to the docs this should be possible? https://hexdocs.pm/ash/dsl-ash-resource.html#validations-validate-always_atomic?

test: atomic only validation

---

test/policy/filter_condition_test.exs

This is just an failing test case.
If you comment out `attribute :is_active, :boolean, default: true, public?: true`(filter_condition_test.exs:124) in Post,
then this test would pass.
Here's what I found. (This could be wrong...)
1. Author has `is_active` attribute.
2. Post has `is_active` attribute, too.
3. Author's `is_deactivated` calculation uses `is_active` in expr.
4. Post's policy uses `Author.is_deactivated`.
With these conditions, `Author.is_deactivated` should check `Author.is_active`,
but it actually checks `Post.is_active`, I think.

test: use other resource's calculation in inline filter policy

---

lib/ash.ex
lib/ash/helpers.ex
test/actions/bulk/bulk_create_test.exs

Warn on bulk action `return_stream?` without any other `return_*?` options enabled.

---

lib/ash/actions/create/bulk.ex
test/actions/bulk/bulk_create_test.exs

Fix `after_batch` arguments for `bulk_create` with `return_records?` disabled

---

lib/ash/type/struct.ex
test/type/struct_test.exs

This PR fixes
- no cond clause evaluated to a truthy value
- error that occurs when nil is passed as an argument of type :struct.

Fix error with nil value

---

documentation/topics/security/policies.md

There is no built-in check for `attribute` - but the same logic can be expressed readably with a call to `expr`.

docs: Replace incorrect `attribute` policy check in Policies guide with an `expr`

---

lib/ash/resource/attribute.ex

Noticed this funny one when browsing the docs today:
Fixed it!

docs: Stop the `*` in `Ash.Type.*` italicising everything when converted to Markdown

---

lib/ash/resource/change/change.ex
test/actions/bulk/bulk_create_test.exs

According to the [docs](https://github.com/ash-project/ash/blob/55f1ead24fa708a6cc356f289adeb855b72a6bcd/lib/ash/resource/change/change.ex#L113-L114), implementing `change/3` should be optional when using `batch_change/3`. In this case, Ash will generate a `change/3` function as a wrapper around `batch_change/3`, but this had the following issues:
1. the arguments for `Changeset.before_action/2` were wrong
2. the generated code contains a call to `before_batch/3` and `after_batch/3`, which caused a compiler error if these functions were not implemented in the change module. I replaced these with `apply/3`, but maybe this could be refactored to generate these callbacks if they are missing.

Fix generated `change/3` function when only implementing `batch_change/3`

---

lib/ash/filter/filter.ex

Adding specific handling for Ash.Query.Call in Filter.map to avoid unnecessary recursion into the internals of the struct.

add pattern for Ash.Query.Call in Filter.map

---

lib/ash/resource/dsl.ex
lib/ash/resource/info.ex
lib/ash/resource/transformers/cache_calculations.ex

Two performance optimizations:
- avoid falling back to a search on nil, which happens quite a lot because we often look up whether non relationships are relationships.
- add similar caching for calculations
But, it seems there's quite a lot of cases where we look up things other than string or atom keys. That seems like it's probably not the right thing to be doing.
In all these cases, in the current implementation we would be comparing relationship name with things like Attribute structs, calculation modules, Ash.Query. All of which would never match a string/atom name.
To get all the tests to pass without introducing a performance issue I add:
def calculation(_resource, _relationship_name) do: nil
def relationship(_resource, _relationship_name) do: nil
But I'm rather assuming that these …

Improve caching for relationships and add caching for calculations

---

lib/ash/resource/info.ex

This catches a performance impact when looking up things that aren't attributes.
Also change a Transformer that runs before the attribute cache so it now doesn't depend on Info.attribute

Remove cache fallback for Info.attribute

---

lib/ash/query/query.ex
lib/ash/resource/info.ex
lib/ash/resource/transformers/attributes_by_name.ex

When building select lists we can use a cached version of the list of always selected attributes.
And using Mapsets improves efficiency when combining the lists
Note that I returned a mapset from the Info function to be slightly more optimal but this isn't quite consistent with other such functions which return ordinary lists.

Cache always selected fields and use mapsets for building select list

---

documentation/how-to/authorize-access-to-resources.livemd

"the check this" -> "then check this"

Fix typo in authorize-access-to-resources howto

---

lib/ash/filter/filter.ex

Filter.map is often called with data structures that include mapsets so we should handle those directly without unpacking the structs.

Add a case for handling mapsets in Filter.map

---

lib/ash/actions/create/bulk.ex
lib/ash/changeset/changeset.ex
test/actions/bulk/bulk_create_test.exs

While working on a bulk create operation, I encountered an issue where the upsert condition worked correctly for managed relationships but failed for the primary resource being upserted. Upon investigation, I traced the problem back to the base changeset, which lacked the necessary filter for the upsert condition.
Adding the missing filter, however, caused the existing bulk create test to fail. Further debugging revealed that the bulk create test had never actually functioned correctly - it was missing a require Ash.Expr statement. It's unclear how the test passed previously, given that the required macros were missing.

Fix bulk upsert condition

---

lib/ash/resource/preparation/builtins.ex

Also attempted to clarify that these aren't the same functions as in the arguments to `Ash.Query.before_action` and `after_action` - they take an additional argument for `context`

docs: Fix examples for builtin `before_action` and `after_action` preparations

---

lib/ash/type/time.ex

just like the commit d4a6feb58 for datetime but for time plus reordering the functions so its the same order as in naive_datetime.ex and date.ex
found this while using :time in an embedded resource 
got the following error:
```
↳ Ash.Actions.Create.Bulk.handle_batch/9, at: lib/ash/actions/create/bulk.ex:456
** (Ash.Error.Unknown) Unknown Error
* ** (ArgumentError) cannot load `[%{"day" => "monday", "from" => "08:00:00", "to" => "10:00:00"}]` as type {:array, #REDACTED.EctoType<[on_update: :update_on_match]>} for field :REDACTED in #REDACTEDh<address: #Ash.NotLoaded<:relationship,  ...>
(ecto 3.12.3) lib/ecto/repo/queryable.ex:431: Ecto.Repo.Queryable.struct_load!/6
(ecto 3.12.3) lib/ecto/repo/schema.ex:76: anonymous fn/4 in Ecto.Repo.Schema.postprocess/5
(elixir 1.16.3) lib/enum.ex:1700: …
```

fix: cast embedded time properly

---

lib/ash/filter/filter.ex
test/query_test.exs

I have a resource with a postgres ltree as primary key, which is represented as a list of strings.
The `InvalidFilterValue` bubbles up from a `manage_relationship` change.

Handle Ash.Query.filter for array values

---

lib/ash/changeset/changeset.ex

Hi @zachdaniel 
The change to changeset.select leads to runtime errors if we use `change ensure_selected(attr)`. If we escape the `changeset.select || []` properly, the runtime errors are gone. Not sure if this is the right place and I do not have time to add some tests, sorry.

fix(ensure_select): properly escape changeset.select

---

lib/ash/actions/create/bulk.ex
lib/ash/actions/destroy/bulk.ex
lib/ash/changeset/changeset.ex

Closes #1473.
Exact same change as in 66cc0e48f1298fc7e68f0b373f7e4ae978c0b650 applied to bulk create/destroy.
(Also fixed typespec for `before_action` of changeset.)

fix: add checks for `around_transaction` and `around_action` in bulk

---

lib/ash/changeset/changeset.ex

Question: it is not mentioned but `around_action` is not compatible with atomic (as in, those hooks are not executed if changeset is atomic), correct?

docs: correct return type for `around_action`

---

lib/ash/query/query.ex
test/changeset/changeset_test.exs
test/query_test.exs

fix(Ash.Query): calling `for_read/2..4` should raise an `ArgumentError` when the specified action doesn't exist.

---

lib/ash/actions/helpers.ex

I think `Enum.reject` is better fit here.

chore: simplify `Actions.Helpers.select_mask`

---

documentation/topics/security/actors-and-authorization.md

Correctly reflect that `:by_default` is the default behaviour
~~- [ ] Bug fixes include regression tests~~
~~- [ ] Chores~~
~~- [ ] Features include unit/acceptance tests~~
~~- [ ] Refactoring~~
~~- [ ] Update dependencies~~

docs: fix authorize? default

---

lib/ash/actions/aggregate.ex

The context provided to `Ash.aggregate!` does not bubble down to the data layer.

Pass context into `data_layer_query` in Ash.Actions.Aggregate

---

lib/ash/query/query.ex

The current functionality just sets the default select fields but does not ensure the fields requested by the user are selected.
It is not possible to test select related functionality on the ETS or Simple datalayers since both return `false` for `can?(_, :select)`. Otherwise, we would add the following to `Ash.Test.QueryTest`:
```elixir
defmodule User do
...
attributes do
...
attribute :unselected_list, {:array, :string}, select_by_default?: false
end
end
describe "ensure_selected" do
test "it does not deselect default fields" do
assert User
|> Ash.Query.for_read(:read)
|> Ash.Query.ensure_selected([:unselected_list])
|> Ash.Query.loading?(:name)
end
test "it selects non-default fields" do
assert User
|> Ash.Query.for_read(:read)
|> Ash.Query.ensure_selected([:unselected_list])
|> …
```

Fix `ensure_selected` for cases where `query.select` is nil

---

documentation/topics/actions/update-actions.md

Noticed a small mistake in docs `Ash.Changeset.set_attribute` does not exist, it should be `Ash.Changeset.change_attribute` instead

chore: Minor docs correction on update action

---

lib/ash/query/function/today.ex

`today()` returns a Date, not a DateTime.
Doc fixed.

docs: fix Ash.Query.Function.Today doc

---

lib/ash/seed.ex
test/seed_test.exs

Ash.Seed.upsert! function to create or update resources based on the specified identity
PR opened regarding the problem listed on [this](https://elixirforum.com/t/how-would-i-call-directly-the-datalayer-bypassing-the-action/66738) post on elixirforum.

feat: ash seed upsert! function

---

lib/ash/resource/transformers/set_primary_actions.ex
test/resource/default_actions_test.exs

When the resource's data layer doesn't support transactions the generated default actions don't enable transactions.

improvement: Conditionally enable transactions on default actions.

---

lib/ash/reactor/dsl/action_transformer.ex
test/reactor/inputs_test.exs

Closes [#126](https://github.com/ash-project/reactor/issues/126).

fix(Reactor): Don't validate `inputs` keys when being transformed.

---

documentation/topics/actions/generic-actions.md

Fixing an the callback arguments of `run` in the generic-actions.md doc

docs: Update generic-actions.md

---

lib/ash/type/decimal.ex

fix: check nil before calling Decimal.eq? in Type.Decimal.equal?

---

test/calculations/calculation_with_embedded_resource_test.exs

Prove that Ash can return a list of embedded resources via a calculation.
We thought we encountered a bug.
Turns out, it was just me doing something wrong.
This test serves as the result and prove that what I tried to do indeed works.

testing: prove that calculations can return a list of embedded resources

---

lib/ash/resource/validation/builtins.ex

Simple fix to docs to reflect actual api, where if you want to check the length of a string is exactly X, you should use the keyword `exact:`.

fix example of using string_length

---

lib/ash/policy/check/changing_attributes.ex

This piece of code in `changing_attributes` check does not make sense to me right now:
```elixir
if Keyword.has_key?(opts, :from) && changeset.action_type == :create do
if opts[:from] == nil do
{:halt, false}
else
{:cont, expr}
end
else
```
It says that `from: nil` is bad but `from: :whatever` is good.
First, I assume that the branches were supposed to be reversed - if `from: nil` then it matches create otherwise not.
Second, but that supposed reversal is also bad as it does not take into account attribute's default value (so it is questionable that the change is from nil) and also ignores potential presence of `to` option.
So instead just do return false for create changeset if `from` option is present.

fix: properly handle `changing_attributes` check with `from` in create

---

lib/ash/domain/info/livebook.ex
test/domain/livebook_test.exs
test/support/flow/user.ex

The `mix ash.generate_livebook` task was generating bad Markdown for multiline attributes - the new lines were being included as-is which broke the tables.
This introduces a little helper to use breaks instead of newlines, and renders much better.
Before:
After:

fix: Allow multi-line descriptions to be rendered in Livebook without error

---

lib/ash/type/type.ex

Notices that some of the code blocks here https://hexdocs.pm/ash/Ash.Type.html weren't syntax-highlighted - they are now :)

docs: Fix syntax highlighting for `Ash.Type` code blocks

---

lib/ash/actions/create/bulk.ex
lib/ash/actions/destroy/bulk.ex
lib/ash/actions/update/bulk.ex

fix: handle notifications returned from simple results in bulk actions

---

lib/ash/query/query.ex
test/query_test.exs

**Issue**
When an Ash resource read action has an argument with a 'constraints' option and a defined constraint is violated by the provided argument value, then the following Warning is printed:
```
warning: the following fields are unknown when raising Ash.Error.Query.InvalidArgument: [ ...
```
**Solution**
Ensure, that `Ash.Query` does not try to add unknown fields when creating `Ash.Error.Query.InvalidArgument`

Fix warning when actions.read.argument constraint is violated

---

lib/ash/changeset/changeset.ex
lib/ash/resource/change/before_action.ex
lib/ash/resource/change/before_transaction.ex
lib/ash/resource/change/builtins.ex

Since Ash 4 changed order of execution for before hooks there is no more `append?` option - it was replaced with `prepend?`. But built-in helpers (`before_action` and `before_transaction`) and some other places are still referencing and specifying `append?`.

fix: finish conversion from `append?` to `prepend?` option

---

lib/ash/changeset/changeset.ex

Should it perhaps be implemented as a separate clause to avoid doing any needless work? E.g.:
```
def manage_relationship(changeset, _, _) do
IO.warn("...")
changeset
end
```
Fixes:  #1407

Warn when `manage_relationship` is called without opts

---

lib/ash/changeset/changeset.ex
test/actions/atomic_update_test.exs

Conditions didn't work in fully atomic scenarios because the code was handling the logic per validation in a backward manner. This negates the result of each validation expression do atomic conditions work as expected.
Fixes #1619.

fix: negate atomic validation expressions when used as `where` conditions

---

lib/ash/changeset/changeset.ex

The pattern matching can be done just as easily in the reduction which is more efficient.
I couldn't leave this, lol. Next time there's a minor thing, I'll just get to it before the merge unless a release needs to go out ASAP. I have a serious case of FauxCD.
I also realized how silly `Stream` was for _just one_ destructure anyway. That's even overkill for me.

improvement: remove unnecessary Stream

---

documentation/topics/actions/create-actions.md
documentation/topics/actions/destroy-actions.md
documentation/topics/actions/generic-actions.md
documentation/topics/actions/read-actions.md
documentation/topics/actions/update-actions.md

The DSL docs are super useful and they should be pointed out right near the top of the action guides!

docs: Add links from Action guides to the DSL docs for that action type

---

documentation/topics/about_ash/alternatives.md

Hello,
I recently separated this project. Previously, the kind team at Ash included it on the Alternatives page.
Thank you!

Change the Project Link in the Alternatives Documentation

---

lib/ash/resource/actions/action/action.ex
lib/ash/type/type.ex
lib/mix/tasks/gen/ash.gen.resource.ex

Hello!
Addressing issue [#1553](https://github.com/ash-project/ash/issues/1553).
Looking for feedback on the following
1. Meaningful error for unrecognized gen.resource task attribute modifier
2. Check attribute type is a valid ash type + bit refactoring
3. Filter out duplicate modifiers on an attribute
4. Delete removed alias examples from docs.

improvement: More Descriptive Error Messages for ash.gen.resource

---

lib/ash/filter/filter.ex

I personally struggled with the current description. I hope this reduced wording is more explicit, while re-using explanation from `Ash.Query.filter_input/2`.
Following on from my post [here](https://elixirforum.com/t/how-to-filter-an-array-attribute-to-find-at-least-one-instance-using-map-syntax/67887) while the iron is hot. If I've misunderstood things I'll remove/correct this PR as needed.

docs(filters): clarify how to use string maps

---

test/manage_relationship_test.exs

add a manage_relationship test that creates resources

---

lib/ash/actions/managed_relationships.ex
test/manage_relationship_test.exs

Technically, [line 1689](https://github.com/lardcanoe/ash/blob/soft-deletes-manage-relationship/lib/ash/actions/managed_relationships.ex#L1689) also has this issue, but not sure how to target it.

fix - handle soft destroys with manage_relationship

---

lib/ash.ex
lib/ash/actions/helpers.ex

`Ash.Query.load` has `strict?` option that limits loaded/selected fields to those that explicitly specified.
This PR allows passing that option to read methods - `Ash.get`/`Ash.read`/`Ash.read_one` and so on - that already do have `load`/`reuse_values?` options.
So now one will be able to write `Ash.get!(User, id, load: [:name], strict?: true)`.

improvement: add support for `strict?` in read options

---

lib/ash/notifier/pub_sub/pub_sub.ex
lib/ash/notifier/pub_sub/publication.ex

This patch adds `except` option to `pub_sub.publish_all` that allows to exclude certain actions from notifications.
My motivation for this is the following scenario:
I have a resource that has multiple update actions that require notifications, and only one action for which notifications are not required (and are pointless since it is only used during application shutdown). Without this option, I have to list all actions separately and remember to update the notifications list each time I add a new action.

allow exclusion of certain actions from publish_all

---

lib/ash/data_layer/ets/ets.ex

Right now ETS data layer (and Mnesia because of that) use aggregate default only in case of `first` aggregate kind and only when there are no records - so if the first record has a value of nil then it will return nil. That is not how it is in other data layers or in Ash runtime filter logic - if the resulted aggregate value is nil (because there are no records or because they have nil values) then the default is used. This PR aligns ETS logic with that of sql/runtime ash.

fix: properly handle aggregate defaults in ets/mnesia

---

lib/ash/notifier/pub_sub/pub_sub.ex
test/notifier/pubsub_test.exs

My previous patch had a bug – wrong key for action name

fix "except" option handling

---

.formatter.exs
documentation/dsls/DSL-Ash.Domain.md
documentation/dsls/DSL-Ash.Resource.md
lib/ash/code_interface.ex
lib/ash/resource/interface.ex
test/code_interface_test.exs

We had discussed [this feature in Discord](https://discord.com/channels/711271361523351632/711271361523351636/1303019179472977930) when I first started messing around with Ash. I figured I'd finally give it a crack.
I did more refactoring. It's probably easier to understand specifically what happened going through the changes commit by commit rather than just looking over the files changed. I left a pretty good trail of what I did.
I wonder if `Ash.CodeInterface.params_and_opts/2` should exist there specifically or perhaps elsewhere. That pattern seems like it's really common.
What is the purpose of allowing keyword parameters? It seems like such a weird feature since it _must_ be paired with non-empty options.

Add default code interface options

---

lib/ash/helpers.ex
lib/ash/query/function/error.ex
lib/ash/query/operator/basic.ex
lib/ash/type/keyword.ex
lib/ash/type/map.ex
lib/ash/type/struct.ex

- Add `Ash.Helpers.json_module/0` that uses Elixir's `JSON` module when loaded.  Otherwise it returns `Jason`.  This will enable `Jason` to be set as an optional dependency in future Ash versions and allow any libraries depending on Ash to leverage the same `json_module` Ash uses.

chore: Optionally use JSON when available

---

documentation/dsls/DSL-Ash.Resource.md
lib/ash/resource/dsl.ex

Replaces "teplates" in the docs with "templates".

Fix "teplates" typo in docs

---

lib/ash/generator/generator.ex

Currently, attempting to use `Ash.Generator` in tests will raise a warning:
```
Compiling 1 file (.ex)
warning: Ash.Generator.create/1 is undefined or private
│
4 │   use Ash.Generator
│   ~~~~~~~~~~~~~~~~~
│
└─ test/support/generator.ex:4: Tunez.Generator.create/1
warning: Ash.Generator.create_many/1 is undefined or private. Did you mean:
* generate_many/2
│
4 │   use Ash.Generator
│   ~~~~~~~~~~~~~~~~~
│
└─ test/support/generator.ex:4: Tunez.Generator.create_many/1
```

fix(`Ash.Generator`): Replace calls to `create` and `create_many` with `generate` and `generate_many`

---

lib/ash/generator/generator.ex

When testing out `generate_many/2` I found there were a couple of issues with it:
* It would error if `after_action: nil` was passed to `bulk_create`
* It would error if the full action struct was passed to `bulk_create` (instead of just the action name)
* It would error if the action passed to `bulk_create` required authorization (no actor being passed in)
* It would raise warnings if the action used in `bulk_create` generated any notifications (tbh I'm not sure *why* the action I'm testing with is generating notifications, but that's a different story)
* It would ignore partial success results, leading to random test failures due to intermittent erroneous generator data
With these changes I can successfully call `generate_many` like `generate_many(artist(), 2)` and get two Artist …

fix: Fix issues in `Ash.Generator.generate_many/2`

---

lib/ash/generator/generator.ex

What it says on the tin! As soon as I tried to add a call to `generate_many` inside my module that calls `use Ash.Generator` it was like noooope `imported Ash.Generator.generate_many/2 conflicts with local function` again

fix(`Ash.Generator`): Fix typo in skipped import name

---

lib/ash/test.ex
test/error_test.exs

Currently if you set up an assertion like the following:
```elixir
%{artist_id: artist.id, name: "test 1960", year_released: 1960}
|> Music.create_album(actor: admin)
|> assert_has_error(Ash.Error.Invalid, "a dummy callback")
```
when the `create_album` call actually succeeds, `assert_has_error` will have a `CaseClauseError`:
```
1) test validations year_released must be between 1950 and now (TunezWeb.Music.AlbumTest)
test/tunez/music/album_test.exs:156
** (CaseClauseError) no case clause matching: {:ok, #Tunez.Music.Album<duration: #Ash.NotLoaded<:calculation, field: :duration>, ...>}
code: |> assert_has_error(Ash.Error.Invalid)
stacktrace:
(ash 3.4.54) lib/ash/test.ex:49: Ash.Test.assert_has_error/4
test/tunez/music/album_test.exs:190: (test)
```
In this case, I think it's pretty safe …

chore(`Ash.Test`): Updates to `assert_has_error` and `refute_has_error` to accept `:ok` tuples

---

test/policy/rbac_test.exs
test/support/policy_rbac/resources/file.ex

Add a failing test for arguments not being passed to queries when testing `can_*` actions for code interfaces.
Prior to [df66222](https://github.com/ash-project/ash/commit/df6622207d04c1b23cc6398946c42d1f645f04ab) this test failed with the following error:
```
1) test if the action can be performed, the can utility should return true (Ash.Test.Policy.RbacTest)
test/policy/rbac_test.exs:82
** (Ash.Error.Invalid)
Invalid Error
* argument id is required
(ash 3.4.54) lib/ash/error/query/required.ex:5: Ash.Error.Query.Required.exception/1
(ash 3.4.54) lib/ash/query/query.ex:674: anonymous fn/2 in Ash.Query.require_arguments/2
(elixir 1.18.0) lib/enum.ex:2546: Enum."-reduce/3-lists^foldl/2-0-"/3
(ash 3.4.54) lib/ash/query/query.ex:591: Ash.Query.for_read/4
(ash 3.4.54) …
```

chore: Add failing test for `Ash.can?` for `get? true` actions with authorization applied

---

lib/ash/type/type.ex
lib/ash/type/uuid.ex
lib/ash/type/uuid_v7.ex

Closes #1714 
- Adds `autogenerate_enabled?` option to `Ash.Type`.  When true `Ash.Type.EctoType.autogenerate/1` is added to the module.
- Adds `Ash.Type.EctoType.autogenerate/1` which mirrors `Ecto.ParamaterizedType.autogenerate/1` so Ash types like `Ash.Type.UUID.EctoType` and `Ash.Type.UUIDv7.EctoType` can be drop ins for existing Ecto schemas `@primary_key` and `@foreign_key_type` schema module attributes.

Add `Ash.Type.EctoType.autogenerate/1` for drop in replacement with existing Ecto Schemas

---

lib/ash/filter/filter.ex
test/filter/multitenancy_test.exs

- allows `get` to not require the multitenancy attribute

fix: don’t require multitenancy attribute in `get`

---

lib/ash/resource/validation/match.ex

Getting an error message like this in a test:
```
** (Ash.Error.Framework)
Framework Error
* Tunez.Music.Album.update must be performed atomically, but it could not be
Reason: can't atomically match an attribute that is not changing
See https://hexdocs.pm/ash/update-actions.html#fully-atomic-updates for more on atomics.
```
Doesn't make it clear what's going on or why. I didn't even realize it was talking about a match validation, not a pattern match!
I think this makes it a little clearer what's going on.

chore: Use clearer error message for match validation atomic errors

---

lib/ash.ex

I thought that `read_first!` would raise an error in the case of no results found - it won't

docs: Clarify the behaviour of `Ash.read_first` and `read_first!` by adding typespecs

---

lib/ash/reactor/builders/ash_step.ex
test/reactor/ash_step_test.exs

These options were always just ignored but now are rejected because Reactor validations options now.

fix: Compilation failure when using the `ash_step` Reactor DSL.

---

lib/ash/type/struct.ex
test/type/struct_test.exs

#1754 
Not sure about the error messages, took a guess. I also added `"is invalid"` for the last error. Although I couldn't figure out how to trigger that.
Also should `Elixir.` part be shown 🤔

fix: type struct handle instance of return error tuple

---

lib/ash/resource/change/cascade_destroy.ex

fix: pass tenant to load in cascade destroy

---

lib/ash/code_interface.ex

#1776 
`describe_calculation` has this but `describe_action` didn't.

docs: In `describe_action` sort arguments by order

---

lib/ash/resource/verifiers/verify_primary_read_action_has_no_arguments.ex

Fix: Include warning for arguments only when 'things' are arguments

---

documentation/topics/actions/destroy-actions.md

I checked the code and it looks like the input is not optional

docs: add missing inputs to the bulk_destroy examples

---

documentation/topics/resources/identities.md
lib/ash/changeset/changeset.ex
lib/ash/resource/identity.ex
test/actions/identity_test.exs
test/resource/identities_test.exs

This PR add `field_names` option to identities. It will work in tandem with https://github.com/ash-project/ash_postgres/pull/478

Add field names to identities

---

lib/ash/actions/action.ex
test/actions/generic_actions_test.exs

Generic actions to raise if they don't have return type but have an return value

---

lib/ash/changeset/changeset.ex

This updates the tenant in the `Ash.Resource.Change.Context` before running each change. 
If you have an action with multiple changes, and one change uses `Ash.Changeset.set_tenant`, now the changeset's tenant and the context's tenant will be aligned in the subsequent changes.

fix: update context tenant from changeset for each change in an action

---

documentation/dsls/DSL-Ash.Reactor.md
lib/ash/actions/helpers.ex
lib/ash/changeset/changeset.ex
lib/ash/policy/check.ex
test/actions/load_test.exs

Was getting error about `nil` not implementing enumerable protocol. It was because `changes` map won't contain changes that did not pass their conditional `where` validations.
Also included a formatting fix, a credo fix, a typo fix and a cheat sheets fix.

fix: properly handle change with `where` validations in bulk

---

lib/ash/actions/update/bulk.ex
lib/ash/actions/update/update.ex

`Ash.Actions.Update.run` [can return `:ok`](https://github.com/ash-project/ash/blob/0761bbbaaab11e22ab33f7ee7a919473f7ebb33c/lib/ash/actions/update/update.ex#L391) in case of a soft destroy. So such return variant needs to be handled in processing of bulk update.
(Typespec for `run` does not list simple `:ok` as a potential result right now. Didn't know if I should have added it in this PR.)

fix: properly handle bulk soft destroy

---

documentation/topics/security/policies.md

This fixes an error-throwing example in the policy docs (see [here](https://elixirforum.com/t/ensure-actor-can-only-create-resource-for-themselves/69988?u=sodapopcan)).
I can also add a note (either code comment above the `create` example or admonition block below) about not being able to use field references in create policies but I'm not sure this is the right place.

Fix erroneous policy group example

---

lib/ash/actions/create/bulk.ex
lib/ash/resource/manual_actions/manual_create.ex
test/actions/bulk/bulk_create_manual_test.exs

Fixes the handling of results from the bulk_create/3 for Ash.Resource.ManualCreate,
- [x ] Bug fixes include regression tests

Fix bulk_create for manual create actions with bulk_create/3

---

config/config.exs
test/actions/load_test.exs

The issue has been present since commit `5665ec59` when `keep_read_action_loads_when_loading?` is true.

Add failing test for ignored calculation arguments

---

lib/ash/actions/update/bulk.ex

Bulk destroy [sets](https://github.com/ash-project/ash/blob/d2fd8e4d29323c23b52358aa315b56e05e506f6f/lib/ash/actions/destroy/bulk.ex#L1374) `opts[:return_destroyed?]` to `opts[:return_records?]` before calling destroy action. But if the destroy is soft then it will be handled by bulk update and it [does not set](https://github.com/ash-project/ash/blob/d2fd8e4d29323c23b52358aa315b56e05e506f6f/lib/ash/actions/update/bulk.ex#L1678) such thing right now.
Encountered the problem when by simply adding AshArchival the result of graphql mutation became nil instead of a record.

fix: return records from bulk soft destroy if requested

---

documentation/tutorials/get-started.md

I think it should be like this:

Move misplaced sentence in the getting started guide

---

lib/ash/type/type.ex

- [ X] Documentation changes
Suggesting a documentation update for Ash.Type (to refer to Ash.Type.NewType) along the lines of the commit.
All in support of improving the clarity of the issue discussed in: https://elixirforum.com/t/best-strategy-to-storing-an-elixir-struct-type-attribute-using-ash/70032/3

Added link to Ash.Type.NewType in main Ash.Type docs

---

documentation/topics/resources/validations.md
lib/ash/resource/validation/action_is.ex
lib/ash/resource/validation/builtins.ex
test/resource/validation/action_is_test.exs

- Update `Resource.Validations.ActionIs` to accept `atom | list(atom)` as described in the documentation
- Add `Resource.Validations.ActionIsTest` to verify that it handles both `atom` and `list(atom)`
- Add opts_schema to help with documentation - `action` is a `{:wrap_list, :atom}`
- Keep same exception message for backwards compatibility in case anyone is matching on it

fix: update Validations.ActionIs to accept atom or list(atom)

---

test/actions/load_test.exs

This test reproduces an issue where arguments are correctly applied when calling
`post |> Ash.load!(sum: [a: 3, b: 4])`,
but not applied when loading from a parent record like:
`author |> Ash.load!(posts: [sum: [a: 3, b: 4]])`.
You can reproduce the issue by running:
`mix test test/actions/load_test.exs:2024`

Add failing test: calculation arguments should be respected for nested loads

---

documentation/how-to/write-queries.livemd
lib/ash/query/query.ex

There were a few cases in the documentation where `Ash.Query.sort/2` was used where it should have been `Ash.Query.sort_input/2`.

docs: fix several cases that should be Ash.Query.sort_input/2

---

documentation/topics/actions/destroy-actions.md

Was looking at how to call a destroy action and noticed that the docs were referencing `Ash.Query.for_destroy` function, which I think was meant to be `Ash.Changeset.for_destroy`.

[docs] Update destroy actions docs to reference correct function name

---

test/actions/update_test.exs

I've found that calling `Ash.update` causes already-loaded relationships to be replaced with `%Ash.NotLoaded{}`. I'm wondering if this is the intended behavior.
I noticed this because previously the loaded relationships were preserved after an update, but after a recent update, they are being set to `%Ash.NotLoaded{}`, which led to a raise in our code.

Failing test: update unloads already loaded relationships

---

lib/ash/expr/expr.ex

Just allows omitting `true` as the last argument for `exists` in `expr`.
Any downsides that I don't see?

improvement: support `expr(exists(relation))`

---

documentation/topics/reference/expressions.md
lib/ash/expr/expr.ex
test/expr_test.exs

- raises ArgumentError with example
case is not allowed in ash expressions. instead use  cond.

fix: case is not allowed and cond is allowed in ash expressions

---

README.md

Since there is a single tutorial, I think it makes sense to promote it to the top without the intermediate section, and explain it’s for beginners to Ash.
The other sections I then wordsmith a little to clarify what they contain.

Documentation: promote the tutorial to the top, and clarify what each topic, how-to, reference contains

---

documentation/topics/development/error-handling.md

Fixes a simple typo in closing `"` in the docs.

Fix typo in closing `"`

---

documentation/dsls/DSL-Ash.Notifier.PubSub.md
lib/ash/query/aggregate.ex

Just same thing repeated twice. Maybe there was something else in mind for the second item.

chore: remove repeat of the same type in Aggregate opts schema

---

test/policy/complex_test.exs
test/support/policy_complex/resources/post.ex

Have an issue with usage of a calculation in a policy expression. The calculation is an expression one and references actor through `^actor(:id)`. The problem that I see is that actor/context does not propagate to calculation expression.
Two reasons (solving either of them should fix the issue, but I don't know what would be appropriate):
a) Calculation context is not filled.
b) `Ash.Expr.fill_template` does not go into `Ash.Query.Ref`.
To demonstrate using the test example, this works:
```elixir
policy action(:erase) do
authorize_if expr(id == ^context(:post_id) and author_id == ^actor(:id))
end
```
But this does not:
```elixir
policy action(:erase) do
authorize_if expr(has_context)
end
calculate :has_context, :boolean, expr(id == ^context(:post_id) and author_id == ^actor(:id))
```

tests: test propagation of context to calculation in policy expression

---

lib/ash/type/enum.ex
test/type/enum_test.exs

When using a custom `Ash.Type.Enum` type, make sure `values/0` returns the values in the same order as defined on the type.
I'm showing the values in a select input and noticed the order changed randomly. This seems to be caused by converting the values to a map (for which the order of keys is not predictable).
I decided to keep the map (instead of replacing it with a keyword list) to keep label/description lookups performant.

fix: maintain order of enum values

---

documentation/dsls/DSL-Ash.Notifier.PubSub.md
lib/ash/notifier/pub_sub/pub_sub.ex

it sends,  %{topic: (topic), event: (event), payload: (notification)},
not  %{topic: (topic), event: (event), notification: (notification)}

fix documentation for broadcast_type: :broadcast

---

lib/ash/action_input.ex
test/action_input_test.exs

Also fixes a bug where actions were not correctly validated, but since it used to raise a `KeyError` and now raises an
`Ash.Error.Invalid.NoSuchAction` it's probably fine.

chore: Tidy up `Ash.ActionInput` by adding doctest examples.

---

lib/ash/query/function/string_join.ex

Removes the duplicate arg `[{:array, :ci_string}, :ci_string]`

Remove duplicate args

---

lib/ash/filter/filter.ex

This PR resolves #1953.
I found that `Ash.Query.Calculation.from_resource_calculation/3` can succeed even when the calculation does not belong to the given resource.
https://github.com/nallwhy/ash/blob/8d9b53d4e726bdcc7cab69978b2ad50c7a87467c/lib/ash/query/calculation.ex#L199
To prevent similar bugs in the future, it might be worth reconsidering the current behavior where calculations are allowed to pass without verification.

Fix filtering with aggregates refers calculation error

---

lib/ash/resource/actions/action/action.ex
lib/ash/resource/actions/action/implementation.ex

Had some difficulty determining the implementation of the module that a generic action's `run` function takes so updating the docs to hopefully help someone else out
Could add a generator, taking inspiration from https://github.com/ash-project/ash/pull/1940, but unsure how useful that would be

docs: Generic action implementation

---

lib/ash/generator/generator.ex
test/generator/generator_test.exs

Hello!
1. New function clause for `Ash.Generator.generate\1` to call `Ash.update!\1` on changesets of action type `:update`.
2. Added test for generator example using :update action on a parent resource.
3. Documentation example for this use-case.

Fix: Allow update action types in Ash.Generator.generate

---

lib/ash/changeset/changeset.ex

I figured out `manage_relationship_opts` and `run_atomic_change` public not because you want them as public interface for other developers to use but because there are other Ash modules that need to call them for internal implementation details. So marking them with `@doc false` as they show up on hexdocs which is confusing.
However, there are two more functions:
1. `set_on_upsert` 
2. `handle_params`
which looks like an internal public function but I'm not sure of the intent of the authors. If the authors could clarify if they intend to make these two publicly available api, I can write the docs or otherwise, mark them with `@doc false`.

Set doc false to internal public functions

---

lib/ash/sort/sort.ex

This fixes a bug where sorting by aggregates whose `field` is not an attribute (i.e. aggregate or a calculation) would cause a crash.
```
[error] ** (UndefinedFunctionError) function nil.embedded?/0 is undefined
nil.embedded?()
(ash 3.5.4) lib/ash/sort/sort.ex:428: Ash.Sort.do_type_sortable?/3
(ash 3.5.4) lib/ash/sort/sort.ex:251: Ash.Sort.get_field/5
(ash 3.5.4) lib/ash/sort/sort.ex:204: Ash.Sort.parse_sort/4
(ash 3.5.4) lib/ash/sort/sort.ex:111: anonymous fn/4 in Ash.Sort.parse_input/3
(elixir 1.18.3) lib/enum.ex:4968: Enumerable.List.reduce/3
(elixir 1.18.3) lib/enum.ex:2600: Enum.reduce_while/3
(ash 3.5.4) lib/ash/sort/sort.ex:110: Ash.Sort.parse_input/3
(ash 3.5.4) lib/ash/query/query.ex:455: Ash.Query.sort_input/3
```

Fix crash when sorting by aggregates with non-attribute field

---

lib/ash/code_interface.ex

This change causes a bunch of "no such input `id`" test failures.  I'm considering filtering those out of the params before passing them into the action, but this would be a change of behaviour so I'm not sure what the correct thing to do is here.

fix(CodeInterface): logic error in `get_by` code interfaces.

---

CHANGELOG.md
documentation/2.0-CHANGELOG.md
documentation/dsls/DSL-Ash.Policy.Authorizer.md
documentation/dsls/DSL-Ash.Resource.md
documentation/topics/actions/update-actions.md
documentation/topics/development/upgrading-to-3.0.md
documentation/topics/resources/code-interfaces.md
documentation/topics/security/actors-and-authorization.md
documentation/topics/security/policies.md
lib/ash.ex
lib/ash/action_input.ex
lib/ash/actions/destroy/bulk.ex
lib/ash/actions/update/bulk.ex
lib/ash/error/query/no_such_field.ex
lib/ash/filter/filter.ex
lib/ash/generator/generator.ex
lib/ash/helpers.ex
lib/ash/plug_helpers.ex
lib/ash/policy/authorizer/authorizer.ex
lib/ash/query/query.ex
lib/ash/resource/actions/create.ex
lib/ash/type/type.ex
test/actions/create_test.exs
test/uuid_v7_test.exs

Hi! I'm using [codespell](https://github.com/codespell-project/codespell) for checking misspellings/typos in docs and/or comments found in this repo. I ignored words such as `dont` (`don't`), etc.

Update misspellings/typos on docs and comments

---

lib/ash/generator/generator.ex
test/generator/generator_test.exs

Without this change, the next line raises an error:
```
** (KeyError) key :arguments not found in: nil
If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
```
Putting this in a PR for a quick once-over, in case there's an established pattern for doing this that I just missed.

chore: Raise an `ArgumentError` when generating a changeset using a non-existent action

---

lib/ash/generator/generator.ex

Simple fix to documentation after [conferring with @zachdaniel](https://discord.com/channels/711271361523351632/1364820978160500797) on Discord.

docs: Fix a bad copy-paste mixing up `changeset_generator/3` and `seed_generator/2` documentation

---

documentation/topics/security/policies.md

I noticed that my starter app config.exs was already declaring this option but with a trailing `?`.
Side note: the note seems fair enough about it not becoming `true` by default until 4.0, even though my starter app was already overriding that default to true.

doc: add ? to allow_forbidden_field_for_relationships_by_default

---

lib/ash/actions/update/bulk.ex

Having the :cont there lead to it breaking [here](https://github.com/ash-project/ash/blob/fafa5b4f9f8378c021668d53cf4e3a98d40f0a16/lib/ash/actions/update/bulk.ex#L3013-L3014)

fix: only return the changeset

---

lib/ash/actions/read/read.ex

#1988 
I did not added this to:
```
defp run_query(
%{action: %{manual: {mod, opts}}} = query,
data_layer_query,
context,
load_attributes?
)
```
FYI

enhancement: Skip reading query for filter false

---

documentation/tutorials/get-started.md

Pipe shorthand is not allowed immediately after a match expression in IEx.

docs: fix pipe shorthand error

---

lib/ash/resource/calculation/calculation.ex

I got bitten by this, and had to check the doc for calculations to figure that the second argument is the context. So I though I'd fix it :)

Calculation doc: mention the context argument

---

lib/ash/notifier/pub_sub/pub_sub.ex

Not sure if it fixes a bug that might be present, but it does fix a symptom. Kept seeing this error:
```elixir
* ** (KeyError) key :topic not found in: %Ash.Notifier.Notification{
resource: MyApp.Accounts.User,
domain: MyApp.Accounts,
action: %Ash.Resource.Actions.Update{
name: :update,
primary?: true,
description: nil,
error_handler: nil,
accept: [:email, :role, :first_name, :last_name, :company_id, :depot_id],
require_attributes: [],
allow_nil_input: [],
skip_unknown_inputs: [],
manual: nil,
manual?: false,
require_atomic?: false,
atomic_upgrade?: false,
atomic_upgrade_with: nil,
action_select: nil,
notifiers: [],
atomics: [],
delay_global_validations?: false,
skip_global_validations?: false,
arguments: [],
changes: [],
reject: [],
metadata: [],
transaction?: true,
touches_resources: …
```

only print topic if present

---

lib/ash/actions/helpers.ex

This PR resolves #2026.
Regarding testing: It seemed difficult to write a specific test for this bug using `Ash.DataLayer.Ets`, so I haven't added one.
I also noticed that `notifications` are prepended to a list in related code. Should their order also be corrected?

Fix batch order of bulk_create

---

lib/ash/type/tuple.ex

When reading this page I could not figure out where to put the `fileds`. This quick change aims to help with this.
- N/A Bug fixes include regression tests
- N/A Chores
- N/A Features include unit/acceptance tests
- N/A Refactoring
- N/A Update dependencies

docs: Make the tuple type constrains fields example more explicit

---

lib/ash/domain/igniter.ex
test/resource/igniter_test.exs

Fixes issue with add_new_code_interface/5 where the `define` would be put in a do block outside the resources block.

fix: add_new_code_interface/5 when do block occurs after resource

---

lib/ash/generator/generator.ex
test/generator/generator_test.exs

fix: make sure after_action is called in generate_many

---

lib/ash/type/tuple.ex

The Tuple type had three bugs:
* In dump_to_native the original tuple `value` was used instead of the tuple converted to a list. This caused Elixir to complain that Tuple doesn't have Enumerable implemented when attempting to zip it.
* In dump_to_native Enum.zip_with was used, expecting constraints[:fields] to be a function. This patch changes that to Enum.zip so it properly zips up the tuple-to-list with the :fields constraints.
* In cast_stored we were returning the tuple, instead of {:ok, tuple} causing downstream to fail since it expected an {:ok, value} structure.
I'm not sure where to add tests for this, would love some guidance there :)

fix: Tuple loader and serializer

---

lib/ash/query/function/ago.ex
lib/ash/query/function/date_add.ex
lib/ash/query/function/datetime_add.ex
lib/ash/query/function/from_now.ex
lib/ash/query/function/minus.ex
lib/ash/query/operator/basic.ex
lib/ash/type/duration.ex
lib/ash/type/type.ex
test/expr_test.exs
test/query/function/ago_test.exs
test/query/function/date_add_test.exs
test/query/function/datetime_add_test.exs
test/query/function/from_now_test.exs
test/type/duration_test.exs

Adds Ash.Type.Duration which is an Elixir Duration, shortname: :duration (also :duration in Ecto). The precision inherent in the interval is maintained. 
The idea is here is to allow Durations to be ash attributes persisted in the chosen DataLayer, noting that Ash has some existing support for durations by combining attributes of :duration_name and :integer type. 
Given that Elixir DateTime.shift, etc can be used with :duration and Comp.compare is implemented (using to_timeout such that durations are compared based on their total magnitude) I'm not sure whether Ash.Query.Function such as Ago, Date_Add, From_Now are needed.
- [ ✔️] Features include unit/acceptance tests

feat: duration

---

lib/ash/reactor/dsl/bulk_update.ex
lib/ash/reactor/steps/bulk_create_step.ex
lib/ash/reactor/steps/bulk_update_step.ex
test/reactor/bulk_update_test.exs

This was causing a name clash because `Ash.Expr` and the DSL are trying to define a function/macro called `actor/1`.
I've also added a test related to #2053 to verify that authorization works as expected.

fix(Ash.Reactor): Don't import `Ash.Expr` in the bulk update DSL.

---

lib/ash.ex
lib/ash/action_input.ex
lib/ash/actions/helpers.ex
lib/ash/actions/read/calculations.ex
lib/ash/can.ex
lib/ash/changeset/changeset.ex
lib/ash/code_interface.ex
lib/ash/query/query.ex
lib/ash/scope.ex
test/code_interface_test.exs
test/policy/simple_test.exs

This would likely need to be incrementally adopted in various places, and the first place would be in `AshAuthentication`. We would likely make it an option in the `ash_authentication_live_session`, to take a `scope`, and expect that scope to define a function like `from_conn/1`. (or something like that)

improvement: add `Ash.Scope` for converting a scope to options

---

lib/ash.ex
test/ash_test.exs

This PR fixes following errors.
`{:error, %Spark.Options.ValidationError{message: "unknown options [:context], valid options are: [:args, :refs, :actor, :scope, :tenant, :authorize?, :tracer, :record, :data_layer?, :reuse_values?, :domain]", value: %{}, key: :context, __exception__: true, keys_path: []}}`
`{:error, %Spark.Options.ValidationError{message: "invalid value for :authorize? option: expected boolean, got: nil", value: nil, key: :authorize?, __exception__: true, keys_path: []}}`

Fix Ash.calculate/2 with opts

---

documentation/tutorials/get-started.md

+ change code type from bash to elixir for consistent highlighting (with `bash` the comment was rendered the same way as the command itself)

Fix typo in get started docs

---

.github/workflows/ash-ci.yml

- Add `postgres-image` input parameter to allow specifying custom PostgreSQL Docker images
- Maintain backward compatibility by falling back to default `postgres:version` format when custom image is not provided
This enables testing with:
- PostGIS images (`postgis/postgis:15-3.3`)
- pgvector images (`pgvector/pgvector:pg15`)
- Alpine variants (`postgres:15-alpine`) 
- Custom PostgreSQL builds
- Specific vendor distributions

feat: add support for custom postgres image in CI workflow

---

lib/ash/type/string.ex
test/type/ci_string_test.exs

fix: add clause in Ash.Type.String.match/1 to handle the OTP 28 regex tuples

fix: add clause in Ash.Type.String.match/1 to handle the OTP 28 regex tuples

---

lib/ash/query/query.ex

I encountered this issue in a project where a combination query referenced a relationship, and it was searching in the `public` schema. This changed fixed it.

fix: set_tenant on combination query

---

lib/ash/actions/read/calculations.ex
test/calculations/calculation_test.exs

When loading multiple calculations that depend on nested relationships with no_attributes?: true, the rewrite system was constructing relationship traversal paths in reverse order, causing KeyError when trying to access relationships that don't exist on the current record.
The issue occurred in get_rewrites/4 where relationship names were being appended to paths instead of prepended, creating paths like [{:rel, :grandparent}, {:rel, :parent}] instead of the correct [{:rel, :parent}, {:rel, :grandparent}].
This caused the system to try accessing :grandparent directly on Child records instead of traversing Child → Parent → Grandparent.
Fixed by changing path construction from append to prepend:
- `path ++ [{:rel, name}]` → `[{:rel, name} | path]`
This ensures rewrite paths match actual …

fix(calculations): correct path construction order for nested relationship rewrites

---

lib/ash/changeset/changeset.ex

I was looking into the docs for `change manage_relationship` -> `:unrelate` functionality, and it referenced a function called `remove_from_relationship/3` which doesn't seem to exist anywhere. 
If it does exist and I just can't find it, I'm happy to document it!

docs: Remove reference to non-existant function `remove_from_relationship/3`

---

lib/ash/policy/check/built_in_checks.ex

docs: Fix syntax error in `Ash.Policy.Check.Builtins.changing_attributes` example

---

test/embedded_resource_test.exs

These tests check that change-tracking in changesets works as expected for changes to attributes that are embedded resources.
We are tracking down a strange bug somewhere in Ash or AshPaperTrail, and these tests imply that the issue is not in Ash, but thought it would be worthwhile to add them to the test suite.

tests: add change-tracking tests for embedded attributes

---

test/resource/actions/update_test.exs

Given a resource with attributes defined as
```elixir
attributes do
...
attribute :oban_job_id, :integer
end
```
and an update action defined as
```elixir
update :set_oban_job_id do
argument :job_id, allow_nil?: false
change atomic_update(:oban_job_id, expr(^arg(:job_id)))
end
```
alongside a code interface like
```elixir
define :set_oban_job_id, action: :set_oban_job_id, args: [:job_id]
```
running the `Resource.set_oban_job_id(resource, 123)` results in:
```
Invalid Error
* No such input `oban_job_id` for action MyApp.Products.Product.set_oban_job_id
The attribute exists on MyApp.Products.Product, but is not accepted by MyApp.Products.Product.set_oban_job_id
Perhaps you meant to add it to the accept list for MyApp.Products.Product.set_oban_job_id?
Valid Inputs:
* job_id
```
Changing …

test: add tests for updates with argument-based changes

---

lib/ash.ex

add missing types to Ash.load typespec

---

documentation/dsls/DSL-Ash.Resource.md
lib/ash/resource/dsl.ex

This PR replaces the example
```
validate at_least_one_of_present([:first_name, :last_name])
```
with 
```
validate present([:first_name, :last_name], at_least: 1)
```
I was confused because I tried to use `at_least_one_of_present` from the example, and my editor refused to autocomplete. It seems that it doesn't exist and (AFAICT from search the history) has never existed?

Replace inexistent at_least_one_of_present in validation examples

---

lib/mix/tasks/ash.extend.ex

Before:
```
Issues:
* Could not determine whether Elixir.Tunez.Music.Artist is an `Ash.Resource` or an `Ash.Domain`.
```
After:
```
Issues:
* Could not determine whether Tunez.Music.Artist is an `Ash.Resource` or an `Ash.Domain`.
```

chore: Remove `Elixir.` from module name printed in Igniter error message

---

lib/ash/action_input.ex
lib/ash/changeset/changeset.ex
lib/ash/query/query.ex
lib/ash/subject.ex
test/subject_test.exs

- Add support for `prepend?` option to Changeset, ActionInput, and Query hooks.  Except for `Ash.Query.after_action` which uses `@read_action_after_action_hooks_in_order?`
- Add transaction hooks to `Ash.Subject` since Changeset, ActionInput, and Query now all support them.
- Update all functions to delegate to the subject type module function
- Align type specs with subject type module types
- Update `get_argument/3` to only return the default value when `:error` is returned from `fetch_argument/2`
- Add `Ash.ActionInput.delete_argument/3`
- Add `Ash.Changeset.fetch_attribute/2`
- Add `Ash.Changeset.fetch_data/2`
- Add `Ash.Changeset.fetch_argument_or_attribute/2`
- Update `Ash.Query.fetch_argument/2` to first call `Ash.Query.new(query)` like other functions to ensure the subject is a …

improvement: Add prepend? opt to hooks and Ash.Subject transaction hooks

---

lib/ash.ex
test/actions/stream_test.exs

- Revert 7e34bbd change that updated Ash @global_opts `authorize?` to only accept boolean.
fixes #2224
All existing tests are passing

fix: allow Ash @global_opts authorize? to accept boolean or nil

---

lib/mix/tasks/gen/ash.gen.resource.ex
test/mix/tasks/ash.gen.resource_test.exs

feat: Add array modifier to `ash.gen.resource`

---

README.md
documentation/dsls/DSL-Ash.Resource.md
documentation/topics/reference/expressions.md
lib/ash/actions/managed_relationships.ex
lib/ash/data_layer/ets/ets.ex
lib/ash/domain/domain.ex
lib/ash/filter/runtime.ex
lib/ash/generator/generator.ex
lib/ash/query/function/get_path.ex
lib/ash/resource/identity.ex
lib/ash/scope.ex
test/actions/bulk/bulk_create_manual_test.exs
test/ash_test.exs
test/resource/require_valid_arguments_in_code_interface_test.exs
test/support/policy_rbac/checks/role_checks.ex
usage-rules.md

Found via `codespell -S logos,deps,CHANGELOG.md -L doesnt,cant,filetest,wont,fo,nd,anc,marge,zar` and `typos --hidden --format brief`

docs: fix typos

---

lib/ash/domain/info.ex
lib/ash/info.ex
lib/ash/resource/info.ex
lib/mix/tasks/helpers.ex
test/domain/info_test.exs
test/info_test.exs
test/resource/info_test.exs

feat: introduce extension introspection functions on Ash.*.Info

---

usage-rules.md

add link to polymorphic relationships guide

usage_rules: minor tweaks

---

lib/ash/type/type.ex
test/calculations/calculation_with_union_type.exs

This fixes that load statements for calculations on embedded resources in a union type doesn't crash, when the value in the union type is currently a primitive.
In order to verify the bug exists:
- Comment out the new default implementations in type.ex
- Run the tests

fix: add default impl for rewrite/3 & get_rewrites/4 for Ash.Type.

---

lib/ash/resource/change/get_and_lock.ex
lib/ash/resource/change/get_and_lock_for_update.ex

My domain uses `require_actor? true`, which means I'm actually unable to use these changes right now, since they don't pass the actor to `Ash.get`

pass actor: nil to ash.get in get_and_lock_for_update

---

lib/ash/changeset/changeset.ex

Using change_attribute/2 in a before_action hook triggers a warning that the changeset has already been validated, suggests a new pattern that isn't compatible with the before_action hook. This confused me at first when copying the patterns from the documentation, so I suggest using force_change_attribute in the examples instead, as well as adding a small note about why.

Update before_action docs to use force_change_attribute/2

---

lib/ash/actions/read/read.ex
test/actions/pagination_test.exs
test/test_helper.exs

Fixes pagination counts not respecting `:disable_async?` config.

fix: respect disable_async config during pagination count

---

CHANGELOG.md
lib/ash/domain/interface.ex
test/domain/domain_test.exs

Improves the error handling when the `use Ash.Domain` macro is invoked multiple times within the same module.
* Enhanced the `__using__` macro in `Ash.Domain.Interface` to detect and raise a `CompileError` with a descriptive message if `use Ash.Domain` is called more than once in the same module. The error points to the exact line of the duplicate invocation.
* Added tracking attribute to count macros invocation 
* Added tests in `domain_test.exs` to ensure a `CompileError` is raised on double invocation of `use Ash.Domain`.

Add CompileError on duplicate Ash.Domain use

---

lib/ash/type/atom.ex
test/type/atom_test.exs
test/type/type_test.exs

The `unsafe_to_atom?` constraint was not used by the `Ash.Type.Atom.cast_stored/2` function so when casting a stored string to an atom it would throw errors. 
I've added a test that demonstrates the problem. The test uses the ETS directly to insert a non-existing atom. I've put this in a new test module specifically for Atom type tests.

Fix bug when casting a non-existing atom from datalayer when `unsafe_to_atom?` is set

---

lib/ash/policy/authorizer/authorizer.ex

I was getting this stacktrace:
```
* ** (KeyError) key :subject not found in: false
If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
(ash 3.5.34) lib/ash/policy/authorizer/authorizer.ex:1568: Ash.Policy.Authorizer.log_successful_policy_breakdown/2
(ash 3.5.34) lib/ash/policy/authorizer/authorizer.ex:1556: Ash.Policy.Authorizer.check_result/1
(ash 3.5.34) lib/ash/can.ex:664: anonymous fn/5 in Ash.Can.run_check/4
(ash 3.5.34) lib/ash/actions/read/read.ex:3462: anonymous fn/2 in Ash.Actions.Read.run_authorize_results/2
(elixir 1.18.4) lib/enum.ex:4968: Enumerable.List.reduce/3
(elixir 1.18.4) lib/enum.ex:2600: Enum.reduce_while/3
(ash 3.5.34) lib/ash/actions/read/read.ex:3461: Ash.Actions.Read.run_authorize_results/2
(ash 3.5.34) …
```

fix variable swapping in authorizer reducer

---

lib/ash/changeset/changeset.ex
test/resource/upsert_test.exs

[The docs for upserts](https://hexdocs.pm/ash/create-actions.html#upserts) say to use `upsert_condition expr(user_id == ^actor(:id))` to restrict access to updating resources to the owner of the resource, as the create policy will be used and not the update policy when an upsert occurs.
When I attempted to do something similar I would consistently get an `Ash.Error.Changes.ActionRequiresActor` error, despite always passing in an `actor`. Upon digging in, the issue is that `filter` attempts to expand the `upsert_condition` expression and replace the `{:_actor, field}` placeholders immediately. However `Ash.Changeset.for_create` isn't populating the context with `actor`, I suspect because `do_for_action` is responsible for that logic.
I was unsure the best approach and opted for the …

fix: Allow ^actor() in upsert_condition

---

lib/ash/actions/update/update.ex

Ensure that changesets for manual update actions get default values applied before handing up to manual update module's `update/3`

fix: add default values to manual action changesets

---

lib/ash/type/enum.ex

Mention that Ash.Type.Enum.label/1 generates a label based on the value if no label was defined, rather than returning nil.

docs: clarify enum labels

---

lib/ash/actions/create/create.ex
test/actions/create_test.exs

following up on https://elixirforum.com/t/anybody-working-on-or-interested-in-ash-mongo-ash-datalayer-for-mongodb/72189/4
when creating a resource directly without creating a changeset first, upsert_fields is not passed to the datalayer:  (new test case in commit 72b161d)
```
Ash.create!(
Post,
%{
title: "foo",
contents: "test"
},
upsert?: true,
upsert_identity: :unique_title,
upsert_fields: [:contents] # this gets lost
)
```
the fix in commit c7e6376 is my best guess on how to fix it (and all tests pass) but:
- I am not 100% confident that this is the right place or way to do it
- there might be a different helper that I haven't seen that should be called
=> i.e. I understand what I am doing, but not why upsert_fields need to be in the changeset, when they are already in the opts
=> I …

Runtime upsert_fields option is not passed to data layer in certain cases

---

lib/ash/error/invalid/no_such_input.ex

`opts[:inputs]` is expected to be a list at line 12.
It makes some calls to exception/1 crash, which end up showing a cryptic error msg instead of the exception.

fix: avoid crashing on new exception

---

lib/ash/resource/verifiers/verify_actions_atomic.ex

Fixes https://github.com/ash-project/ash/issues/2326

Fix usage of Ash.Notifier.requires_original_data/2 in VerifyActionsAtomic

---

documentation/topics/advanced/reactor.md
lib/ash/action_input.ex
test/actions/generic_actions_test.exs

Generic action after_action, after_transaction and around_transaction hooks were not correctly validating return types for generic actions with no return type.

fix: Incorrect return type checking for generic action hooks

---

lib/ash/actions/create/bulk.ex
lib/ash/data_layer/data_layer.ex
test/actions/bulk/bulk_create_test.exs

extra context 
* https://github.com/ash-project/ash_paper_trail/pull/205
* https://github.com/ash-project/ash_postgres/pull/626

handle return_skipped_upsert? in bulk creates

---

lib/ash/actions/read/read.ex
test/actions/read_test.exs

Fixes issues where the after_transaction callbacks are being passed arguments that don't match the typespec of `t:Ash.Query.after_transaction_fun/0`. 

fix: Ash.Query.after_transaction result argument issues.

---

lib/ash/actions/bulk_manual_action_helpers.ex
lib/ash/actions/create/bulk.ex
lib/ash/actions/destroy/bulk.ex
lib/ash/actions/helpers.ex
lib/ash/actions/update/bulk.ex
lib/ash/data_layer/ets/ets.ex
lib/ash/data_layer/mnesia/mnesia.ex
lib/ash/data_layer/simple/simple.ex
test/actions/bulk/bulk_create_manual_test.exs
test/actions/bulk/bulk_create_test.exs
test/actions/bulk/bulk_destroy_manual_test.exs
test/actions/bulk/bulk_destroy_test.exs
test/actions/bulk/bulk_update_manual_test.exs

and added some convenience helpers
As requested here, https://github.com/ash-project/ash/pull/2353#issuecomment-3374737225
its a bit more extensive, added bulk_destroy whilst at it. But tried to keep it to a minimum with some extra tests

fix: extended context collision prevention to all bulk operation types
