lib/ash/data_layer/ets.ex

update docs for ETS

---

lib/ash/filter/filter.ex

Context
---
* Creates private guard for checking against nil/empty values
* Moves variable assignment outside of function heads when not required for differentiating pattern matching
* Adds helpers for parsing attributes and relationships

refactor(filter, inspect): adds helpers and guards to clarify code

---

lib/ash.ex
lib/ash/actions/destroy.ex
lib/ash/actions/update.ex
lib/ash/api/interface.ex
lib/ash/options_helpers.ex

feat: use option schemas in the interface

---

lib/ash/type/type.ex
test/actions/create_test.exs

improvement: add `date` support

---

.formatter.exs
.github/workflows/elixir.yml
documentation/topics/aggregates.md
documentation/topics/calculations.md
lib/ash.ex
lib/ash/actions/read.ex
lib/ash/calculation.ex
lib/ash/options_helpers.ex
lib/ash/query/calculation.ex
lib/ash/query/query.ex
lib/ash/resource.ex
lib/ash/resource/aggregate.ex
lib/ash/resource/attribute.ex
lib/ash/resource/calculation.ex
lib/ash/resource/dsl.ex
lib/ash/resource/schema.ex
lib/ash/type/atom.ex
lib/ash/type/map.ex
lib/ash/type/type.ex
mix.exs
test/ash_test.exs
test/calculation_test.exs

feat: initial calculation support

---

.formatter.exs
lib/ash/api/api.ex
lib/ash/resource.ex
lib/ash/resource/dsl.ex
lib/ash/resource/identity.ex
lib/ash/resource/transformers/cache_primary_key.ex
test/actions/read_test.exs
test/calculation_test.exs

feat: add identities, to enhance `get` calls

---

lib/ash/actions/read.ex
lib/ash/actions/side_load.ex
lib/ash/api/api.ex
lib/ash/data_layer/data_layer.ex
lib/ash/data_layer/delegate.ex
lib/ash/engine/request.ex
lib/ash/filter/filter.ex
lib/ash/query/query.ex
lib/ash/resource/dsl.ex
test/actions/side_load_test.exs
test/filter/filter_interaction_test.exs

Specifically, this allows us to behave correctly when loading
relationships w/ a limit or offset

feat: support inner lateral joins

---

README.md

docs: elixir syntax highlighting in README.md

---

.formatter.exs
CHANGELOG.md
documentation/introduction/getting_started.md
lib/ash/actions/create.ex
lib/ash/actions/read.ex
lib/ash/actions/side_load.ex
lib/ash/actions/update.ex
lib/ash/changeset/changeset.ex
lib/ash/data_layer/delegate.ex
lib/ash/engine/request.ex
lib/ash/error/query/aggregates_not_supported.ex
lib/ash/error/query/unsupported_predicate.ex
lib/ash/filter/filter.ex
lib/ash/options_helpers.ex
lib/ash/query/aggregate.ex
lib/ash/query/query.ex
lib/ash/resource.ex
lib/ash/resource/actions/create.ex
lib/ash/resource/actions/update.ex
lib/ash/resource/change/builtins.ex
lib/ash/resource/change/change.ex
lib/ash/resource/change/relate_actor.ex
lib/ash/resource/dsl.ex
lib/ash/resource/validation.ex
test/actions/create_test.exs
test/actions/side_load_test.exs
test/actions/update_test.exs

feat: add changes to actions

---

.github/workflows/elixir.yml
lib/ash.ex
lib/ash/resource/identity.ex

fix: Fix identities

---

lib/ash/type/uuid.ex

fix: correct comment in UUID type

---

lib/ash/resource/actions/create.ex
lib/ash/resource/actions/destroy.ex
lib/ash/resource/actions/read.ex
lib/ash/resource/actions/shared_options.ex
lib/ash/resource/actions/update.ex
lib/ash/resource/relationships/belongs_to.ex
lib/ash/resource/relationships/has_many.ex
lib/ash/resource/relationships/has_one.ex
lib/ash/resource/relationships/many_to_many.ex
lib/ash/resource/relationships/shared_options.ex

added description to actions and relationships

---

lib/ash/resource/aggregate.ex
lib/ash/resource/calculation/calculation.ex
lib/ash/resource/identity.ex
lib/ash/resource/validation.ex
test/resource/actions/read_test.exs
test/resource/aggregates_test.exs
test/resource/calculations_test.exs
test/resource/identities_test.exs
test/resource/validations_test.exs

feat: added description for missing resources

---

changeset_test.exs
lib/ash/changeset/changeset.ex
lib/ash/resource.ex
test/changeset/changeset_test.exs

- Just adding some tests fo `Changeset` and fix small typos.

test: add changeset_test

---

lib/ash/api/transformers/validate_many_to_many_join_attributes.ex
lib/ash/api/transformers/validate_relationship_attributes.ex
lib/ash/dsl/extension.ex
lib/ash/error/dsl/dsl_error.ex
lib/ash/resource/transformers/belongs_to_attribute.ex
lib/ash/resource/transformers/cache_primary_key.ex
lib/ash/resource/transformers/set_primary_actions.ex
lib/ash/resource/transformers/validate_action_types_supported.ex
test/resource/actions/actions_test.exs
test/resource/actions/create_test.exs
test/resource/actions/destroy_test.exs
test/resource/actions/read_test.exs
test/resource/actions/update_test.exs
test/resource/attributes_test.exs
test/resource/relationships/belongs_to_test.exs
test/resource/relationships/has_many_test.exs
test/resource/relationships/has_one_test.exs
test/resource/relationships/many_to_many_test.exs

Module name errors

---

lib/ash/actions/relationships.ex
lib/ash/actions/update.ex
lib/ash/dsl/extension.ex
lib/ash/filter/filter.ex
lib/ash/filter/runtime.ex
lib/ash/query/expression.ex
lib/ash/query/function/function.ex
lib/ash/query/not.ex
lib/ash/query/operator/eq.ex
lib/ash/query/operator/greater_than.ex
lib/ash/query/operator/greater_than_or_equal.ex
lib/ash/query/operator/in.ex
lib/ash/query/operator/is_nil.ex
lib/ash/query/operator/less_than.ex
lib/ash/query/operator/less_than_or_equal.ex
lib/ash/query/operator/operator.ex
lib/ash/query/ref.ex
lib/mix/tasks/ash.formatter.ex
lib/sat_solver.ex
mix.exs
test/changeset/changeset_test.exs

Some small module name updates, and fixes for elixir 1.11 compiler warnings.

Module updates

---

.formatter.exs
coveralls.json
documentation/topics/pagination.md
lib/ash.ex
lib/ash/actions/read.ex
lib/ash/actions/relationships.ex
lib/ash/actions/side_load.ex
lib/ash/actions/sort.ex
lib/ash/api/api.ex
lib/ash/api/interface.ex
lib/ash/data_layer/data_layer.ex
lib/ash/data_layer/ets.ex
lib/ash/engine/request.ex
lib/ash/error/invalid/limit_required.ex
lib/ash/error/invalid/multiple_results.ex
lib/ash/error/invalid/pagination_required.ex
lib/ash/filter/filter.ex
lib/ash/page/keyset.ex
lib/ash/page/offset.ex
lib/ash/query/operator/not_eq.ex
lib/ash/query/query.ex
lib/ash/resource/actions/read.ex
lib/ash/resource/dsl.ex
lib/ash/resource/schema.ex
lib/ash/resource/transformers/countable_actions.ex
mix.exs
test/actions/pagination_test.exs
test/ash/data_layer/ets_test.exs

~- [ ] Bug fixes include regression tests~

feat: Add pagination

---

lib/ash/api/api.ex

docs: Switch titles to match contents of paragraphs

---

documentation/topics/aggregates.md
documentation/topics/notifiers.md
lib/ash.ex
lib/ash/actions/create.ex
lib/ash/actions/destroy.ex
lib/ash/actions/relationships.ex
lib/ash/actions/update.ex
lib/ash/api/api.ex
lib/ash/api/interface.ex
lib/ash/changeset/changeset.ex
lib/ash/data_layer/data_layer.ex
lib/ash/engine/engine.ex
lib/ash/engine/request.ex
lib/ash/engine/request_handler.ex
lib/ash/engine/runner.ex
lib/ash/notifier/notification.ex
lib/ash/notifier/notifier.ex
lib/ash/page/keyset.ex
lib/ash/resource.ex
lib/ash/resource/transformers/set_primary_actions.ex
mix.exs
test/actions/create_test.exs
test/notifier_test.exs

feat: add notifiers

---

lib/ash/actions/relationships.ex
lib/ash/changeset/changeset.ex
lib/ash/engine/request.ex
test/actions/read_test.exs
test/changeset/changeset_test.exs

target issue #46 
this need a careful review.

feat: Optimize relashionship records replacement

---

README.md

update getting started link

---

lib/ash/resource.ex
lib/ash/resource/aggregate.ex
lib/ash/resource/attribute.ex
lib/ash/resource/calculation/calculation.ex
lib/ash/resource/relationships/belongs_to.ex
lib/ash/resource/relationships/has_many.ex
lib/ash/resource/relationships/has_one.ex
lib/ash/resource/relationships/many_to_many.ex
lib/ash/resource/relationships/shared_options.ex
lib/ash/resource/transformers/belongs_to_attribute.ex
lib/ash/resource/transformers/create_join_relationship.ex
test/resource/aggregates_test.exs
test/resource/attributes_test.exs
test/resource/calculations_test.exs
test/resource/relationships/belongs_to_test.exs
test/resource/relationships/has_many_test.exs
test/resource/relationships/has_one_test.exs
test/resource/relationships/many_to_many_test.exs

feat: Add property: private? for attributes, relationships, aggregates, and calculations

---

documentation/introduction/getting_started.md

getting started documentation improvements

getting started documentation improvements 

---

documentation/introduction/getting_started.md

switched id to uuid_primary_key for overall consistency with the sample app

switched id to uuid_primary_key for overall consistency with the sample app

---

documentation/introduction/getting_started.md
documentation/introduction/getting_started_phx.md
mix.exs

ash phoenix getting started

---

documentation/introduction/getting_started.md
documentation/introduction/getting_started_phx.md

- Updates to getting started docs

Updates to getting starting docs

---

lib/ash/type/binary.ex
lib/ash/type/type.ex

Add built in :binary type

---

documentation/introduction/getting_started.md

docs: Update getting_started.md

---

documentation/topics/calculations.md
lib/ash/dsl/extension.ex
lib/ash/resource/calculation/calculation.ex
lib/ash/resource/dsl.ex

Improve documentation for calculations
Add ability to "label" examples by passing a tuple instead of just a string.
Fix some minor typos

Documentation improvements and labeled examples

---

.formatter.exs
lib/ash/query/aggregate.ex
lib/ash/resource/aggregate.ex
lib/ash/resource/dsl.ex
test/resource/aggregates_test.exs

Issue: https://github.com/ash-project/ash/issues/184

improvement: add sum aggregate

---

README.md
documentation/topics/contexts_and_domains.md

docs: Minor doc changes

---

lib/ash/query/query.ex

This will make the Query docs easier to follow

docs: use full module name

---

.github/PULL_REQUEST_TEMPLATE.md

docs: Add documentation changes to GitHub template

---

documentation/introduction/getting_started_phx.md

docs: Add postgres adapter instruction to getting started doc

---

lib/ash/actions/load.ex
lib/ash/actions/read.ex
lib/ash/error/side_load/invalid_query.ex
lib/ash/error/side_load/no_such_relationship.ex
lib/ash/filter/filter.ex
lib/ash/filter/runtime.ex
lib/ash/query/aggregate.ex
lib/ash/query/query.ex
test/actions/load_test.exs
test/filter/filter_interaction_test.exs

Closes #235. I didn't scrutinize the naming very much, just did a quick regex replace wherever possible, manually overriding conflicts. If it looks good, :+1: but I'm also fine w/ nitpicks or shelving it for later. It just looked like some low-hanging fruit for me!

refactor: remove references to "side loading"

---

.github/PULL_REQUEST_TEMPLATE.md

Add more items to PR checklist

---

lib/ash/api/interface.ex

fix: ensure create functions generated by code_interface accept tenant in the opts list

Fix create code interface to correctly accept tenant in the opts list

---

lib/ash/api/interface.ex
lib/ash/changeset/changeset.ex
lib/ash/resource/validation/builtins.ex
lib/ash/resource/validation/compare.ex
lib/ash/resource/validation/present.ex
test/resource/validation/compare_test.exs

feat: added number validator supporting validation of arguments and attributes, all the standard validators are included i.e: greater_than, less_than, less_than_or_equal_to, greater_than_or_equal_to
feat: added two new functions in changeset, `&get_argument_or_attribute/2` and `&fetch_argument_or_change/2`
fix: give `present` validation access to arguments also, not just arguments
added some tests

feat: add compare validator

---

lib/ash/resource/validation/match.ex
lib/ash/resource/validation/one_of.ex
lib/ash/resource/validation/string_length.ex

fix: make remaining validations check arguments also

improvement: Update remaining builtin validators

---

lib/ash/resource/dsl.ex
lib/ash/resource/relationships/many_to_many.ex

Just a couple of typos and syntax issues

docs: Minor documentation tweaks

---

lib/ash/type/atom.ex
lib/ash/type/enum.ex

docs: Fix atom constraint documentation

---

lib/ash/type/atom.ex

Fix atom casting when empty string

---

lib/ash/type/atom.ex

Fix atom casting more

---

lib/ash/page/page.ex
lib/ash/resource/info.ex
test/resource/info_test.exs

feat(Ash.Resource.Info): add &public_field/2 helper

---

backers.md

docs: Update backers.md

---

.formatter.exs
CHANGELOG.md
lib/ash/actions/create.ex
lib/ash/actions/destroy.ex
lib/ash/actions/load.ex
lib/ash/actions/update.ex
lib/ash/api/api.ex
lib/ash/changeset/changeset.ex
lib/ash/dsl/transformer.ex
lib/ash/options_helpers.ex
lib/ash/resource/relationships/belongs_to.ex
lib/ash/resource/relationships/has_many.ex
lib/ash/resource/relationships/has_one.ex
lib/ash/resource/relationships/many_to_many.ex
lib/ash/resource/transformers/belongs_to_attribute.ex
lib/ash/resource/validation.ex
mix.exs
test/actions/validation_test.exs

chore: Bring over changes committed to master branch

---

lib/ash/query/operator/greater_than.ex
lib/ash/query/operator/less_than_or_equal.ex
lib/sat_solver.ex
test/filter/simplication_test.exs
test/support/helpers.ex

fix: use Date.add when using LessThanOrEqual with date value

---

documentation/topics/compile_times.md

documentation: fix compile_times.md

---

lib/ash/changeset/changeset.ex

fix: typo in changeset.ex

---

lib/ash/api/api.ex

fix: Fix typespecs in Ash.Api

---

lib/ash/resource/transformers/require_unique_action_names.ex
test/resource/require_unique_action_names_test.exs
test/support/flow.ex

fix: Enforce unique action names

---

lib/ash/type/time.ex
lib/ash/type/type.ex
test/type/time_test.exs

improvement: Add time type matching existing date type

---

lib/ash/type/date.ex

Mirror the changes added to the time type in #310 back to date type

fix: Handle date type cast_input with nil value

---

lib/ash/type/naive_datetime.ex
lib/ash/type/type.ex
test/type/naive_datetime_test.exs

Implement NaiveDateTime in the same style as Time and Date

improvement: implement NaiveDateTime type

---

lib/ash/registry/extensions/resource_validations/transformers/ensure_no_embeds.ex

Chore: Fix typo

---

lib/ash/resource/calculation/concat.ex

fix: Fix concat

---

lib/ash/resource/info.ex

Just acted as a proxy for Zach here hah. He fixed it, I just typed.

fix: fixed bug wher embedded resources would always provide defaults, not allowing you to declare your own (primary?) actions

---

.github/ISSUE_TEMPLATE/bug_report.md

Make it consistent with other headers.

Fix the "Runtime" formatting in the bug report template

---

lib/ash/policy/info.ex
test/policy/rbac_test.exs

I just did a quick test to make sure it returns true, but it doesn't cover many cases. I can add more if needed.

feat: add can?/4 policy utility

---

.formatter.exs
lib/ash/options_helpers.ex
lib/ash/resource/actions/shared_options.ex
lib/ash/resource/dsl.ex
lib/ash/resource/transformers/default_accept.ex
test/elixir_sense/plugin_test.exs
test/resource/actions/actions_test.exs

https://github.com/ash-project/ash/issues/249

Add accept_default option

---

lib/ash/resource/validation.ex

docs: Fix little documentation typo

---

documentation/tutorials/get-started.md

fix the path bug of adding tickets resource

docs: Update get-started.md

---

documentation/tutorials/get-started.md

docs: minor changes to getting started guide

---

documentation/topics/code-interface.md

docs: Little typo in documentation

---

documentation/tutorials/get-started.md

docs: change Api to Helpdesk.Support and add file comments

---

documentation/topics/expressions.md
lib/ash/filter/filter.ex
lib/ash/query/function/length.ex
test/filter/filter_test.exs

improvement: Implement length function

---

.formatter.exs
lib/ash/calculation.ex

fix(Ash.Calculation): fix return type for `load/3` callback.

---

documentation/tutorials/get-started.md

Docs: fixed file creation step in get-started

---

documentation/topics/calculations.md

docs: Missing calculation type in doco

---

lib/ash/api/diagram/diagram.ex
lib/ash/resource/change/relate_actor.ex
test/api/diagram_test.exs

Initial cut of generating ERDs in Mermaid from a given API. Other things to look at:
- show attrs
- show private attrs
- show private relships
- show calcs, aggs
- mix task to generate similar to flow chart

feature: generate mermaid entity relationship diagrams from a given api

---

README.md

docs: update contributor guide link

---

CHANGELOG.md
documentation/topics/calculations.md
documentation/topics/flows.md
documentation/topics/notifiers.md
documentation/topics/store-context-in-process.md
lib/ash/changeset/changeset.ex
lib/ash/data_layer/mnesia/mnesia.ex
lib/ash/engine/request.ex
lib/ash/error/changes/required.ex
lib/ash/error/error.ex
lib/ash/error/query/no_complex_sorts_with_keyset_pagination.ex
lib/ash/filter/filter.ex
lib/ash/filter/runtime.ex
lib/ash/notifier/notification.ex
lib/ash/query/function/function.ex
lib/ash/query/query.ex
lib/ash/registry/info.ex
lib/ash/type/type.ex
test/calculation_test.exs
test/generator/generator_test.exs
test/resource/resource_test.exs

docs: fix typos

---

lib/ash/engine/request.ex
lib/ash/filter/runtime.ex
lib/ash/policy/authorizer.ex
lib/ash/policy/filter_check.ex

fix: policy fixes from pair session

---

lib/ash/policy/info.ex
test/policy/rbac_test.exs

`Ash.Policy.can/4` and `Ash.Policy.can?/4` need to be able to accept a query/changeset in order to support complex reads, such as those w/ required arguments. This PR adds support to pass a query/changeset instead of an action/action name.
This is a re-submission of an earlier PR because I got a little too zealous with my git script to reset my fork/local copy to upstream. :sweat_smile:

improvement: allow passing query or changeset in can/can?/4

---

lib/mix/mermaid.ex
lib/mix/tasks/generate_er_diagrams.ex
lib/mix/tasks/generate_flow_charts.ex

- refactor: remove unused sibling_file fn
- refactor: extract mermaid helpers and simplify

refactor: simplify mermaid mix tasks

---

lib/ash/api/info/diagram.ex

- docs: fix typos in diagram doc, rename folder to match module
- chore: fix diagram formatting

docs: refactor diagram, fix doc typos and formatting

---

lib/ash/api/info/livebook.ex
lib/mix/tasks/generate_livebook.ex
test/api/livebook_test.exs
test/support/flow/org.ex
test/support/flow/user.ex

Basic Livebook generation and mix task.
Some refactoring required around utility functions, as the mermaid tasks are using too.

feat: basic livebook generator and mix task

---

documentation/tutorials/get-started.md

Added some missing pointer to which files need to be edited as well as
```
recompile()
```
to each shell section to dig this point in :)

docs: Update get started guide to be more beginner friendly

---

documentation/tutorials/philosophy.md

docs: Comment out editorial comments

---

lib/ash/resource/transformers/default_accept.ex
test/resource/actions/actions_test.exs

fix: destroy action types default to accepts []

---

lib/ash/policy/check/built_in_checks.ex

docs(policy): fix built_in_checks typo, formatting

---

lib/ash/policy/authorizer.ex

docs: fix typo

---

documentation/tutorials/extending-resources.md

I went through the tutorial and got some compiler errors/warnings, this is what I had to change to fix them.

docs: Update extending-resources.md

---

lib/ash/actions/create.ex
lib/ash/actions/destroy.ex
lib/ash/actions/read.ex

Signed-off-by: kernel-io <kernel-io@users.noreply.github.com>

fix: fix authorize? method

---

documentation/tutorials/extending-resources.md

docs: Remove double space and with

---

lib/ash/resource/validation/confirm.ex

fix: Use proper options in `confirm` change.

---

lib/ash/api/api.ex

improvement: add nil return type to api get/3, read_one/2 and read_one!/2

---

documentation/how_to/validate-changes.md
documentation/tutorials/extending-resources.md

Notices these while going through AshHQ making sure everything was rendering correctly. There will be a few more PRs to come for other Ash projects!

docs: Fix minor typos in guide headings

---

lib/ash/policy/authorizer.ex
lib/ash/policy/filter_check_with_context.ex
lib/ash/policy/info.ex

Mainly I just wanted to fix the broken link to the Policies guide (incorrectly linked to Flows) but then I spotted a few other things.

docs: Policy tweaks

---

documentation/topics/flows.md

Fixed copy/paste error on comment referring to the action atom.

docs: Update flows.md to fix copy/paste error of action atom

---

lib/ash/api/api.ex
lib/ash/error/invalid/page_requires_pagination.ex
test/actions/read_test.exs

Leaving the checklist here. Bit unsure how to test here. Aims to fix https://github.com/ash-project/ash/issues/505

improvement: Add error message when page is added but pagination is not enabled

---

documentation/topics/attributes.md
documentation/topics/constraints.md
lib/ash/resource/actions/argument.ex
lib/ash/resource/attribute.ex
lib/ash/type/type.ex

Introduces:
- attribute topic article
- constraints topic article
- improves attribute DSL documentation
- improves argument DSL documentation

docs: Attribute documentation topic

---

documentation/tutorials/get-started.md

Added example of how to write the Representative ID directly into the Ticket during Ticket creation. Based on https://discord.com/channels/711271361523351632/1073248091324551228/1073249825363075102

docs: Update "Get Started" guide with an example

---

lib/ash/query/query.ex
test/calculation_test.exs

I had this problem in my code, and passing the query argument made it work. I don't think this is 100% correct in this case. 
The added test is also not doing what I would expect it to. The calculation is not loaded and I don't know why.  Maybe this gives you enough information for a fix. Or if it is more involved, maybe you could give me a couple pointers. 
Thanks

test: pass in arguments to validation

---

documentation/topics/relationships.md

Introduces:
- improves relationships topic guide

docs: improve relationships topic guide

---

documentation/topics/policies.md

A rewrite of the Policies guide.
I've been bashing my head against policies for a few days now because I missed some of the fundamentals - the difference between simple and filter checks, which type is created when, and how `:unknown` values fit in. The info was kinda in the guide, but hidden away/really hard for me to wrap my head around - so I want to make it a lot clearer for future devs.
Please give it a good read and let me know if there are any technical issues - there might still be some holes in my understanding but I think I finally worked it all out!

docs: rewrite Policies guide to be clearer

---

lib/ash/plug_helpers.ex

improvement: add `update_actor` to `Ash.Plughelpers`

---

lib/ash/resource/change/builtins.ex
lib/ash/resource/change/set_attribute.ex

Adds [requested](https://discord.com/channels/711271361523351632/712035333432147989/1085967846632345682) option `set_when_nil?` to builtin change `set_attribute`, indicating that the change should only set the attribute when its current value is not `nil`.
Includes update of dependency `picosat_elixir` to `~> v0.2.3`.
*Note: Existing test suite passes, however this PR does not yet include additional docs/tests.*

improvement: add option `set_when_nil?` to builtin change `set_attribute`

---

lib/ash/plug_helpers.ex

improvement: add `{set,update,get}_context` to `Ash.PlugHelpers`

---

.github/workflows/ash-ci.yml
config/config.exs
lib/ash/actions/read.ex
lib/ash/flags.ex
lib/ash/query/query.ex

Add `read_uses_flow?` feature flag.

---

lib/ash/query/query.ex

remove deprecation warning on aggregate/5 in query.ex

---

lib/ash/policy/check/built_in_checks.ex
lib/ash/policy/check/relates_to_actor_via.ex
lib/ash/query/query.ex
lib/ash/resource/change/builtins.ex
lib/ash/resource/change/relate_actor.ex
test/policy/relates_to_actor_via_test.exs
test/resource/changes/relate_actor_test.exs

This allows relating a field of the actor to a resource
Rename relates_to_actor_via subfield opt to field

improvement: Add :field option to relate_actor change

---

lib/ash/resource/change/builtins.ex
test/resource/changes/set_new_attribute_test.exs

fix: Fix set_new_attribute by adding missing option to set_attribute

---

test/flow_test/branching_transaction_mapping_test.exs
test/flow_test/branching_transaction_no_record_test.exs
test/support/flow/flows/branching_transaction_mapping.ex
test/support/flow/flows/branching_transaction_no_record.ex
test/support/flow/flows/get_user_not_found_error.ex
test/support/flow/user.ex

Tests to debug this situation:
https://discord.com/channels/711271361523351632/1092520117977489418/1092520117977489418
tests are failing while they should pass.

test: tests for custom steps returning nil even when there is a right result

---

lib/ash/type/term.ex

improvement: Change storage type of Ash.Type.Term to :binary

---

lib/ash/resource/info.ex
test/resource/info_test.exs

feat: add `fields/1` and `public_fields/1` to Ash.Resource.Info

---

lib/ash/resource/interface.ex

"actor" term was duplicated and one of them was supposed to be "tracer"

Fix docs for code_interface generated help

---

lib/ash/flow/flow.ex

ensure add_tenant/1 checks the correct key

---

lib/ash/flow/executor/ash_engine.ex

fix: copy tenant to step on flow build

---

lib/ash/code_interface.ex

Part addition of a feature and part refactor/fix.
Main refactor part: currently in code interface file there is a lot of repetition. So I moved repeated parts of each action into quoted expressions and reuse those.
Also replaced such construction:
```elixir
if opts == [] && Keyword.keyword?(params_or_opts) do
apply(__MODULE__, elem(__ENV__.function, 0), [
unquote_splicing(arg_vars),
%{},
params_or_opts
])
else
```
With:
```elixir
{params, opts} =
if opts == [] && Keyword.keyword?(params_or_opts),
do: {%{}, params_or_opts},
else: {params_or_opts, opts}
```
And renamed `input` variables into `params`, since this is what arguments they are passed into are called.
Fix comes from the fact that repetition of the code leads to incomplete fixes, changes and inconsistencies over time. Just right …

fix: refactor out some repetition in code interface

---

.gitignore
lib/ash/data_layer/data_layer.ex
lib/ash/resource/info.ex
test/resource/info_test.exs

Added data_layer function to Ash.Resource.Info

Get datasource from resource

---

lib/ash/code_interface.ex

Continuation from #609.
Move common code that swaps opts/params and merges named args into params as `resolve_opts_params`.
Instead of doing `Keyword.take` and `Keyword.drop` to separate between subject (input/query/changeset) options and api options, use `Keyword.split`.
Good changes on their own, but now it also will be quite easy for actions `case` to return tuple `{subject_name, resolve_subject, subject}` and then define three additional functions outside of case (so no code repetition) for `subject_to_act`, `can_act` and `can_act?`. So likes of `query_to_find_by_slug`/`changeset_to_archive`/`can_publish?` can be defined automatically with code interface and the code to add such functionality is quite small - just return the subject or pass it into `api.can`/`api.can?`. Are there any …

fix: continue refactor in code interface

---

documentation/how_to/validate-changes.md

fix: Typo in validations documentation

---

lib/ash/code_interface.ex
test/code_interface_test.exs

Currently `not_found_error?` option allows to overwrite same setting of a get action interface. But only in one direction - from true to false (to force not to throw). If an action was configured with `not_found_error?: false` then passing `not_found_error?: true` option will not affect anything. This fixes this asymmetry.

fix: honor `not_found_error?: true` opt in code interface get actions

---

lib/ash/query/query.ex

Also added `@doc false` to `def for_read_opts`.

fix: remove duplicate doc for `authorize?` in `Query.for_read_opts`

---

lib/ash/actions/managed_relationships.ex

updated api functions to use changeset

---

lib/ash/resource/dsl.ex
lib/ash/resource/verifiers/verfiy_identities.ex
test/resource/identities_test.exs

* adds verifier for identity fields.
* raises error if verifier fails
* tests added
Closes #576.

adds verifier for identity fields.

---

lib/ash/resource/calculation/builtins.ex

improvement: add missing argument to calculate example

---

lib/ash/embeddable_type.ex
lib/ash/type/union.ex

This is a WIP change because I don't really know what I'm doing - I just did what Zach said.

fix: add `handle_change/3` and `prepare_change/3` to `Ash.Type.Union`

---

logos/ash_logo_pride.svg
logos/ash_logo_trans.svg

chore: add pride and trans pride versions of the logos.

---

lib/ash/plug_helpers.ex

- [-] Bug fixes include regression tests
- [-] Features include unit/acceptance tests
- [-] Refactoring
- [-] Update dependencies
Fixes spec for set_tenant and changes docs to reflect

fix set_tenant spec

---

test/flow_test/run_from_action_test.exs
test/support/flow/child.ex
test/support/flow/flows/cancel_parent_resource.ex
test/support/flow/parent.ex
test/support/flow/registry.ex

This PR adds test that recreates problem from https://github.com/ash-project/ash/issues/652

Add test that recreates problem from issue 652

---

lib/ash/engine/request.ex

The code was introduced in https://github.com/ash-project/ash/commit/3c42062861ecb862d179175fcab4efdf5075e0ca

Remove leftover commented out debug code

---

lib/ash/resource/validation/argument_equals.ex
lib/ash/resource/validation/builtins.ex

I copied `AttributeEquals` and made `ArgumentEquals` validation.
They are almost same.

feat: validate argument equality

---

documentation/topics/expressions.md

fix-doc: refer to variable instead of constant in the function body

---

lib/ash/resource/validation/argument_does_not_equal.ex
lib/ash/resource/validation/argument_in.ex
lib/ash/resource/validation/builtins.ex

I copied all attribute validations, and modified for argument validations.

feat: validate arg

---

documentation/topics/actions.md

Update documentation to include `user_id` in query.

---

lib/ash/resource/dsl.ex
lib/ash/resource/verifiers/ensure_aggregate_field_is_attribute_or_calculation.ex
test/resource/aggregates_test.exs

This PR solves this bug: https://github.com/ash-project/ash/issues/580

Feature: Ensure aggregate field is attribute or calculation. 

---

lib/ash/resource/dsl.ex

Set `patchable?: true` on attributes section of resource's DSL

Make resource's DSL attributes section patchable

---

lib/ash/page/keyset.ex
test/actions/pagination_test.exs

fix: sort operator names in keyset

---

documentation/tutorials/get-started.md

I haven't tested it out if this works properly

Add Livebook button

---

lib/ash/changeset/changeset.ex
lib/ash/resource/dsl.ex

Changeset doc formatting was broken in a couple of places. Made captialisation, back-ticking and sentences more consistent.

docs(changeset): various doc and formatting improvements

---

documentation/tutorials/get-started.md

It is a list ⛓️

---

test/actions/load_test.exs

I found another case where field_policies were not respected correctly

update test to load forbidden field through union

---

documentation/topics/pagination.md

Added a section at the bottom which details where the options are and clears up the need to setup actions and how to query for pagination.

Update pagination.md for clearer implementation and options

---

lib/ash/embeddable_type.ex

Fixes: casting an array attribute to nil

---

documentation/topics/expressions.md

Fix typo in expressions topic

---

lib/ash/actions/create/bulk.ex
lib/ash/actions/create/create.ex
lib/ash/actions/managed_relationships.ex
lib/ash/actions/update.ex
lib/ash/api/api.ex
lib/ash/changeset/changeset.ex
lib/ash/data_layer/ets/ets.ex
lib/ash/error/error.ex
lib/ash/filter/filter.ex
lib/ash/resource/change/increment.ex
test/actions/bulk/bulk_create_test.exs

improvement: rewrite bulk creates, optimize changeset functions

---

documentation/topics/relationships.md

docs: Link to the ash_postgres references documentation in the Relationships guide

---

documentation/topics/attributes.md

fix typos for attribute, writable and update_default

---

documentation/topics/identities.md

explicitly mention read action

---

test/changeset/changeset_test.exs

changeset changing_attribute? on tenant

---

documentation/topics/actions.md

docs: Add note about returning resources from generic actions.

---

documentation/dsls/DSL:-Ash.Flow.cheatmd
documentation/dsls/DSL:-Ash.Resource.cheatmd
documentation/topics/identities.md
lib/ash/actions/sort.ex
lib/ash/api/api.ex
lib/ash/data_layer/data_layer.ex
lib/ash/flow/step/create.ex
lib/ash/query/aggregate.ex
lib/ash/query/function/string_split.ex
lib/ash/query/query.ex
lib/ash/resource/actions/action/action.ex
lib/ash/resource/aggregate/aggregate.ex
lib/ash/resource/dsl.ex
lib/ash/resource/info.ex

Wether: noun
1. A castrated male sheep or goat.
Whether: conjuction
1. Used to indirect questions to introduce one alternative.
2. Used to introduce alternative possibilities.
3. Either.

docs: Spelling fix (`wether` -> `whether`).

---

documentation/topics/relationships.md

Fix module reference in Relationship Guide

---

lib/ash/type/union.ex
test/type/union_test.exs

fix: change_attribute failing on a union attribute

---

test/actions/read_test.exs

I've just updated an old app from Ash 2.6.1 to 2.17.7 and found an interesting bug I think. Providing the action option to `get!` seems to now ignore the provided action and uses the primary?
```elixir
Portal.App.get!(Portal.App.Timesheet, id, action: :details)
```

Api.get! ignores the action option

---

test/actions/multitenancy_test.exs
test/actions/read_test.exs

Fix typo in MultitenancyTest

---

lib/ash/data_layer/ets/ets.ex
test/flow_test/flow_composition_test.exs
test/flow_test/transaction_test.exs

Move `Ash.Changeset.force_change_attribute(:approved, true)` to relevant test.

Fix flow tests

---

test/policy/complex_test.exs

Remove unnecessary 'authorize?: false' and explicitly specify the filter policy results.

Enhance policy complex test

---

test/type/union_test.exs

Reproduces regression reported in #802

Bug casting embedded union arguments

---

test/resource/validation/embedded_resource_test.exs

pass the source context with data to embedded resource validations

---

documentation/topics/security.md

This updates the documentation to correctly show the best practice for passing the actor to the change.
Discussed on Discord [here](https://discord.com/channels/711271361523351632/1069610909296766998/1188013482059255808)

Update security.md to fix bug in showing when to pass the actor

---

lib/ash/error/invalid/page_requires_pagination.ex

Fix typo in pagination error

---

documentation/tutorials/get-started.md

fixed a path in get-started.md

fixed a path in get-started.md

---

documentation/topics/pagination.md

Also added important note about updated return type from querying a paginated action
I spent a bit of time yesterday puzzling over how to actually implement pagination, so I thought I could make the guide a bit clearer (and add notes about where I got stuck).

docs: Rewrite some of the pagination guide to be a bit clearer

---

lib/ash/resource/builder.ex

Fix typo in Ash.Resource.Builder

---

lib/ash/resource/builder.ex
lib/ash/resource/info.ex

Add code interface support in Info and Builder.

---

lib/ash/filter/filter.ex
lib/ash/query/function/string_join.ex
test/calculations/calculation_test.exs
test/query/function/string_join_test.exs

string_join for Ash.CiString

---

lib/ash/data_layer/ets/ets.ex
test/actions/aggregate_test.exs

Add `:decimal` aggregate support to `DataLayer.Ets` [WIP]

---

lib/ash/actions/read/relationships.ex

fix: pass in actor to api.can call

---

lib/ash.ex
lib/ash/action_input.ex
lib/ash/calculation.ex
lib/ash/changeset/changeset.ex
lib/ash/data_layer/data_layer.ex
lib/ash/plug_helpers.ex
lib/ash/query/query.ex
lib/ash/resource/change/change.ex
lib/ash/tracer/tracer.ex
lib/ash/type/type.ex

Change typespec of tenant from String.t() to term()

---

lib/ash/changeset/changeset.ex
test/actions/atomic_update_test.exs
test/actions/update_test.exs
test/policy/belongs_to_test.exs

Remove unnecessary authorize?: false in belongs_to_test

---

lib/ash/actions/read/read.ex
test/count_test.exs

fix: only count resources the actor is allowed to see

---

lib/ash/code_interface.ex

Closes #857.
As proposed in [the last comment](https://github.com/ash-project/ash/issues/857#issuecomment-1917978189) now for calculations with names that end with the question mark the following convention applies:
```elixir
is_true(...) # safe method
is_true?(...) # throwing method
``` 
This is a breaking change since it changes behavior of theoretical `is_safe?` from safe one to throwing one.

fix: change names of code interface methods for calculations

---

lib/ash/actions/read/calculations.ex

https://github.com/ash-project/ash/pull/847#issuecomment-1908463011

feat: support returning streams from mod calc

---

lib/ash/actions/update/update.ex

Fix: Pass the tenant to fully_atomic_changeset call

---

lib/ash/filter/filter.ex

needed for https://github.com/ash-project/ash_graphql/pull/113

feat: support functions in parse predicates

---

test/flow_test/authorization_test.exs

Reproducing a bug where Flow ignores the authorization.
```
mix test test/flow_test/authorization_test.exs
```

Reproducing a bug where Flow ignores the authorization.

---

test/actions/bulk/bulk_destroy_test.exs

add test for bulk_destroy with policy and query

---

lib/ash/actions/read/read.ex

the pid of async_limiter in the query's context maybe invalid due to we stop it at the end of read. So adding another checking to make sure it's still alive.
BTW, I found this issue according to the following crash:
```
[error] GenServer #PID<0.647.0> terminating
** (stop) exited in: GenServer.call(#PID<0.648.0>, {:get_and_update, #Function<0.21809672/1 in Ash.Actions.Read.AsyncLimiter.async_or_inline/3>}, 5000)
** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
(elixir 1.16.0) lib/gen_server.ex:1114: GenServer.call/3
(ash 2.19.3) lib/ash/actions/read/async_limiter.ex:26: Ash.Actions.Read.AsyncLimiter.async_or_inline/3
(elixir 1.16.0) lib/enum.ex:1708: anonymous fn/3 in Enum.map/2 …
```

fix: prevent leakage of stale async_limiter's pid 

---

lib/ash/api/api.ex

Improvements to the bulk_update and bulk_destroy functions of the Ash.Api module.

docs: Improvements to the bulk_update and bulk_destroy functions

---

lib/ash/type/struct.ex

Actual change can be done in one-liner:
```elixir
merged_load = Ash.Query.load(__MODULE__, merged_load) # __MODULE__ is Ash.Type.Struct
merged_load = Ash.Query.load(constraints[:instance_of], merged_load)
```
Other changes in `merge_load` and `can_load?` are purely cosmetical and for consistency.
For record I was just looking at types for different reasons and spotted (what I assume is) a wrong load usage.

fix: load with right module in `get_rewrites` of `Ash.Type.Struct`

---

lib/ash/actions/read/relationships.ex

Set tenant correctly when reading many_to_many relationship.

---

lib/ash/type/decimal.ex
lib/ash/type/float.ex
test/type/decimal_test.exs
test/type/float_test.exs

feat: add lt, gt constraints to float, decimal

---

test/resource/aggregates_test.exs
test/resource/resource_test.exs

chore: Add failing tests for loads with with explicit domains.

---

lib/ash/actions/aggregate.ex
lib/ash/actions/managed_relationships.ex

Fix places where tenant is not passed along

---

lib/ash/actions/helpers.ex

Hi!
In my Elixir parser CI, I noticed ash was failing to parse (problem for me!) but it lead me to notice you had this odd (yet valid!) code.
I'm not entirely sure if this is supposed to be "else []" or just drop the else, but figured I'd drop you a PR.
Thanks!

refactor: erroneous else

---

lib/ash/policy/simple_check.ex

Backport of #956. (Just simple rebase, the diff is identical.)

improvement: allow simple check to return error tuple

---

test/policy/simple_test.exs
test/support/policy_simple/domain.ex
test/support/policy_simple/resources/foo.ex

Test to easily reproduce the bug

chore: changing_attributes with `to` field failing test

---

lib/ash/changeset/changeset.ex

chore: show the correct alternatives for already validated changesets

---

documentation/how_to/upgrade.md

docs: Add upgrade note about changing `ash_apis` -> `ash_domains` in  app config

---

lib/ash/actions/sort.ex

Fixes a small typo I saw in an error message.

Fix typo in sort error message

---

lib/ash/changeset/changeset.ex
lib/ash/resource/change/builtins.ex
lib/ash/resource/change/update_change.ex
test/changeset/changeset_test.exs
test/resource/changes/update_change_test.exs

Allows mapping a change with a function

feat: add `update_change` function and builtin change

---

lib/ash.ex

fix: remove `internal?` and `stacktraces?` from common opts

---

lib/ash/actions/create/bulk.ex
lib/ash/actions/create/create.ex
lib/ash/actions/read/read.ex
lib/ash/actions/update/update.ex
test/actions/multitenancy_test.exs

improvement: call ToTenant protocol when setting tenant in actions

---

test/calculations/calculation_test.exs

chore: add failing test for calculations on private relationships

---

lib/ash/query/function/date_add.ex
test/query/function/date_add_test.exs

Fix date_add query function

---

test/calculations/calculation_test.exs

chore: failing test for strict loads on nested relationship loads

---

documentation/tutorials/get-started.md

docs: fix typo :ubject -> :subject in get-started.md

---

documentation/topics/resources/changes.md
documentation/topics/resources/domains.md

Fix a few minor typographical errors I found in the 3.0 RC guides.

Typo fixes

---

lib/ash/actions/read/relationships.ex
test/actions/load_test.exs

While filter, sorts etc are already copied from the read action into the query, using the right action is relevant, for example, when it's checked against in policies, or in preparations that check the action name from the query

improvement: use explicit read actions when reading relationships

---

documentation/topics/resources/changes.md

docs: fix typo in code snippet for change actions doc

---

test/actions/load_test.exs

fix: fix typo in load test

---

test/actions/validation_test.exs

Fixed validation tests for embedded resources

---

lib/ash/changeset/changeset.ex
lib/ash/resource/validation/attribute_present.ex
lib/ash/resource/validation/attributes_present.ex
lib/ash/resource/validation/builtins.ex
lib/ash/resource/validation/present.ex
test/actions/validation_test.exs

Closes https://github.com/ash-project/ash/issues/1015

Add attributes_present, attributes_absent.

---

lib/ash/error/forbidden.ex
lib/ash/error/framework.ex
lib/ash/error/invalid.ex
lib/ash/error/unknown.ex

use Splode.ErrorClass for error classes

---

documentation/topics/development/upgrading-to-3.0.md

docs: add more details on the behavior of accept :*

---

lib/ash.ex
lib/ash/changeset/changeset.ex
test/ash_test.exs

feat: Ash.create and Ash.update oneliner

---

documentation/topics/resources/changes.md
documentation/topics/resources/validations.md

chore: fix typo of docs

---

lib/ash/changeset/changeset.ex
lib/ash/resource/validation/attributes_present.ex

Fix typo Changeset.attributes_present? to attribute_present?

---

documentation/topics/actions/create-actions.md
documentation/topics/actions/update-actions.md

typo in documentation

---

lib/ash/changeset/changeset.ex
test/changeset/changeset_test.exs

Changeset.present? to be false when belongs_to is set to nil

---

test/actions/bulk/bulk_create_test.exs
test/actions/bulk/bulk_update_test.exs

chore: failing tests for before_transaction hooks in bulk actions

---

test/actions/bulk/bulk_create_test.exs
test/actions/bulk/bulk_destroy_test.exs
test/actions/bulk/bulk_update_test.exs

chore: failing tests for after_transaction hooks on bulk failures

---

documentation/topics/resources/domains.md

The action name is part of the `opts` keyword list

docs: Update code interface syntax in Domains guide

---

lib/ash.ex

docs: clarify functionality of `notify?` and `return_notifications?`

---

test/actions/bulk/bulk_update_test.exs

chore: failing test for bulk update with global validations

---

lib/ash/resource/change/builtins.ex

Thank you jeroen11dijk on Discord for picking this one up! :v:

docs: Fix syntax error in builtin change documentation

---

lib/ash/actions/read/relationships.ex

Fix missing tenant for many_to_many read

---

lib/ash.ex
lib/ash/actions/read/read.ex
lib/ash/actions/read/relationships.ex
lib/ash/data_layer/ets/ets.ex
lib/ash/error/query/invalid_page.ex
lib/ash/helpers.ex
lib/ash/page/keyset.ex
lib/ash/page/offset.ex
lib/ash/page/page.ex
lib/ash/page/unpaged.ex
lib/ash/query/query.ex
test/actions/load_test.exs
test/actions/pagination_test.exs
test/query_test.exs

feat: add relationship pagination

---

lib/ash/type/type.ex
test/type/array_test.exs

backport #1115 and #1116 to 2.0

---

test/calculations/calculation_test.exs

chore: add failing test for calculation loaded twice in Ash.load/3

---

test/calculations/calculation_test.exs

chore: add failing test for calculation reuse across loads

---

lib/ash/actions/read/read.ex
test/actions/load_test.exs

Maintain backwards compatibility

fix: ignore required pagination for relationships

---

test/actions/bulk/bulk_destroy_test.exs
test/actions/bulk/bulk_update_test.exs

chore: add failing tests for filter on stream bulk update/destroy

---

lib/ash/actions/destroy/bulk.ex
lib/ash/resource/change/builtins.ex
lib/ash/resource/change/cascade_destroy.ex
test/resource/changes/cascade_destroy_test.exs

feat: Add `cascade_destroy` to builtin changes.

---

lib/ash/embeddable_type.ex

fix: copy context for the other destroy calls too

---

documentation/topics/actions/destroy-actions.md

docs: fix typo on destroy actions

---

lib/ash/changeset/changeset.ex
test/actions/update_test.exs

:not_atomic was returned for a non-atomic validation even if the where condition evaluated to false

fix: check the where condition before checking validation atomicity

---

documentation/dsls/DSL:-Ash.Reactor.md
lib/ash/reactor/builders/bulk_create.ex
lib/ash/reactor/builders/create.ex
lib/ash/reactor/dsl/action_transformer.ex
lib/ash/reactor/dsl/bulk_create.ex
lib/ash/reactor/reactor.ex
lib/ash/reactor/steps/bulk_create_step.ex
lib/ash/reactor/steps/create_step.ex
test/reactor/bulk_create_test.exs

feat(Ash.Reactor): Add `bulk_create` step type.

---

documentation/how-to/test-resources.livemd

Test resource mix install patch

---

documentation/topics/security/sensitive-data.md
lib/ash/changeset/changeset.ex
lib/ash/filter/filter.ex
lib/ash/helpers.ex
test/query_test.exs

feat: Implement `show_sensitive?` config

---

lib/ash/actions/read/read.ex
lib/ash/actions/read/relationships.ex
lib/ash/page/unpaged.ex
test/actions/load_test.exs

feat: allow retrieving the count of paginated relationships

---

lib/ash/changeset/changeset.ex
test/changeset/changeset_test.exs

fix: handle list of atomic conditions (#1194)

---

lib/ash/changeset/changeset.ex

The problems appeared in the ash_mysql module that I'm currently writing when I removed the `{:atomic, :upsert}` capability from my module but left the `{:atomic, :update}` one : updates with atomics started complaining about the missing upsert capability.
I'm not 100% sure that this is the right fix, and I have no idea how I could write non regression tests for this. However tests that wrongly failed in my module now pass and all tests still pass in ash.

fix: mixup between atomic upsert vs update capability of datalayers

---

mix.exs

(screenshot borrowed from aidalgol on Discord)

docs: Remove duplicate link to mnesia in DSL docs

---

test/actions/bulk/bulk_update_test.exs

The following error is produced
1) test manual updates are supported (Ash.Test.Actions.BulkUpdateTest)
test/actions/bulk/bulk_update_test.exs:358
** (CaseClauseError) no case clause matching: nil
code: |> Ash.bulk_update!(:update_manual, %{},
stacktrace:
(ash 3.0.7) lib/ash/actions/update/bulk.ex:2076: anonymous fn/11 in Ash.Actions.Update.Bulk.run_batch/10
(elixir 1.16.2) lib/enum.ex:1264: anonymous fn/3 in Enum.flat_map/2
(stdlib 5.0.2) maps.erl:416: :maps.fold_1/4
(elixir 1.16.2) lib/enum.ex:2540: Enum.flat_map/2
(ash 3.0.7) lib/ash/actions/update/bulk.ex:1966: Ash.Actions.Update.Bulk.run_batch/10
(ash 3.0.7) lib/ash/actions/update/bulk.ex:1505: Ash.Actions.Update.Bulk.do_handle_batch/13
(ash 3.0.7) lib/ash/actions/update/bulk.ex:1042: anonymous fn/12 in …

test: demonstrate error with bulk update on manual action

---

lib/ash.ex
lib/ash/can.ex

Ensure Ash.can? returns boolean | no_return as specified in the @spec

---

documentation/topics/actions/actions.md

Fix a small mistake in the docs.

---

lib/ash/resource/validation/compare.ex

Do not validate nil

---

lib/ash/generator/generator.ex
test/generator/generator_test.exs

fix: add resource to Ash.Seed.seed! in Ash.Generator.seed!

---

lib/ash/seed.ex
test/seed_test.exs

Implements #990 
I was not sure how to write the docs correctly though.

feat: add tenant option to Ash.Seed.seed!

---

lib/ash/query/operator/eq.ex
lib/ash/query/operator/in.ex
test/query/operator/eq_test.exs
test/query/operator/in_test.exs

Try to fix the compare/2 implementations

---

lib/ash/actions/destroy/bulk.ex
test/actions/bulk/bulk_create_test.exs
test/actions/bulk/bulk_destroy_test.exs
test/actions/bulk/bulk_update_test.exs

On paper, bulk operations (create, update, destroy) currently supports a `load` option used to specify "a load statement to apply to records", provided that the `return_records?` option is also set to `true` and records are returned.
The relevant changes and unit tests are added here to verify that the `load` statement is respected and it correctly loads relationships.
Note: loading relationships with pagination on results for bulk destroys is still not supported. Indeed, relationships are currently queried using a lateral join but after the resource deletion has happened, so it looks like nothing is related.

`load` relationships on the results of bulk operations

---

lib/ash/actions/managed_relationships.ex
lib/ash/data_layer/ets/ets.ex
lib/ash/filter/filter.ex
test/actions/load_test.exs

Fix warning: using map.field notation

---

lib/ash/filter/filter.ex

Handle relationship filter on primary key

---

lib/ash/actions/destroy/bulk.ex
lib/ash/actions/update/bulk.ex

Fixes
https://github.com/ash-project/ash/discussions/1262

fix: gather notifications in main ref not tmp ref.

---

test/policy/simple_test.exs
test/support/policy_simple/domain.ex
test/support/policy_simple/resources/context.ex

add expr context in policy test

---

test/policy/simple_test.exs
test/support/policy_simple/domain.ex
test/support/policy_simple/resources/context.ex
test/support/policy_simple/resources/context/changes/do_change.ex

Add replication of forbidden error on expr using context

---

test/policy/simple_test.exs
test/support/policy_simple/resources/calculations/post_texts.ex
test/support/policy_simple/resources/user.ex

Per discussion with Zach, this isn't desired behavior.

Test case showing calculations erroneously respect policies

---

test/calculations/calculation_test.exs

chore: failing test for nested calculation loading a relationship

---

lib/ash/actions/destroy/destroy.ex

chore: fix formatting with `mix format`

---

lib/ash/type/integer.ex

fix: use correct contraint when validating min int

---

lib/mix/tasks/gen/ash.gen.resource.ex

Improve documentation example

---

test/actions/bulk/bulk_update_test.exs

chore: add failing test for bulk update with numeric constraints

---

lib/ash/type/module.ex

Module type apply_constraints for nil fix

---

lib/ash/resource/igniter.ex

fix: mix igniter.install ash --example case clause error

---

documentation/topics/resources/relationships.md

context: https://discord.com/channels/711271361523351632/711271361523351636/1263542865020325949

update relationships docs so source_attribute is not required to be unique

---

lib/ash/policy/info.ex

fix: add default to private_fields_policy in Ash.Policy.Info

---

documentation/topics/actions/generic-actions.md

As a newbie to ash, it took me a while to figure out how to call generic actions. This should help users to get started with actions.

Document how to call a Generic Action

---

lib/ash/resource/actions/action/implementation.ex

This was causing a Dialyzer error

fix: add :ok to Ash.Resource.Actions.Implementation.run/3 callback

---

test/support/enum.ex
test/type/enum_test.exs

add test for string enum 

---

.github/security.md

Fix SECURITY.md badge URL

---

documentation/topics/resources/relationships.md

Documentation - Add section regarding strict-loading for manual relationships.

---

lib/ash/resource/schema.ex
test/resource/attributes_test.exs

Add defaults and typespec to resulting Resource struct

---

lib/ash.ex
lib/ash/actions/create/bulk.ex
lib/ash/type/file.ex

Dialyzer Fixes

---

lib/ash/actions/create/bulk.ex
lib/ash/embeddable_type.ex
lib/comparable/comp.ex

Pass options without :templated tuple to after_batch 

---

.formatter.exs
documentation/dsls/DSL:-Ash.Resource.md
lib/ash.ex
lib/ash/changeset/changeset.ex
lib/ash/data_layer/ets/ets.ex
lib/ash/expr/expr.ex
lib/ash/filter/filter.ex
lib/ash/filter/runtime.ex
lib/ash/query/function/upsert_conflict.ex
lib/ash/query/query.ex
lib/ash/resource/actions/create.ex
test/actions/create_test.exs

Implement condition for upsert

---

documentation/topics/advanced/multitenancy.md

Add a small addition: using multitenancy with code interfaces 
(I couldn't find this info anywhere in the docs, only worked it out after seeing answers on the forum)

docs: using multitenancy with code interfaces

---

lib/ash.ex
lib/ash/actions/create/bulk.ex
lib/ash/data_layer/data_layer.ex
lib/ash/data_layer/ets/ets.ex
test/actions/bulk/bulk_create_test.exs

Implement `upsert_condition` for bulk create

---

documentation/topics/security/policies.md

docs: Fix code typo in Policies guide

---

lib/ash/tracer/tracer.ex

Adjacent note: I think `Ash.Tracer` methods `start_span`, `stop_span` and `set_error` should be marked with `@doc false` since they are not supposed to be part of public API and are public just so that they can be called from a macro.

fix: do not call tracer `set_metadata` with span type that it ignores

---

lib/ash/changeset/changeset.ex

Fix an error in the changeset action lifecycle example

---

documentation/topics/actions/update-actions.md

Make sure there is a caret in front of each atomic_ref occurence

---

documentation/topics/security/policies.md

fix typo in Policies doc

---

test/actions/load_test.exs

A bug we've seen in our app after upgrading to Ash 3. The example is super-contrived, but in this example attempting to reload the `campaign_upcase` calculation lazily is not actually fetching its dependencies before attempting to recalculate. The `load` function is being called, but the data is not being used.
The test fails with the following error:
```
1) test loads it allows lazy-reloading calculations that have dependencies (Ash.Test.Actions.LoadTest)
test/actions/load_test.exs:774
** (KeyError) key :name not found in: #Ash.NotLoaded<:relationship, field: :campaign>
code: Ash.load!(author, [:campaign_upcase], lazy?: true)
stacktrace:
Ash.Test.Actions.LoadTest.UpcaseName.calculate/3
test/actions/load_test.exs:216: anonymous fn/1 in Ash.Test.Actions.LoadTest.UpcaseName.calculate/3 …
```

bug: Add failing test for lazy-reloaded calculations that aren't reloading their dependencies

---

documentation/topics/resources/relationships.md

use Ash instead of Domain module for read in docs

---

test/resource/resource_test.exs

Failing test as requested.
Note that it's loading attributes on these relationships which is problematic, not loading the relationships themselves.

chore: Add failing test for loading attributes of no-attribute relationships.

---

lib/mix/tasks/patch/ash.patch.extend.ex

Use correct extensions in `ash.patch.extend.ex`

---

lib/ash/resource/igniter.ex

I found the need to add a many_to_many relationship to a Resource generated in an Igniter, and could not find a good way to do that. Rather than add some custom zipper work in the Igniter, I added a relationships editor to the Resource Igniter. I have tested this locally, but if there are tests that should be added please let me know.
If there is a better way that Ash already supports to do this I'd be happy to do it that way instead, but I couldn't find one.

Add relationship editor to Resource Igniter

---

lib/ash/changeset/changeset.ex

Addresses same issue as #1452 
It's quite complicated to produce a good test for this. I would need two resources, one of which has an array primary key and a many to many relationship.
Should I build the test or is the PR ok like this?

Fix Ash.Changeset.manage_relationships/4 for list primary keys

---

lib/ash/resource/builder.ex
test/resource/builder_test.exs

Failing tests for creating Ash.Resource.Action validation using DSL builder

---

lib/ash/policy/check/built_in_checks.ex

docs: note that contexts are not shared across queries

---

lib/mix/tasks/gen/ash.gen.resource.ex

docs: disambiguate UUIDv4 and UUIDv7

---

lib/ash/resource/dsl.ex

doc: link to builtin validations

---

test/calculations/calculation_test.exs

This PR adds a failing test for an issue I found yesterday in my own app.
My resource has a calculation with an argument, and I wanted to load a default set of extra calculations on _that_ calculation, but additionally supply extra calculations to load on the calculation at call time.
The test loads `said_hello_to`, a calculation that takes an argument and returns a User, and loads nested things on it:
* `full_name` (in a preparation)
* `full_name_with_request` (at call time)
Both loads use the same value for the calculation argument.
What I would expect to happen:
* `said_hello_to` is a User struct with both `full_name` and `full_name_with_request` calculated on it
What actually happens:
```
1) test calculations with arguments can be loaded through both in preparations and with load …
```

bug: Add failing test for loading through calculations with arguments

---

documentation/dsls/DSL:-Ash.Resource.md
lib/ash/resource/dsl.ex

docs: fix - use load instead of select in calculations

---

documentation/topics/security/policies.md

docs: fix a few typos in policies guide

---

test/filter/parent_test.exs

Add test that verify parent expression can refer relationship's attributes

---

lib/ash/policy/authorizer/authorizer.ex
lib/sat_solver/implementation.ex
lib/sat_solver/sat_solver.ex

* Consistently capitalize SAT in "SAT solver"
* Include info about the different options when prompted to install one

chore: Update error messages around SAT solvers

---

lib/ash/domain/dsl.ex
lib/ash/domain/verifiers/validate_arguments_to_code_interface.ex
lib/ash/resource/dsl.ex
lib/ash/resource/verifiers/validate_arguments_to_code_interface.ex
test/domain/domain_test.exs
test/resource/require_valid_arguments_in_code_interface_test.exs

Address https://github.com/ash-project/ash/issues/1520

Add compile-time checks for `code_interface` arguments in Resource and Domain

---

lib/ash/type/decimal.ex
test/type/decimal_test.exs

fix: use Decimal.eq? in Ash.Type.Decimal

---

documentation/dsls/DSL-Ash.Resource.md
lib/ash/resource/dsl.ex

Add examples of defining a calculation with keyword options.
Relates to #1534

Clarify how to pass options to calculate

---

lib/ash/query/query.ex

This frustrated me for like an hour. I referred to this page so many times.

Mention require in Ash.Query

---

lib/ash/resource/attribute.ex

doc: add docstring for timestamps helper macro

---

lib/ash/notifier/pub_sub/pub_sub.ex

use to_tenant instead of tenant when building notification topic

---

lib/ash/ci_string.ex
lib/ash/query/function/string_split.ex
lib/ash/query/query.ex
test/query_test.exs

Let me know if these docs help, i also ran the formatter and some files got formatted that I didn't touch.

provide docs and typespecs for ash cistring and format code

---

lib/ash/page/keyset.ex
lib/ash/page/page.ex
lib/ash/page/unpaged.ex

Add some docs and typespecs for Ash.Page

---

lib/ash/options_helpers.ex

don't document options helpers but add typespecs

---

lib/ash/generator/generator.ex
lib/ash/page/offset.ex
lib/ash/uuid.ex
lib/ash/vector.ex

add in more specs and docs

---

lib/ash/resource/validation/attribute_does_not_equal.ex
lib/ash/resource/validation/attribute_equals.ex

attribute_equals to use Comp

---

lib/ash.ex
lib/ash/can.ex

add docs and typespecs to Ash.Can module

---

lib/ash/query/query.ex
test/actions/read_test.exs

Fix not working skip_unknown_inputs opt of read action

---

lib/ash/actions/read/read.ex
lib/ash/query/aggregate.ex

fix: add tenant to Aggregate opts when building count query

---

test/policy/complex_test.exs
test/support/policy_complex/resources/comment/checks/runtime_check.ex
test/support/policy_complex/resources/comment/comment.ex

Not sure if this is the best approach to testing this, but this does represent the issue I'm seeing!

minimal repro of issues with runtime checks

---

documentation/topics/development/project-structure.md

per https://discord.com/channels/711271361523351632/711271361523351636/1313276402770120836

update project structure docs

---

documentation/topics/resources/calculations.md

fix(Docs): Missing  attr `arguments` on context

---

lib/ash/query/query.ex

chore: update for read opt docs

---

documentation/how-to/polymorphic-relationships.livemd

Fix some typos in this document.
- [V] Documentation changes

Fix some typos in the polymorphic-relationships.livemd document

---

lib/ash/action_input.ex
lib/ash/changeset/changeset.ex
test/actions/create_test.exs
test/changeset/changeset_test.exs

Fixes: https://github.com/ash-project/ash/issues/1535

feat: throw validation error when trying to set public arguments in private_arguments

---

documentation/topics/actions/generic-actions.md

chore(docs): Add Generic Action info on returning a list of resources

---

documentation/tutorials/get-started.md

docs: Remove errant backtick in Getting Started guide

---

README.md

Add RealWorld example to README - https://github.com/team-alembic/realworld

docs: Add RealWorld example to README

---

documentation/tutorials/get-started.md

docs: add to run 'mix ash.setup' in get started guide

---

documentation/tutorials/get-started.md

Docs: add example for update-validate to start-guide

---

lib/ash/code_interface.ex
test/code_interface_test.exs

fix: handle ambiguous case of empty params in code interfaces

---

test/type/map_test.exs

- [x ] Bug fixes include regression tests

Add failing tests for Ash.Type.Map, when using string constrains

---

documentation/topics/advanced/multitenancy.md

surfaced the commonly used (I assume) `all_tenants?` keyword for identities with an example.

Update multitenancy.md for extra info around identites

---

lib/ash/changeset/changeset.ex
lib/ash/expr/expr.ex
lib/ash/filter/runtime.ex
lib/ash/query/operator/is_nil.ex

feat: make atomics work even if expr err is not supported

---

.github/workflows/test-subprojects.yml

Putting this in a PR so I can see if the syntax is correct - not sure if the YAML will barf on the projects that don't have a `ref` mentioned
(of course, now I see that they don't run in branches)

chore: Update CI build for Tunez to point to the current latest branch w/ tests

---

lib/ash.ex
test/policy/simple_test.exs

fix: missing get_opts_schema authorize_with option

---

lib/ash/type/type.ex

improve docs on ash_type - custom type

---

documentation/topics/resources/notifiers.md

Fix a small typo in the notifiers docs

---

lib/ash/actions/managed_relationships.ex

fix: handle parent in rel in managed belongs to

---

lib/ash/actions/action.ex

Handles `:ok` (when an action has no return type) and `{:ok, result, notifications}` from generic actions when an action has `transaction? true`.

fix: fix handling of generic action returns with transaction enabled

---

lib/ash/query/query.ex

fix: error message on read action exception for through relationship

---

test/actions/has_many_test.exs

Following up on this [Elixir Forum post](https://elixirforum.com/t/failing-to-get-aggregation-to-work-with-parent-and-3-layer-nesting/69244).
This PR creates a failing test that reproduces a potential bug.

Failed aggregate expr with parent with 3-deep expression

---

lib/ash/resource/change/cascade_update.ex

fix: add tenant to load in cascade update

---

documentation/topics/reference/expressions.md

Fix docs: expressions date_add

---

documentation/tutorials/get-started.md

docs (get-started): Fixes missing variable re-assignment. Closes #1777.

---

documentation/topics/reference/expressions.md
lib/ash/filter/filter.ex
lib/ash/query/function/string_position.ex
test/query/function/string_position_test.exs

- [?] Chores
- [y] Documentation changes
- [y] Features include unit/acceptance tests

Add string_position expression

---

lib/ash/actions/read/read.ex
lib/ash/filter/filter.ex
test/actions/calculations_referencing_aggregates_test.exs

Related to [elixir forum issue](https://elixirforum.com/t/forbidden-error-when-trying-to-sort-on-aggregate-while-an-actor-is-required/69371)

fix: Missing actor on aggregate call

---

lib/ash/actions/read/read.ex

fix: Missing actor on aggregate resource call

---

lib/ash/code_interface.ex
test/code_interface_test.exs

fix: Missing case clause for bulk update/destroy with `get?: true` in interface

---

lib/ash/actions/action.ex

When running a generic action with `transaction? true`, this fix ensures the input.resource is not wiped from the list of resources to issue a rollback for if the transaction encounters an error.
Since the Ets-datalayer used in the test-suite doesn't have proper transaction/rollback-support, I've set up a repro which demonstrates the issue here instead: https://github.com/Torkan/ash-generic-tx-action-repro
Hopefully this can be merged as-is, and if there are any unintended consequences I'm not aware of, at least I shed some light on the issue 😄

Generic transactional actions: Don't clear input.resource from resource list in case of rollback.

---

lib/ash/changeset/changeset.ex

I think this probably should be like this 😅

fix(`changeset.ex`): fixes typo in `manage_relationship` doc example

---

lib/ash/actions/read/read.ex

Fix propagate invalid refrence error when adding calc context to sort

---

documentation/topics/resources/aggregates.md

docs: fixes a typo in `aggregates` docs

---

lib/mix/tasks/ash.codegen.ex

docs: expand moduledoc for codegen with dry-run and check flag documentation

---

lib/ash/resource/validation/compare.ex
test/resource/validation/compare_test.exs

improvement: allow is_equal and is_not_equal for compare validation

---

lib/ash/actions/create/create.ex

Fix upsert identity type error

---

test/authorizer/aggregation_check_test.exs

This is just a failing test.
The last one should pass as other cases do.

test: check aggregation

---

documentation/topics/advanced/reactor.md

Adding an example of using a transaction step.

docs: add reactor transaction example

---

documentation/topics/development/generators.md
lib/mix/tasks/gen/ash.gen.change.ex
test/mix/tasks/ash.gen.change_test.exs

feat: task for generating custom changes module

---

documentation/topics/security/sensitive-data.md

Explain how to set private_arguments using options passed to Changeset.

Update sensitive-data.md with missing option

---

lib/ash/resource/actions/action/action.ex
lib/ash/type/new_type.ex
lib/ash/type/type.ex
test/type/new_type_test.exs
test/type/type_test.exs

improvement: new type recursive validation

---

.formatter.exs
documentation/dsls/DSL-Ash.Resource.md
lib/ash/actions/read/relationships.ex
lib/ash/query/query.ex
lib/ash/resource/relationships/belongs_to.ex
lib/ash/resource/relationships/has_many.ex
lib/ash/resource/relationships/has_one.ex
lib/ash/resource/relationships/many_to_many.ex
lib/ash/resource/relationships/shared_options.ex
test/query/default_sort_in_relationship.exs
test/query/default_sort_test.exs
test/resource/relationships/belongs_to_test.exs
test/resource/relationships/has_many_test.exs
test/resource/relationships/has_one_test.exs
test/resource/relationships/many_to_many_test.exs

Default sort ash

---

lib/ash/resource/change/cascade_destroy.ex
lib/ash/resource/change/cascade_update.ex

set access_from in cascade_<update/destroy>

---

lib/ash/actions/create/bulk.ex
lib/ash/actions/destroy/bulk.ex
lib/ash/actions/update/bulk.ex
lib/ash/can.ex

fix: use the notification logic from bulk update in create

---

test/manage_relationship_test.exs

Adds failing tests for `on_match: :update` and `on_lookup: :relate_and_update`.

Add failing manage_relationship on_match and on_lookup relate/update tests

---

lib/ash/policy/check/accessing_from.ex
lib/ash/policy/check/action.ex
lib/ash/policy/check/action_type.ex
lib/ash/policy/check/actor_absent.ex
lib/ash/policy/check/actor_attribute_equals.ex
lib/ash/policy/check/actor_present.ex
lib/ash/policy/check/changing_relationships.ex
lib/ash/policy/check/context_equals.ex
lib/ash/policy/check/filtering_on.ex
lib/ash/policy/check/loading.ex
lib/ash/policy/check/resource.ex
lib/ash/policy/check/selecting.ex
lib/ash/policy/check/static.ex

Fixes as per https://elixirforum.com/t/possible-code-clean-up-in-ash-policy-or-is-it-intentional/70515

Remove duplicate impl of default policy functions

---

lib/ash/query/aggregate.ex
lib/ash/query/query.ex
test/query_test.exs

#1993 
Should I make a test? I haven't found tests that test `Query.aggregate`

fix: Accept field opt in query aggregate

---

README.md
documentation/topics/advanced/combination-queries.md
lib/ash/actions/read/calculations.ex
lib/ash/actions/read/read.ex
lib/ash/actions/sort.ex
lib/ash/data_layer/data_layer.ex
lib/ash/data_layer/ets/ets.ex
lib/ash/expr/expr.ex
lib/ash/filter/filter.ex
lib/ash/filter/runtime.ex
lib/ash/policy/authorizer/authorizer.ex
lib/ash/query/combination.ex
lib/ash/query/combination_attr.ex
lib/ash/query/query.ex
lib/ash/query/ref.ex
lib/ash/resource.ex
lib/ash/sort/sort.ex
mix.exs
test/query_test.exs
test/type/union_test.exs

See the guide for more. AshSql & AshPostgres parts will come later.

improvement: combination queries

---

documentation/dsls/DSL-Ash.Policy.Authorizer.md

docs: formatting fix for elixir code in `Ash.Policy.Authorizer`

---

lib/ash/actions/read/read.ex
lib/ash/actions/read/relationships.ex
lib/ash/resource/relationships/has_many.ex
test/actions/aggregate_test.exs

#2012 
Not sure how correct this is regarding implementation details,. 
Also I feel the test is misplaced, but it felt most convenient to make the test in that file.

enhancement: support has many limit

---

lib/ash/type/datetime.ex
lib/ash/type/time.ex
lib/ash/type/time_usec.ex
lib/ash/type/type.ex
lib/ash/type/utc_datetime.ex
lib/ash/type/utc_datetime_usec.ex
test/type/time_usec_test.exs

- [ n/a] Bug fixes include regression tests
- [✅] Chores
- [✅] Documentation changes
- [✅] Features include unit/acceptance tests
- [n/a] Refactoring
- [n/a ] Update dependencies

feat - support :time_usec

---

.formatter.exs
documentation/dsls/DSL-Ash.Resource.md

fix: Update spark formatter and cheat sheet with limit

---

test/actions/bulk/bulk_update_test.exs

Reproduces https://github.com/ash-project/ash/issues/2030
Fixed in: 
https://github.com/ash-project/ash/commit/e635e5789c43a920e7c9469fc47161068e254993
https://github.com/ash-project/ash/commit/aecaf64aa7927606327cbef30334110162699ddb

test: add bulk part update embedded attribute test

---

lib/ash/policy/authorizer/authorizer.ex

Credo failed in actions on my PR, I thought it was my HERE inspect. 😂

fix: remove inspect call in authorizer

---

lib/ash/query/operator/basic.ex
test/expr_test.exs

enhancement: support date diff expr

---

test/expr_test.exs

Fix credo large number readability issue

---

lib/ash/options_helpers.ex
lib/ash/resource/calculation/calculation.ex

Add a nimble options type for calculations.

Add an Ash.OptionsHelpers.calculation_type/0

---

documentation/topics/about_ash/alternatives.md

Just a missing dot i found reading the docs.

Docs: fix missing dot

---

lib/ash/query/query.ex
test/query_test.exs

Allow non-list input to skip_unknown_inputs opt of query

---

lib/ash/data_layer/ets/ets.ex
test/ash/data_layer/ets_test.exs

Fail when integer primary key is not supplied in ETS.
Closes https://github.com/ash-project/ash/issues/1500

feat: raise if integer primary key is not supplied in ETS

---

lib/ash/resource.ex

This is nicer in long list when records are truncated, because
relationships are likely to be `#Ash.NotLoaded<:relationship, field: ...>`
and `__meta__` to be `#Ecto.Schema.Metadata<:loaded>`.
Before:
```
%Ash.Test.Resource.ResourceTest.Leg{
pants: #Ash.NotLoaded<:relationship, field: :pants>,
__meta__: #Ecto.Schema.Metadata<:loaded>,
id: "112d3351-852b-44e4-a715-6f46436c38b9",
side: "right",
pants_id: "2ac24627-542f-4e23-8cd4-f1b18634af53"
}
```
After:
```
%Ash.Test.Resource.ResourceTest.Leg{
id: "f112cd6d-fe2f-4bec-98f2-13d2ad87cf3d",
side: "right",
pants_id: "d68fb517-f94c-4384-94c9-79e5a35e1a53",
pants: #Ash.NotLoaded<:relationship, field: :pants>,
__meta__: #Ecto.Schema.Metadata<:loaded>
}
```
I couldn't find any test related to this, so I tested this by adding a `dbg` to a test …

Inspect: put __meta__ and relationships at the end

---

lib/mix/tasks/gen/ash.gen.validation.ex
test/mix/tasks/ash.gen.validation_test.exs

Hello!
1. Fixed typo in generated boilerplate
2. Fixed typo in gen task test

fix: ash.gen.validation generates invalid callback

---

documentation/topics/about_ash/what-is-ash.md

docs: minor grammar update

---

test/actions/create_test.exs

add test to showcase issue with set_attribute

---

lib/ash.ex

we can get {:ok, nil} if error? opt is false

add nil to Ash.get spec

---

lib/ash/query/query.ex

fix: combination_of typespec

---

test/generator/generator_test.exs

Fixes #2136 and #2137 
@barnabasJ was faster than me @zachdaniel 😃

fix: support read actions and arguments in Ash.Generator.action_input/3

---

documentation/topics/actions/actions.md

added ash action lifecycle docs

---

lib/ash/test.ex
test/test_test.exs

Upgrade strip_metadata/1 to recurse on maps and handle additional metadata fields

---

documentation/topics/advanced/multi-step-actions.md

chore: typo in Multi-Step Actions guide

---

lib/ash/resource/change/cascade_destroy.ex
lib/ash/resource/dsl.ex

Update documentation for destroy and cascading destroy.

---

documentation/topics/resources/relationships.md

docs: add diagram for manage_relationship

---

test/actions/aggregate_test.exs

This is a reproduction for an issue I ran into.
It seems that modify_query is not applied when a read_action is specified for an aggregation.

test: added test for modify_query in aggregate with read_action

---

documentation/tutorials/get-started.md

Improving some parts and add small explanations

---

documentation/topics/resources/code-interfaces.md
usage-rules.md

docs: `get_by_id` typo fix

---

lib/ash/resource/dsl.ex
lib/ash/resource/verifiers/verify_filter_expressions.ex
test/resource/verify_filter_expressions_test.exs

Enhancement: filter expression verifier

---

usage-rules.md

Oneliner with a link to hexdocs

Update usage-rules.md to include Polymorphic Relationships

---

lib/ash/type/composite_type_helpers.ex
lib/ash/type/keyword.ex
lib/ash/type/map.ex
lib/ash/type/struct.ex
lib/ash/typed_struct.ex
test/type/keyword_test.exs
test/type/map_test.exs
test/type/struct_test.exs

fix: multiple errors

---

lib/ash/typed_struct.ex
test/typed_struct_test.exs

I think this covers the requirement in #2253.  Let me know if any changes are needed.
- Adds generated function head for `new!/1` for required fields
closes #2253

improvement: TypedStruct required field pattern matching

---

lib/ash/policy/check/built_in_checks.ex

Clarify that `action_type` and `relates_to_actor_via` checks also accepts list arguments

---

lib/ash/notifier/notifier.ex

https://github.com/ash-project/ash/commit/27aca515eb53f2ecb2dfc6d2c98f133a57e6ce71 added telemetry spans and uses `notification.domain` for span names but based on previous state, `Notification.new` signature and [documentation](https://github.com/ash-project/ash/blob/d10bd592905702438bc2536f1691fffbd424f065/lib/ash/action_input.ex#L933-L937) in `ActionInput` I would assume that `resource` is the only required field for `Ash.Notification`.
So this adds fallback to `Ash.Resource.Info.domain` if `notification.domain` is not set.

fix: handle notification without set domain in telemetry spans

---

documentation/topics/resources/aggregates.md

docs: custom aggregate example

---

documentation/topics/about_ash/what-is-ash.md

Fix typo in what-is-ash

---

lib/ash/changeset/changeset.ex
test/actions/validation_test.exs

Fixes #2319
I was thinking about trying to check if options are valid earlier, but saw a commit message that the option initialization was moved to runtime intentionally.
Still, it would be great for DX if such a mistake is pointed out earlier. 
The function is quite nested. Please let me know if another approach to handle the init error is preferred. The first case match is on error, to improve readability.
Edit: Force pushed to fix `mix check` that I forgot to run

fix: handle validation init errors without overriding them with validation message

---

lib/ash/info.ex
lib/mix/tasks/helpers.ex

Locally, the `Task.async_stream` doesn't make any difference in performance. Perhaps in projects with a really large amount of deps it does, so I left it in.

Improve performance of mix tasks that load extensions

---

lib/ash/changeset/changeset.ex

fix: handle atomic_refs in bulk upserts

---

documentation/topics/advanced/multitenancy.md

Added set_tenant Documentation with examples

---

lib/ash.ex
lib/ash/actions/action.ex
lib/ash/actions/create/bulk.ex
lib/ash/actions/destroy/bulk.ex
lib/ash/actions/read/read.ex
lib/ash/actions/update/bulk.ex
lib/ash/changeset/changeset.ex
lib/ash/data_layer/data_layer.ex
lib/ash/reactor/steps/transaction_step.ex
lib/mix/tasks/install/ash.install.ex
test/ash_test.exs

feat:  rollback transactions on error option

---

lib/ash/actions/bulk_manual_action_helpers.ex
lib/ash/actions/update/bulk.ex
lib/ash/changeset/changeset.ex
lib/ash/data_layer/data_layer.ex
lib/ash/data_layer/ets/ets.ex
lib/ash/query/query.ex
lib/ash/resource.ex
test/actions/bulk/bulk_update_manual_test.exs
test/actions/bulk/bulk_update_test.exs

As discussed in https://github.com/ash-project/ash_graphql/issues/372
This PR fixes notifications being nil in nested operations by using improved tracking of their respective contexts

fix: improve nested bulk action notification handling
